Repository neo-project/neo, pull requests merged in 2019-08, with the labels that each got.

#983 dotnet format
  neo.UnitTests/Consensus/UT_Consensus.cs
  neo.UnitTests/Cryptography/UT_Base58.cs
  neo.UnitTests/Cryptography/UT_Cryptography_Helper.cs
  neo.UnitTests/Cryptography/UT_MerkleTree.cs
  neo.UnitTests/IO/Caching/UT_CloneCache.cs
  neo.UnitTests/IO/Caching/UT_FifoSet.cs
  neo.UnitTests/Network/P2P/Payloads/UT_Header.cs
  neo.UnitTests/VM/UT_Helper.cs
  neo/Network/RPC/Models/RpcInvokeResult.cs
  neo/Network/RPC/Models/RpcNep5Balances.cs
  neo/Network/RPC/Models/RpcPlugin.cs
  neo/Network/RPC/Models/RpcRawMemPool.cs
  neo/Network/RPC/Models/RpcRequest.cs
  neo/Network/RPC/Models/RpcValidateAddressResult.cs
  neo/SmartContract/ApplicationEngine.cs
Labels: trivial

#1008 Patch for "Transaction failed when multi addresses in one wallet." #1007
  neo/Wallets/Wallet.cs
Labels: bug

#1030 Fix the potential risk to get null CurrentHeaderHash from Blockchain (2x)
  neo/Ledger/Blockchain.cs
Labels: port-to-3.x

#953 Set max block size
  neo.UnitTests/Consensus/UT_ConsensusContext.cs
  neo.UnitTests/SmartContract/Native/UT_PolicyContract.cs
  neo/Consensus/ChangeViewReason.cs
  neo/Consensus/ConsensusContext.cs
  neo/Consensus/ConsensusService.cs
  neo/Network/P2P/Payloads/Block.cs
  neo/Network/P2P/Payloads/BlockBase.cs
  neo/SmartContract/Native/PolicyContract.cs
Labels: enhancement, neo3-preview1

#1020 Update policy - Add maximum witness size (in bytes)
  neo.UnitTests/Network/P2P/Payloads/UT_Witness.cs
  neo/Network/P2P/Payloads/Witness.cs
Labels: enhancement, neo3-preview1

#1053 Fix consensus problem for proposed blocks with zero transactions
  neo/Consensus/ConsensusContext.cs
  neo/Consensus/ConsensusService.cs
Labels: bug, consensus
