Repository neo-project/neo, pull requests merged in 2019-11, with the labels that each got.

#1201 Remove the case of GetData in ProtocolHandlerMailbox#ShallDrop
  neo.UnitTests/Network/P2P/UT_ProtocolHandlerMailbox.cs
  neo/Network/P2P/ProtocolHandler.cs
Labels: port-to-2.x

#1203 Optimize MerkleTree (3x)
  neo/Cryptography/MerkleTree.cs
Labels: enhancement, port-to-2.x

#1207 Optimize MerkleTree (2x)
  neo/Cryptography/MerkleTree.cs
Labels: enhancement

#1190 Improve SYSCALLs: `Neo.Crypto.*`
  neo.UnitTests/Ledger/UT_Blockchain.cs
  neo.UnitTests/Network/P2P/Payloads/UT_Transaction.cs
  neo.UnitTests/Network/P2P/Payloads/UT_Witness.cs
  neo.UnitTests/SmartContract/UT_Contract.cs
  neo.UnitTests/SmartContract/UT_ContractParameterContext.cs
  neo.UnitTests/SmartContract/UT_InteropService.NEO.cs
  neo.UnitTests/SmartContract/UT_InteropService.cs
  neo.UnitTests/Wallets/SQLite/UT_VerificationContract.cs
  neo.UnitTests/Wallets/UT_Wallet.cs
  neo/Network/P2P/Payloads/Witness.cs
  neo/Network/RPC/TransactionManager.cs
  neo/SmartContract/Contract.cs
  neo/SmartContract/Helper.cs
  neo/SmartContract/InteropService.NEO.cs
  neo/SmartContract/InteropService.cs
  neo/Wallets/Wallet.cs
  neo/neo.csproj
Labels: compiler

#1229 Prevent XXE (3x)
  neo/Network/UPnP.cs
Labels: bug, port-to-2.x

#1235 Fix PublishTransaction deserialization (2x)
  neo.UnitTests/UT_PublishTransaction.cs
  neo/Network/P2P/Payloads/PublishTransaction.cs
Labels: bug

#1224 Fix Base58 issues (3x)
  neo.UnitTests/Cryptography/UT_Base58.cs
  neo/Cryptography/Base58.cs
Labels: bug, port-to-2.x

#1233 Decrease the block time threshold (3x)
  neo.UnitTests/Consensus/UT_Consensus.cs
  neo/Consensus/ConsensusService.cs
Labels: port-to-2.x

#1178 Upgrade dependencies and target frameworks
  .travis.yml
  neo.UnitTests/Extensions/NativeContractExtensions.cs
  neo.UnitTests/Extensions/Nep5NativeContractExtensions.cs
  neo.UnitTests/Network/P2P/Payloads/UT_Transaction.cs
  neo.UnitTests/SmartContract/Enumerators/UT_IteratorKeysWrapper.cs
  neo.UnitTests/SmartContract/Enumerators/UT_IteratorValuesWrapper.cs
  neo.UnitTests/SmartContract/Iterators/UT_MapWrapper.cs
  neo.UnitTests/SmartContract/Native/Tokens/UT_NeoToken.cs
  neo.UnitTests/SmartContract/Native/Tokens/UT_Nep5Token.cs
  neo.UnitTests/SmartContract/Native/UT_PolicyContract.cs
  neo.UnitTests/SmartContract/UT_ApplicationEngine.cs
  neo.UnitTests/SmartContract/UT_ContainerPlaceholder.cs
  neo.UnitTests/SmartContract/UT_InteropService.NEO.cs
  neo.UnitTests/SmartContract/UT_InteropService.cs
  neo.UnitTests/SmartContract/UT_JsonSerializer.cs
  neo.UnitTests/SmartContract/UT_NotifyEventArgs.cs
  neo.UnitTests/SmartContract/UT_SmartContractHelper.cs
  neo.UnitTests/SmartContract/UT_Syscalls.cs
  neo.UnitTests/UT_UInt160.cs
  neo.UnitTests/UT_UInt256.cs
  neo.UnitTests/VM/UT_Helper.cs
  neo.UnitTests/Wallets/NEP6/UT_NEP6Account.cs
  neo.UnitTests/neo.UnitTests.csproj
  neo/Cryptography/RIPEMD160Managed.cs
  neo/Cryptography/SCrypt.cs
  neo/Helper.cs
  neo/IO/Data/LevelDB/Native.cs
  neo/IO/Helper.cs
  neo/Ledger/Blockchain.ApplicationExecuted.cs
  neo/Network/RPC/PolicyAPI.cs
  neo/SmartContract/ApplicationEngine.cs
  neo/SmartContract/ContainerPlaceholder.cs
  neo/SmartContract/Enumerators/ConcatenatedEnumerator.cs
  neo/SmartContract/Enumerators/IEnumerator.cs
  neo/SmartContract/Enumerators/IteratorKeysWrapper.cs
  neo/SmartContract/Enumerators/IteratorValuesWrapper.cs
  neo/SmartContract/Helper.cs
  neo/SmartContract/IInteroperable.cs
  neo/SmartContract/InteropDescriptor.cs
  neo/SmartContract/InteropService.NEO.cs
  neo/SmartContract/InteropService.cs
  neo/SmartContract/Iterators/ArrayWrapper.cs
  neo/SmartContract/Iterators/ConcatenatedIterator.cs
  neo/SmartContract/Iterators/IIterator.cs
  neo/SmartContract/Iterators/MapWrapper.cs
  neo/SmartContract/Iterators/StorageIterator.cs
  neo/SmartContract/JsonSerializer.cs
  neo/SmartContract/Native/ContractMethodMetadata.cs
  neo/SmartContract/Native/NativeContract.cs
  neo/SmartContract/Native/PolicyContract.cs
  neo/SmartContract/Native/Tokens/GasToken.cs
  neo/SmartContract/Native/Tokens/NeoToken.cs
  neo/SmartContract/Native/Tokens/Nep5Token.cs
  neo/SmartContract/NotifyEventArgs.cs
  neo/VM/Helper.cs
  neo/neo.csproj
Labels: blocker

#1239 Fix Base58 issues (2x)
  neo.UnitTests/UT_Base58.cs
  neo.UnitTests/UT_Consensus.cs
  neo/Cryptography/Base58.cs
Labels: bug

#1087 New plugin interface: IStoragePlugin
  src/neo/NeoSystem.cs
  src/neo/Plugins/IStoragePlugin.cs
  src/neo/Plugins/Plugin.cs
  tests/neo.UnitTests/Consensus/UT_Consensus.cs
  tests/neo.UnitTests/Consensus/UT_ConsensusContext.cs
  tests/neo.UnitTests/Ledger/UT_Blockchain.cs
  tests/neo.UnitTests/TestBlockchain.cs
Labels: blocker
