Repository neo-project/neo, pull requests merged in 2024-05, with the labels that each got.

#3211 SmartContract: catch exception on multisignature contract parsing
  src/Neo/SmartContract/Helper.cs
  tests/Neo.UnitTests/SmartContract/UT_Helper.cs
Labels: bug, critical

#3234 fix hardfork issues
  src/Neo/ProtocolSettings.cs
  src/Neo/SmartContract/Native/ContractMethodAttribute.cs
  src/Neo/SmartContract/Native/ContractMethodMetadata.cs
  src/Neo/SmartContract/Native/CryptoLib.cs
  src/Neo/SmartContract/Native/NativeContract.cs
  src/Neo/SmartContract/Native/NeoToken.cs
Labels: waiting for review

#3240 Neo.CLI: enable hardforks for NeoFS mainnet
  src/Neo.CLI/config.fs.mainnet.json
Labels: bug, ready to merge

#3204 improve parse method in neo-cli
  src/Neo.CLI/CLI/MainService.Tools.cs
  src/Neo.CLI/CLI/ParseFunctionAttribute.cs
Labels: blocked, cosmetic

#3245 Native: include DeprecatedIn hardfork into usedHardforks
  src/Neo/SmartContract/Native/NativeContract.cs
Labels: bug

#3261 fix TraverseIterator count
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
Labels: bug

#3252 COVERALL: fix broken by changing report from lcov to cobertura
  .github/workflows/main.yml
Labels: ready to merge

#3263 fix CancelTransaction !signers.Any()
  src/Plugins/RpcServer/RpcServer.Wallet.cs
Labels: bug

#3259 Fix and Update devcontainer.json to use Dockerfile
  .devcontainer/devcontainer.dockerfile
  .devcontainer/devcontainer.json
Labels: ready to merge

#3244 [**Part-2**] Neo module/master fixes
  src/Plugins/ApplicationLogs/ApplicationLogs.csproj
  src/Plugins/ApplicationLogs/ApplicationLogs.json
  src/Plugins/ApplicationLogs/LogReader.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.csproj
  src/Plugins/DBFTPlugin/DBFTPlugin.json
  src/Plugins/Directory.Build.props
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/OracleService/OracleService.csproj
  src/Plugins/OracleService/OracleService.json
  src/Plugins/RpcServer/RpcServer.csproj
  src/Plugins/RpcServer/RpcServer.json
  src/Plugins/RpcServer/RpcServerPlugin.cs
  src/Plugins/StateService/StatePlugin.cs
  src/Plugins/StateService/StateService.csproj
  src/Plugins/StateService/StateService.json
  src/Plugins/StateService/Storage/StateStore.cs
  src/Plugins/StateService/Verification/VerificationContext.cs
  src/Plugins/StateService/Verification/VerificationService.cs
  src/Plugins/StatesDumper/StatesDumper.cs
  src/Plugins/StatesDumper/StatesDumper.csproj
  src/Plugins/StatesDumper/StatesDumper.json
  src/Plugins/StorageDumper/StorageDumper.cs
  src/Plugins/StorageDumper/StorageDumper.csproj
  src/Plugins/StorageDumper/StorageDumper.json
  src/Plugins/TokensTracker/TokensTracker.cs
  src/Plugins/TokensTracker/TokensTracker.csproj
  src/Plugins/TokensTracker/TokensTracker.json
Labels: ready to merge

#3248 COVERALL: Improve maintenance and readbility of some variables
  .github/workflows/main.yml
Labels: ready to merge

#3273 Native: remove deprecated NamedCurve enum
  src/Neo/SmartContract/Native/CryptoLib.cs
  src/Neo/SmartContract/Native/NamedCurve.cs
  src/Neo/SmartContract/Native/NamedCurveHash.cs
Labels: waiting for review, ready to merge

#3241 use datoshi as the name of the smallest unit of GAS
  src/Neo.CLI/CLI/MainService.Blockchain.cs
  src/Neo.CLI/CLI/MainService.Contracts.cs
  src/Neo.CLI/CLI/MainService.Wallet.cs
  src/Neo.CLI/CLI/MainService.cs
  src/Neo.GUI/GUI/InvokeContractDialog.cs
  src/Neo/Ledger/Blockchain.ApplicationExecuted.cs
  src/Neo/Network/P2P/Payloads/Transaction.cs
  src/Neo/ProtocolSettings.cs
  src/Neo/SmartContract/ApplicationEngine.Contract.cs
  src/Neo/SmartContract/ApplicationEngine.Crypto.cs
  src/Neo/SmartContract/ApplicationEngine.OpCodePrices.cs
  src/Neo/SmartContract/ApplicationEngine.Runtime.cs
  src/Neo/SmartContract/ApplicationEngine.Storage.cs
  src/Neo/SmartContract/ApplicationEngine.cs
  src/Neo/SmartContract/Helper.cs
  src/Neo/SmartContract/Native/ContractManagement.cs
  src/Neo/SmartContract/Native/NativeContract.cs
  src/Neo/SmartContract/Native/NeoToken.cs
  src/Neo/SmartContract/Native/OracleContract.cs
  src/Neo/SmartContract/Native/PolicyContract.cs
  src/Neo/Wallets/Helper.cs
  src/Neo/Wallets/Wallet.cs
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
  src/Plugins/RpcServer/Session.cs
  src/Plugins/RpcServer/Settings.cs
  tests/Neo.UnitTests/Extensions/NativeContractExtensions.cs
  tests/Neo.UnitTests/Ledger/UT_PoolItem.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Transaction.cs
  tests/Neo.UnitTests/SmartContract/UT_Contract.cs
  tests/Neo.UnitTests/SmartContract/UT_Helper.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropPrices.cs
Labels: waiting for review, ready to merge

#3278 [NEO CLI] Remove comments in Json file
  src/Neo.CLI/config.fs.mainnet.json
  src/Neo.CLI/config.fs.testnet.json
  src/Neo.CLI/config.json.md
  src/Neo.CLI/config.mainnet.json
  src/Neo.CLI/config.testnet.json
Labels: waiting for review

#3282 [Neo Plugin RPCServer]fix getcontractstate
  src/Plugins/RpcServer/RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_Result.cs
Labels: waiting for review

#3281 Remove StatesDumper - Minor Refactor on StorageDumper
  neo.sln
  src/Plugins/StatesDumper/PersistActions.cs
  src/Plugins/StatesDumper/Settings.cs
  src/Plugins/StatesDumper/StatesDumper.cs
  src/Plugins/StatesDumper/StatesDumper.csproj
  src/Plugins/StatesDumper/StatesDumper.json
  src/Plugins/StorageDumper/Settings.cs
  src/Plugins/StorageDumper/StorageDumper.cs
  src/Plugins/StorageDumper/StorageDumper.json
Labels: waiting for review

#3283 Remove Build Warnings
  src/Neo.GUI/Neo.GUI.csproj
  src/Neo/SmartContract/ApplicationEngine.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
  src/Plugins/StorageDumper/Settings.cs
  src/Plugins/StorageDumper/StorageDumper.cs
Labels: waiting for review

#3279 [Neo Wallet Fix] Add cert import exception
  src/Neo/Wallets/NEP6/NEP6Wallet.cs
  src/Neo/Wallets/Wallet.cs
  tests/Neo.UnitTests/Wallets/NEP6/UT_NEP6Wallet.cs
Labels: waiting for review, ready to merge
