Repository neo-project/neo, pull requests merged in 2024-12, with the labels that each got.

#3606 [Core Plugin] PR 3414 part 4. thread safe snapshot
  src/Plugins/LevelDBStore/Plugins/Storage/Snapshot.cs
Labels: Waiting for Review

#3604 Upgrade `System.Text.RegularExpressions` to fix vulnerability
  src/Plugins/OracleService/OracleService.csproj
Labels: Ready to Merge

#3447 `[Move]` Part-8 Classes into Different Library - `Neo.Extensions`
  src/Neo/Extensions/UInt160Extensions.cs
  src/Neo/Extensions/VM/EvaluationStackExtensions.cs
  src/Neo/VM/Helper.cs
  src/Plugins/RpcClient/Nep17API.cs
  tests/Neo.Network.RPC.Tests/UT_PolicyAPI.cs
  tests/Neo.Network.RPC.Tests/UT_TransactionManager.cs
Labels: Blocker, Waiting for Review, Ready to Merge

#3607 Improve `LevelDBStore`
  src/Plugins/LevelDBStore/IO/Data/LevelDB/DB.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Helper.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Iterator.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Native.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Options.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Snapshot.cs
  src/Plugins/LevelDBStore/Plugins/Storage/Snapshot.cs
  src/Plugins/LevelDBStore/Plugins/Storage/Store.cs
  tests/Neo.Plugins.Storage.Tests/StoreTest.cs
Labels: Ready to Merge

#3609 Update Readme.md
  README.md
Labels: Ready to Merge

#3616 feat: add readonly StorageKeys to eliminate some allocations
  src/Neo/SmartContract/Native/LedgerContract.cs
  src/Neo/SmartContract/Native/NeoToken.cs
  src/Neo/SmartContract/Native/PolicyContract.cs
Labels: Ready to Merge

#3621 Fix comment: `DataCache.GetInternal` throws `KeyNotFoundException` on key not exists
  src/Neo/Persistence/ClonedCache.cs
  src/Neo/Persistence/DataCache.cs
  src/Neo/Persistence/SnapshotCache.cs
Labels: Waiting for Review

#3449 `[Move]` Part-10 Classes into Different Library - `Neo.Extensions`
  src/Neo/Extensions/SmartContract/ContractParameterExtensions.cs
Labels: Waiting for Review

#3614 [Add] Get Accounts and Balances for GasToken
  src/Neo/Extensions/SmartContract/GasTokenExtensions.cs
  src/Neo/SmartContract/Native/FungibleToken.cs
  tests/Neo.UnitTests/Extensions/UT_GasTokenExtensions.cs
Labels: Ready to Merge

#3620 [Fixed] Dotnet version for DevContainer
  .devcontainer/devcontainer.dockerfile
Labels: Ready to Merge

#3625 [`Move`]: move unit-tests of `DataCache` to corresponding directory
  tests/Neo.UnitTests/Persistence/UT_CloneCache.cs
  tests/Neo.UnitTests/Persistence/UT_DataCache.cs
Labels: Ready to Merge

#3623 [`Fix`]: remove the only compiler warning
  benchmarks/Neo.Extensions.Benchmarks/Neo.Extensions.Benchmarks.csproj
  benchmarks/Neo.VM.Benchmarks/Neo.VM.Benchmarks.csproj
  benchmarks/Neo.VM.Benchmarks/OpCode/BenchmarkEngine.cs
  benchmarks/Neo.VM.Benchmarks/Program.cs
Labels: Ready to Merge

#3626 [`Fix`]: `UInt160.TryParse` when source has whitespaces
  src/Neo/UInt160.cs
  tests/Neo.UnitTests/UT_UInt160.cs
Labels: Ready to Merge

#3624 [`Add`]: add missing unit-tests for `LogStorageStore`
  tests/Neo.Plugins.ApplicationLogs.Tests/UT_LogStorageStore.cs
Labels: Ready to Merge

#3630 [Plugin RpcServer] fix issue 3629
  src/Plugins/RpcServer/RpcException.cs
  src/Plugins/RpcServer/RpcServer.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
Labels: Ready to Merge

#3186 Base58 perfomance patch
  src/Neo/Cryptography/Base58.cs
Labels: Ready to Merge, UT-Required

#3496 [`Fix`]: integer overflow in `JumpTable.SubStr `
  src/Neo.VM/JumpTable/JumpTable.Splice.cs
  src/Neo/SmartContract/ApplicationEngine.cs
  tests/Neo.VM.Tests/Tests/OpCodes/Splice/SUBSTR.json
Labels: Bug, Critical, Need Update, Hardfork

#3599 Fix NEO callstates
  src/Neo/ProtocolSettings.cs
  src/Neo/SmartContract/Native/ContractMethodAttribute.cs
  src/Neo/SmartContract/Native/ContractMethodMetadata.cs
  src/Neo/SmartContract/Native/CryptoLib.cs
  src/Neo/SmartContract/Native/LedgerContract.cs
  src/Neo/SmartContract/Native/NativeContract.cs
  src/Neo/SmartContract/Native/NeoToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NeoToken.cs
  tests/Neo.UnitTests/UT_ProtocolSettings.cs
Labels: Bug, Waiting for Review, Ready to Merge, Hardfork

#3634 public abstract class Cache and FIFOCache
  src/Neo.IO/Caching/Cache.cs
  src/Neo.IO/Caching/FIFOCache.cs
Labels: Waiting for Review

#3636 fix tests error
  src/Neo/SmartContract/ApplicationEngine.cs
Labels: Ready to Merge

#3597 NeoToken: accept candidate registration via onNEP17Payment
  src/Neo/SmartContract/Native/NeoToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NeoToken.cs
Labels: Waiting for Review, Hardfork

#3635 Fix HF_Echidna ut
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngine.Contract.cs
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngineProvider.cs
  tests/Neo.UnitTests/SmartContract/UT_Contract.cs
  tests/Neo.UnitTests/SmartContract/UT_Helper.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropPrices.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.NEO.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
  tests/Neo.UnitTests/SmartContract/UT_JsonSerializer.cs
  tests/Neo.UnitTests/SmartContract/UT_NotifyEventArgs.cs
  tests/Neo.UnitTests/SmartContract/UT_Syscalls.cs
  tests/Neo.UnitTests/VM/UT_Helper.cs
Labels: Waiting for Review

#3641 [`Remove`]: some unnecessary old implementations for benchmark
  benchmarks/Neo.Benchmarks/Benchmarks.UInt160.cs
  benchmarks/Neo.Benchmarks/OldUInt160.cs
  benchmarks/Neo.Extensions.Benchmarks/Benchmark.ByteArrayComparer.cs
  benchmarks/Neo.Extensions.Benchmarks/OldByteArrayComparer.cs
  src/Neo.VM/Cryptography/BitOperations.cs
Labels: Waiting for Review

#3639 Extensible capabilities and ArchivalNode
  src/Neo.CLI/CLI/MainService.Network.cs
  src/Neo/Network/P2P/Capabilities/ArchivalNodeCapability.cs
  src/Neo/Network/P2P/Capabilities/FullNodeCapability.cs
  src/Neo/Network/P2P/Capabilities/NodeCapability.cs
  src/Neo/Network/P2P/Capabilities/NodeCapabilityType.cs
  src/Neo/Network/P2P/Capabilities/UnknownCapability.cs
  src/Neo/Network/P2P/Payloads/VersionPayload.cs
  tests/Neo.UnitTests/Network/P2P/Capabilities/UT_ArchivalNodeCapability.cs
  tests/Neo.UnitTests/Network/P2P/Capabilities/UT_UnknownCapability.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_VersionPayload.cs
Labels: Waiting for Review, Ready to Merge

#3643 NeoToken: add NEP-27 to supported standards list starting from Echidna
  src/Neo/SmartContract/Native/FungibleToken.cs
  src/Neo/SmartContract/Native/NativeContract.cs
  src/Neo/SmartContract/Native/NeoToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
Labels: Hardfork

#3615 [Add] GetStorage for ContractState
  src/Neo/Extensions/SmartContract/ContractStateExtensions.cs
  src/Plugins/RpcServer/RpcServer.Blockchain.cs
  tests/Neo.UnitTests/Extensions/UT_ContractStateExtensions.cs
Labels: Waiting for Review

#3647 P2P: fix `UnknownCapability`validation and maintainig
  src/Neo/Network/P2P/Capabilities/UnknownCapability.cs
  src/Neo/Network/P2P/Payloads/NetworkAddressWithTime.cs
  src/Neo/Network/P2P/Payloads/VersionPayload.cs
  tests/Neo.UnitTests/Network/P2P/Capabilities/UT_UnknownCapability.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_NetworkAddressWithTime.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_VersionPayload.cs
Labels: Waiting for Review

#3648 [Core Crypto] Optimize hash
  src/Neo/Cryptography/Helper.cs
Labels: Waiting for Review, Ready to Merge

#3638 [`Optimization`]: `HexToBytes` and `TryParse` of `UInt160`, `UInt256`
  benchmarks/Neo.Extensions.Benchmarks/Benchmark.StringExtensions.cs
  benchmarks/Neo.Extensions.Benchmarks/Program.cs
  src/Neo.Extensions/StringExtensions.cs
  src/Neo/UInt160.cs
  src/Neo/UInt256.cs
  tests/Neo.Extensions.Tests/UT_StringExtensions.cs
Labels: Waiting for Review

#3642 [`Add`]: add `IReadOnlyStoreView`
  benchmarks/Neo.Benchmarks/Neo.Benchmarks.csproj
  benchmarks/Neo.Benchmarks/Persistence/Bechmarks_ReadOnlyStoreView.cs
  benchmarks/Neo.Benchmarks/Program.cs
  src/Neo/Persistence/DataCache.cs
  src/Neo/Persistence/IReadOnlyStoreView.cs
  src/Neo/Persistence/ReadOnlyStoreView.cs
  tests/Neo.UnitTests/Persistence/UT_ReadOnlyStoreView.cs
Labels: Ready to Merge

#3646 ut: fix HF_Echidna unit tests
  src/Neo/ProtocolSettings.cs
Labels: Waiting for Review, Ready to Merge

#3640 [`Style`]: use standard style of `ReadOnlyStore.TryGet`
  src/Neo/Persistence/IReadOnlyStore.cs
  src/Neo/Persistence/SnapshotCache.cs
  src/Plugins/ApplicationLogs/Store/LogStorageStore.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.cs
  src/Plugins/MPTTrie/Cryptography/MPTTrie/Cache.cs
  src/Plugins/StateService/Storage/StateSnapshot.cs
Labels: Ready to Merge

#3610 [Add] Get Accounts and Balances for NeoToken
  src/Neo/Extensions/SmartContract/NeoTokenExtensions.cs
  tests/Neo.UnitTests/Extensions/UT_NeoTokenExtensions.cs
Labels: Ready to Merge
