Repository neo-project/neo, pull requests merged in 2024-08, with the labels that each got.

#3441 [Neo Core Add] add char support
  src/Neo/VM/Helper.cs
  tests/Neo.UnitTests/VM/UT_Helper.cs
Labels: ready to merge

#3444 [`dbft`] Prevent Store Creation
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.cs
Labels: blocked, waiting for review, ready to merge, Plugins

#3334 [Neo Core Bug] fix compound type reference issue
  benchmarks/Neo.VM.Benchmarks/Benchmarks.Types.cs
  benchmarks/Neo.VM.Benchmarks/TestArray.cs
  benchmarks/Neo.VM.Benchmarks/TestStruct.cs
  src/Neo.VM/EvaluationStack.cs
  src/Neo.VM/Neo.VM.csproj
  src/Neo.VM/Types/Array.cs
  src/Neo.VM/Types/CompoundType.cs
  src/Neo.VM/Types/Map.cs
  tests/Neo.VM.Tests/UT_ReferenceCounter.cs
Labels: waiting for review, ready to merge

#3426 Fix plugin exception
  src/Neo/Ledger/Blockchain.cs
  src/Neo/Plugins/Plugin.cs
  src/Neo/Plugins/PluginSettings.cs
  src/Neo/Plugins/UnhandledExceptionPolicy.cs
  src/Plugins/ApplicationLogs/ApplicationLogs.json
  src/Plugins/ApplicationLogs/LogReader.cs
  src/Plugins/ApplicationLogs/Settings.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.json
  src/Plugins/DBFTPlugin/Settings.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/OracleService/OracleService.json
  src/Plugins/OracleService/Settings.cs
  src/Plugins/RpcServer/RpcServer.json
  src/Plugins/RpcServer/RpcServerPlugin.cs
  src/Plugins/RpcServer/Settings.cs
  src/Plugins/StateService/Settings.cs
  src/Plugins/StateService/StatePlugin.cs
  src/Plugins/StateService/StateService.json
  src/Plugins/StorageDumper/Settings.cs
  src/Plugins/StorageDumper/StorageDumper.cs
  src/Plugins/StorageDumper/StorageDumper.json
  src/Plugins/TokensTracker/TokensTracker.cs
  src/Plugins/TokensTracker/TokensTracker.json
  tests/Neo.UnitTests/Plugins/TestPlugin.cs
  tests/Neo.UnitTests/Plugins/UT_Plugin.cs
Labels: ready to merge

#3450 [Neo Json Fix] Json null tests
  src/Neo.Json/JArray.cs
  tests/Neo.Json.UnitTests/UT_JArray.cs
Labels: bug, ready to merge

#3453 [Neo Core StdLib] Add Base64url
  src/Neo.CLI/config.fs.mainnet.json
  src/Neo.CLI/config.json
  src/Neo.CLI/config.mainnet.json
  src/Neo.CLI/config.testnet.json
  src/Neo/Neo.csproj
  src/Neo/SmartContract/Native/StdLib.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_StdLib.cs
Labels: waiting for review, hardfork

#3458 [fixedbug] RpcServer findstorage
  src/Plugins/RpcServer/RpcServer.Blockchain.cs
Labels: ready to merge

#3465 v3.7.6
  .github/workflows/main.yml
  src/Directory.Build.props
Labels: ready to merge

#3468 Set `Password` to `SecureString` for Wallet
  src/Neo.Extensions/Neo.Extensions.csproj
  src/Neo.Extensions/SecureStringExtensions.cs
  src/Neo/Wallets/NEP6/NEP6Account.cs
  src/Neo/Wallets/NEP6/NEP6Wallet.cs
  tests/Neo.Extensions.Tests/UT_SecureStringExtensions.cs
  tests/Neo.UnitTests/Wallets/NEP6/UT_NEP6Account.cs
Labels: feature, waiting for review

#3457 [Neo Plugin RPCServer] Rpc parameters. Part I
  src/Plugins/RpcServer/Model/BlockHashOrIndex.cs
  src/Plugins/RpcServer/Model/ContractNameOrHashOrId.cs
  src/Plugins/RpcServer/ParameterConverter.cs
  src/Plugins/RpcServer/RpcMethodWithParamsAttribute.cs
  src/Plugins/RpcServer/RpcServer.Blockchain.cs
  src/Plugins/RpcServer/RpcServer.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_Parameters.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
Labels: waiting for review, ready to merge

#3461 test RpcServer.Utilities, .SmartContract and .Wallet
  src/Plugins/RpcServer/RpcErrorFactory.cs
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
  src/Plugins/RpcServer/RpcServer.Utilities.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Utilities.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Wallet.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.cs
Labels: waiting for review, ready to merge, NGD Review

#3408 `[Move]` Part-4 Classes into Different Library - `Neo.Extensions`
  src/Neo.CLI/CLI/MainService.Network.cs
  src/Neo.Extensions/AssemblyExtensions.cs
  src/Neo.Extensions/Collections/HashSetExtensions.cs
  src/Neo.Extensions/DateTimeExtensions.cs
  src/Neo.Extensions/Net/IpAddressExtensions.cs
  src/Neo.Extensions/RandomExtensions.cs
  src/Neo.Extensions/StringExtensions.cs
  src/Neo.GUI/GUI/CreateMultiSigContractDialog.cs
  src/Neo.GUI/GUI/ImportCustomContractDialog.cs
  src/Neo.GUI/GUI/ParametersEditor.cs
  src/Neo.IO/Caching/HashSetCache.cs
  src/Neo.IO/Neo.IO.csproj
  src/Neo/Cryptography/ECC/ECCurve.cs
  src/Neo/Extensions/HashSetExtensions.cs
  src/Neo/Helper.cs
  src/Neo/NeoSystem.cs
  src/Neo/Network/P2P/Payloads/NetworkAddressWithTime.cs
  src/Neo/Network/P2P/Payloads/PingPayload.cs
  src/Neo/Network/P2P/Payloads/VersionPayload.cs
  src/Neo/Network/P2P/Peer.cs
  src/Neo/Network/P2P/TaskManager.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.MakePayload.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
  src/Plugins/RpcClient/RpcClient.cs
  src/Plugins/RpcClient/Utility.cs
  src/Plugins/TokensTracker/Trackers/NEP-17/Nep17Tracker.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Trie.cs
  tests/Neo.Extensions.Tests/Collections/UT_HashSetExtensions.cs
  tests/Neo.Extensions.Tests/Neo.Extensions.Tests.csproj
  tests/Neo.Extensions.Tests/Net/UT_IpAddressExtensions.cs
  tests/Neo.Extensions.Tests/UT_AssemblyExtensions.cs
  tests/Neo.Extensions.Tests/UT_DateTimeExtensions.cs
  tests/Neo.Extensions.Tests/UT_RandomExtensions.cs
  tests/Neo.Extensions.Tests/UT_StringExtensions.cs
  tests/Neo.Network.RPC.Tests/UT_ContractClient.cs
  tests/Neo.Network.RPC.Tests/UT_Nep17API.cs
  tests/Neo.UnitTests/Cryptography/ECC/UT_ECFieldElement.cs
  tests/Neo.UnitTests/Cryptography/ECC/UT_ECPoint.cs
  tests/Neo.UnitTests/Cryptography/UT_Base58.cs
  tests/Neo.UnitTests/Cryptography/UT_Crypto.cs
  tests/Neo.UnitTests/IO/UT_MemoryReader.cs
  tests/Neo.UnitTests/Ledger/UT_MemoryPool.cs
  tests/Neo.UnitTests/SmartContract/Manifest/UT_ContractManifest.cs
  tests/Neo.UnitTests/SmartContract/UT_SmartContractHelper.cs
  tests/Neo.UnitTests/TestUtils.Block.cs
  tests/Neo.UnitTests/TestUtils.Transaction.cs
  tests/Neo.UnitTests/UT_Helper.cs
  tests/Neo.UnitTests/Wallets/NEP6/UT_NEP6Contract.cs
  tests/Neo.UnitTests/Wallets/NEP6/UT_NEP6Wallet.cs
Labels: blocker, ready to merge

#3466 Add UT Neo.IO
  src/Neo.IO/Caching/KeyedCollectionSlim.cs
  tests/Neo.UnitTests/IO/Caching/UT_KeyedCollectionSlim.cs
  tests/Neo.UnitTests/IO/UT_MemoryReader.cs
Labels: waiting for review, NGD Review

#3469 improve error message when wrong wallet is opened
  src/Neo/Wallets/Helper.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
Labels: ready to merge

#3460 Update UT RpcServer
  src/Neo/Network/P2P/Peer.cs
  src/Plugins/RpcServer/RpcServer.Node.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Node.cs
  tests/Neo.UnitTests/Extensions/NativeContractExtensions.cs
Labels: ready to merge

#3470 test GetApplicationLog
  src/Plugins/ApplicationLogs/LogReader.cs
  tests/Neo.Plugins.ApplicationLogs.Tests/Neo.Plugins.ApplicationLogs.Tests.csproj
  tests/Neo.Plugins.ApplicationLogs.Tests/UT_LogReader.cs
Labels: ready to merge, unit tests, Plugins

#3467 Add UT Neo.Extensions
  src/Neo.Extensions/BigIntegerExtensions.cs
  tests/Neo.Extensions.Tests/UT_BigIntegerExtensions.cs
  tests/Neo.Extensions.Tests/UT_ByteExtensions.cs
Labels: waiting for review, unit tests, NGD Review
