Repository neo-project/neo, pull requests merged in 2024-03, with the labels that each got.

#3154 Expose committee address
  src/Neo/SmartContract/Native/NeoToken.cs
Labels: help wanted, blocked, waiting for review

#3171 Allow to get the native contract state without a projectSettings
  src/Neo/SmartContract/Native/NativeContract.cs
Labels: waiting for review

#3174 Optimize crypto
  src/Neo/Cryptography/Crypto.cs
  src/Neo/Cryptography/ECC/ECPoint.cs
  src/Neo/IO/Caching/ECDsaCache.cs
  tests/Neo.UnitTests/Cryptography/ECC/UT_ECPoint.cs
Labels: bug

#3170 Optimize contract calls
  src/Neo/SmartContract/ContractState.cs
  src/Neo/SmartContract/IInteroperableVerifiable.cs
  src/Neo/SmartContract/Native/ContractManagement.cs
  src/Neo/SmartContract/NefFile.cs
  src/Neo/SmartContract/StorageItem.cs
Labels: waiting for review

#3177 [Crypto Add] add secp256K1 Sign
  src/Neo.GUI/GUI/SigningDialog.cs
  src/Neo/Cryptography/Crypto.cs
  src/Neo/Wallets/Helper.cs
  tests/Neo.UnitTests/Cryptography/UT_Crypto.cs
  tests/Neo.UnitTests/SmartContract/Manifest/UT_ContractGroup.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.NEO.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
Labels: waiting for review

#3180 Upgrade to `dotnet` 8.0
  .devcontainer/devcontainer.json
  .github/workflows/main.yml
  benchmarks/Neo.Benchmarks/Neo.Benchmarks.csproj
  benchmarks/Neo.VM.Benchmarks/Neo.VM.Benchmarks.csproj
  global.json
  src/Directory.Build.props
  src/Neo.CLI/Neo.CLI.csproj
  src/Neo.ConsoleService/Neo.ConsoleService.csproj
  src/Neo.Cryptography.BLS12_381/Neo.Cryptography.BLS12_381.csproj
  src/Neo.Extensions/Neo.Extensions.csproj
  src/Neo.GUI/Neo.GUI.csproj
  src/Neo.IO/Neo.IO.csproj
  src/Neo.Json/Neo.Json.csproj
  src/Neo.VM/Neo.VM.csproj
  src/Neo/Neo.csproj
  tests/Directory.Build.props
  tests/Neo.ConsoleService.Tests/Neo.ConsoleService.Tests.csproj
  tests/Neo.Cryptography.BLS12_381.Tests/Neo.Cryptography.BLS12_381.Tests.csproj
  tests/Neo.Json.UnitTests/Neo.Json.UnitTests.csproj
  tests/Neo.UnitTests/Neo.UnitTests.csproj
  tests/Neo.VM.Tests/Neo.VM.Tests.csproj
Labels: waiting for review

#3182 Remove `net7.0` framework
  benchmarks/Neo.Benchmarks/Neo.Benchmarks.csproj
  benchmarks/Neo.VM.Benchmarks/Neo.VM.Benchmarks.csproj
  src/Neo.CLI/Neo.CLI.csproj
  src/Neo.ConsoleService/Neo.ConsoleService.csproj
  src/Neo.Cryptography.BLS12_381/Neo.Cryptography.BLS12_381.csproj
  src/Neo.Extensions/Neo.Extensions.csproj
  src/Neo.GUI/Neo.GUI.csproj
  src/Neo.IO/Neo.IO.csproj
  src/Neo.Json/Neo.Json.csproj
  src/Neo.VM/Neo.VM.csproj
  src/Neo/Neo.csproj
  tests/Neo.ConsoleService.Tests/Neo.ConsoleService.Tests.csproj
  tests/Neo.Cryptography.BLS12_381.Tests/Neo.Cryptography.BLS12_381.Tests.csproj
  tests/Neo.Json.UnitTests/Neo.Json.UnitTests.csproj
  tests/Neo.UnitTests/Neo.UnitTests.csproj
  tests/Neo.VM.Tests/Neo.VM.Tests.csproj
Labels: waiting for review

#3183 Repo Configuration Fixes
  .github/workflows/main.yml
  global.json
Labels: waiting for review
