Repository neo-project/neo, pull requests merged in 2024-09, with the labels that each got.

#3476 Add some UT
  tests/Neo.Network.RPC.Tests/RpcTestCases.json
  tests/Neo.Network.RPC.Tests/UT_RpcClient.cs
  tests/Neo.Network.RPC.Tests/UT_Utility.cs
Labels: ready to merge, unit tests, NGD Review

#3472 Update ConstantTimeUtility.cs
  src/Neo.Cryptography.BLS12_381/ConstantTimeUtility.cs
Labels: bug, ready to merge

#3475 Test OracleService
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/OracleService/OracleService.csproj
  src/Plugins/OracleService/Settings.cs
  tests/Neo.Plugins.OracleService.Tests/E2E_Https.cs
  tests/Neo.Plugins.OracleService.Tests/TestBlockchain.cs
  tests/Neo.Plugins.OracleService.Tests/TestUtils.cs
  tests/Neo.Plugins.OracleService.Tests/UT_OracleService.cs
  tests/Neo.Plugins.OracleService.Tests/config.json
Labels: ready to merge, unit tests

#3479 [Neo Plugin RPC] update rpc node methods signatures to use explicit parameter types.
  src/Plugins/RpcServer/RpcServer.Node.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Node.cs
Labels: waiting for review

#3483 Fixing errors in comments
  src/Neo.VM/JumpTable/JumpTable.Compound.cs
  src/Neo.VM/OpCode.cs
Labels: waiting for review

#3482 parse nef file scripts
  src/Neo.CLI/CLI/MainService.Tools.cs
Labels: ready to merge

#3486 [Neo VM Style] Throw exception for Integer that is larger than 32 bytes
  src/Neo.VM/ScriptBuilder.cs
  tests/Neo.VM.Tests/UT_ScriptBuilder.cs
Labels: ready to merge

#3498 fixed bug in RpcError
  src/Plugins/RpcServer/RpcError.cs
Labels: ready to merge

#3501 fix: concurrency conflict in HeaderCache.Count
  src/Neo/Ledger/HeaderCache.cs
  tests/Neo.UnitTests/Ledger/UT_HeaderCache.cs
Labels: ready to merge

#3477 [`Add`] Transaction Builder
  src/Neo/Builders/AndConditionBuilder.cs
  src/Neo/Builders/OrConditionBuilder.cs
  src/Neo/Builders/SignerBuilder.cs
  src/Neo/Builders/TransactionAttributesBuilder.cs
  src/Neo/Builders/TransactionBuilder.cs
  src/Neo/Builders/WitnessBuilder.cs
  src/Neo/Builders/WitnessConditionBuilder.cs
  src/Neo/Builders/WitnessRuleBuilder.cs
  tests/Neo.UnitTests/Builders/UT_SignerBuilder.cs
  tests/Neo.UnitTests/Builders/UT_TransactionAttributesBuilder.cs
  tests/Neo.UnitTests/Builders/UT_TransactionBuilder.cs
  tests/Neo.UnitTests/Builders/UT_WitnessBuilder.cs
  tests/Neo.UnitTests/Builders/UT_WitnessConditionBuilder.cs
  tests/Neo.UnitTests/Builders/UT_WitnessRuleBuilder.cs
Labels: ready to merge

#3493 [`Fix`] Neo Plugins github nuget
  .editorconfig
  .github/workflows/pkgs-delete.yml
Labels: ready to merge

#3409 `[Move]` Part-5 Classes into Different Library - `Neo.Extensions`
  src/Neo.Extensions/StringExtensions.cs
  src/Neo.Extensions/UnsafeData.cs
  src/Neo/Extensions/Collections/ICollectionExtensions.cs
  src/Neo/Extensions/MemoryExtensions.cs
  src/Neo/IO/Caching/ReflectionCache.cs
  src/Neo/IO/Helper.cs
  src/Neo/Network/P2P/Message.cs
  src/Neo/Network/P2P/Payloads/AddrPayload.cs
  src/Neo/Network/P2P/Payloads/Block.cs
  src/Neo/Network/P2P/Payloads/Conditions/AndCondition.cs
  src/Neo/Network/P2P/Payloads/Conditions/OrCondition.cs
  src/Neo/Network/P2P/Payloads/ExtensiblePayload.cs
  src/Neo/Network/P2P/Payloads/FilterAddPayload.cs
  src/Neo/Network/P2P/Payloads/FilterLoadPayload.cs
  src/Neo/Network/P2P/Payloads/HeadersPayload.cs
  src/Neo/Network/P2P/Payloads/InvPayload.cs
  src/Neo/Network/P2P/Payloads/MerkleBlockPayload.cs
  src/Neo/Network/P2P/Payloads/OracleResponse.cs
  src/Neo/Network/P2P/Payloads/Signer.cs
  src/Neo/Network/P2P/Payloads/Transaction.cs
  src/Neo/Network/P2P/Payloads/Witness.cs
  src/Neo/SmartContract/MethodToken.cs
  src/Neo/SmartContract/Native/LedgerContract.cs
  src/Neo/SmartContract/Native/NeoToken.cs
  src/Neo/SmartContract/Native/TransactionState.cs
  src/Neo/SmartContract/Native/TrimmedBlock.cs
  src/Neo/SmartContract/NefFile.cs
  src/Neo/Wallets/Helper.cs
  src/Plugins/ApplicationLogs/Store/States/BlockLogState.cs
  src/Plugins/ApplicationLogs/Store/States/EngineLogState.cs
  src/Plugins/ApplicationLogs/Store/States/ExecutionLogState.cs
  src/Plugins/ApplicationLogs/Store/States/NotifyLogState.cs
  src/Plugins/ApplicationLogs/Store/States/TransactionEngineLogState.cs
  src/Plugins/ApplicationLogs/Store/States/TransactionLogState.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.Get.cs
  src/Plugins/DBFTPlugin/Messages/ConsensusMessage.cs
  src/Plugins/DBFTPlugin/Messages/PrepareRequest.cs
  src/Plugins/DBFTPlugin/Messages/RecoveryMessage/RecoveryMessage.ChangeViewPayloadCompact.cs
  src/Plugins/DBFTPlugin/Messages/RecoveryMessage/RecoveryMessage.CommitPayloadCompact.cs
  src/Plugins/DBFTPlugin/Messages/RecoveryMessage/RecoveryMessage.PreparationPayloadCompact.cs
  src/Plugins/DBFTPlugin/Messages/RecoveryMessage/RecoveryMessage.cs
  src/Plugins/MPTTrie/Cryptography/MPTTrie/Node.Extension.cs
  src/Plugins/MPTTrie/Cryptography/MPTTrie/Node.Leaf.cs
  src/Plugins/MPTTrie/Cryptography/MPTTrie/Node.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
  src/Plugins/SQLiteWallet/VerificationContract.cs
  src/Plugins/StateService/Network/Vote.cs
  src/Plugins/StateService/Storage/StateStore.cs
  src/Plugins/StateService/Verification/VerificationService.cs
  src/Plugins/TokensTracker/Extensions.cs
  tests/Neo.Extensions.Tests/UT_StringExtensions.cs
  tests/Neo.Extensions.Tests/UT_UnsafeData.cs
  tests/Neo.UnitTests/IO/UT_IOHelper.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_NetworkAddressWithTime.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_VersionPayload.cs
  tests/Neo.UnitTests/TestUtils.Transaction.cs
Labels: ready to merge

#3502 fix: always throw `DivideByZeroException ` when `BloomFilter` is empty
  src/Neo/Cryptography/BloomFilter.cs
  tests/Neo.UnitTests/Cryptography/UT_BloomFilter.cs
Labels: bug, waiting for review, need update

#3500 fix: concurrency conflict in MemPool.TryRemoveUnVerified
  src/Neo/Ledger/MemoryPool.cs
  tests/Neo.UnitTests/Ledger/UT_MemoryPool.cs
Labels: ready to merge

#3504 [NeoVM] update rvcount error message
  src/Neo.VM/JumpTable/JumpTable.Control.cs
Labels: waiting for review
