Repository neo-project/neo, pull requests merged in 2024-06, with the labels that each got.

#3288 [Neo MemStore] fix memstore commit bug
  src/Neo/Persistence/SnapshotCache.cs
  tests/Neo.UnitTests/Persistence/UT_MemoryStore.cs
Labels: bug, waiting for review

#3291 [Neo Core Style] define a class for the contractbasemethod
  src/Neo/SmartContract/ApplicationEngine.cs
  src/Neo/SmartContract/ContractBasicMethod.cs
  src/Neo/SmartContract/DeployedContract.cs
  src/Neo/SmartContract/Helper.cs
  src/Neo/SmartContract/Native/ContractManagement.cs
  src/Neo/Wallets/Helper.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
Labels: waiting for review

#3294 [Neo Core Style] Rename parameters, update comments, fix code style
  src/Neo/SmartContract/Native/NativeContract.cs
Labels: waiting for review, ready to merge

#3292 Fixed up `main.yml`
  .github/workflows/main.yml
  src/Neo.CLI/Neo.CLI.csproj
  src/Neo.ConsoleService/Neo.ConsoleService.csproj
  src/Neo.Cryptography.BLS12_381/Neo.Cryptography.BLS12_381.csproj
  src/Neo.Extensions/Neo.Extensions.csproj
  src/Neo.GUI/Neo.GUI.csproj
  src/Neo.IO/Neo.IO.csproj
  src/Neo.Json/Neo.Json.csproj
  src/Neo.VM/Neo.VM.csproj
  src/Neo/Neo.csproj
  src/Plugins/ApplicationLogs/ApplicationLogs.csproj
  src/Plugins/DBFTPlugin/DBFTPlugin.csproj
  src/Plugins/Directory.Build.props
  src/Plugins/LevelDBStore/LevelDBStore.csproj
  src/Plugins/MPTTrie/MPTTrie.csproj
  src/Plugins/OracleService/OracleService.csproj
  src/Plugins/RocksDBStore/RocksDBStore.csproj
  src/Plugins/RpcClient/RpcClient.csproj
  src/Plugins/RpcServer/RpcServer.csproj
  src/Plugins/SQLiteWallet/SQLiteWallet.csproj
  src/Plugins/StateService/StateService.csproj
  src/Plugins/StorageDumper/StorageDumper.csproj
  src/Plugins/TokensTracker/TokensTracker.csproj
  tests/Directory.Build.props
Labels: waiting for review, ready to merge

#3299 [Neo Plugin Bug]fix 3296
  src/Plugins/ApplicationLogs/Store/LogStorageStore.cs
Labels: bug, critical, waiting for review, ready to merge

#3290 SmartContract: use executing contract state to check permissions
  src/Neo/Hardfork.cs
  src/Neo/SmartContract/ApplicationEngine.cs
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngine.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
  tests/Neo.UnitTests/SmartContract/UT_Syscalls.cs
Labels: bug, ready to merge, hardfork

#3301 [Neo Core Bug]fix 3300
  src/Neo/SmartContract/ApplicationEngine.Runtime.cs
  src/Neo/SmartContract/NotifyEventArgs.cs
  tests/Neo.UnitTests/SmartContract/UT_NotifyEventArgs.cs
Labels: bug, critical, waiting for review, ready to merge, hardfork

#3330 v3.7.5
  .github/workflows/main.yml
  benchmarks/Neo.Benchmarks/Neo.Benchmarks.csproj
  benchmarks/Neo.VM.Benchmarks/Neo.VM.Benchmarks.csproj
  src/Directory.Build.props
  src/Neo.CLI/config.fs.mainnet.json
  src/Neo.CLI/config.json
  src/Neo.CLI/config.mainnet.json
  src/Neo.CLI/config.testnet.json
  src/Neo/Hardfork.cs
  src/Neo/SmartContract/ApplicationEngine.Runtime.cs
  src/Neo/SmartContract/ApplicationEngine.cs
  src/Neo/SmartContract/NotifyEventArgs.cs
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngine.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
  tests/Neo.UnitTests/SmartContract/UT_NotifyEventArgs.cs
  tests/Neo.UnitTests/SmartContract/UT_Syscalls.cs
Labels: waiting for review, ready to merge

#3329 fix plugin download url
  src/Neo.CLI/Settings.cs
  src/Neo.CLI/config.fs.mainnet.json
  src/Neo.CLI/config.fs.testnet.json
  src/Neo.CLI/config.json
  src/Neo.CLI/config.mainnet.json
  src/Neo.CLI/config.testnet.json
  tests/Neo.Plugins.OracleService.Tests/config.json
Labels: waiting for review, ready to merge

#3314 [Neo CLI Optimization] fix exception message
  src/Neo.CLI/CLI/MainService.cs
Labels: waiting for review, ready to merge

#3318 Return expect to verify neo-cli
  .github/workflows/main.yml
  scripts/Neo.CLI/test-neo-cli.expect
Labels: waiting for review, ready to merge

#3295 [Neo CLI New Feature] Allow custom plugins
  src/Neo.CLI/CLI/MainService.Plugins.cs
  src/Neo.CLI/Settings.cs
  src/Neo.CLI/config.json
  src/Neo.CLI/config.json.md
Labels: waiting for review, ready to merge

#3306 Fixed `Path` and `Property` for `*.csproj` files
  src/Neo.CLI/Neo.CLI.csproj
  src/Neo.ConsoleService/Neo.ConsoleService.csproj
  src/Neo.Cryptography.BLS12_381/Neo.Cryptography.BLS12_381.csproj
  src/Neo.Extensions/Neo.Extensions.csproj
  src/Neo.GUI/Neo.GUI.csproj
  src/Neo.IO/Neo.IO.csproj
  src/Neo.Json/Neo.Json.csproj
  src/Neo.VM/Neo.VM.csproj
  src/Neo/Neo.csproj
  src/Plugins/ApplicationLogs/ApplicationLogs.csproj
  src/Plugins/DBFTPlugin/DBFTPlugin.csproj
  src/Plugins/LevelDBStore/LevelDBStore.csproj
  src/Plugins/MPTTrie/MPTTrie.csproj
  src/Plugins/OracleService/OracleService.csproj
  src/Plugins/RocksDBStore/RocksDBStore.csproj
  src/Plugins/RpcClient/RpcClient.csproj
  src/Plugins/RpcServer/RpcServer.csproj
  src/Plugins/SQLiteWallet/SQLiteWallet.csproj
  src/Plugins/StateService/StateService.csproj
  src/Plugins/StorageDumper/StorageDumper.csproj
  src/Plugins/TokensTracker/TokensTracker.csproj
Labels: bug, waiting for review, ready to merge

#3309 [Neo Core] Part 1. Isolate Plugins Exceptions from the Node.
  src/Neo/Ledger/Blockchain.cs
  src/Neo/Plugins/Plugin.cs
  tests/Neo.UnitTests/Plugins/TestPlugin.cs
  tests/Neo.UnitTests/Plugins/UT_Plugin.cs
Labels: waiting for review, ready to merge

#3342 sync v3.7.5
  src/Neo.CLI/config.fs.mainnet.json
  src/Neo.CLI/config.json
  src/Neo.CLI/config.mainnet.json
  src/Neo.CLI/config.testnet.json
Labels: ready to merge

#3341 [Neo Plugin Optimization] Catch format exception
  src/Plugins/RpcServer/RpcServer.Blockchain.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
Labels: waiting for review, ready to merge

#3332 [Neo Core Optimization] Organize core events.
  src/Neo.CLI/CLI/MainService.Logger.cs
  src/Neo/IEventHandlers/ICommittedHandler.cs
  src/Neo/IEventHandlers/ICommittingHandler.cs
  src/Neo/IEventHandlers/ILogHandler.cs
  src/Neo/IEventHandlers/ILoggingHandler.cs
  src/Neo/IEventHandlers/IMessageReceivedHandler.cs
  src/Neo/IEventHandlers/INotifyHandler.cs
  src/Neo/IEventHandlers/IServiceAddedHandler.cs
  src/Neo/IEventHandlers/ITransactionAddedHandler.cs
  src/Neo/IEventHandlers/ITransactionRemovedHandler.cs
  src/Neo/IEventHandlers/IWalletChangedHandler.cs
  src/Neo/IEventHandlers/handlers.md
  src/Plugins/ApplicationLogs/LogReader.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/StateService/StatePlugin.cs
  src/Plugins/StorageDumper/StorageDumper.cs
  src/Plugins/TokensTracker/TokensTracker.cs
Labels: waiting for review, ready to merge

#3326 [Neo VM Optimization]Print stack exception
  src/Neo.VM/ExecutionEngine.cs
Labels: waiting for review, ready to merge

#3307 Fixed `version` display in `neo-cli`
  src/Neo.CLI/CLI/MainService.cs
  src/Neo/Network/P2P/LocalNode.cs
Labels: waiting for review, ready to merge

#3320 Fixed Props paths for `*.csproj` builds
  src/Directory.Build.props
  src/Plugins/Directory.Build.props
Labels: waiting for review, ready to merge

#3311 [Neo Plugin New feature] UnhandledExceptionPolicy on Plugin Unhandled Exception
  src/Neo/Ledger/Blockchain.cs
  src/Neo/Plugins/Plugin.cs
  src/Neo/Plugins/PluginSettings.cs
  src/Neo/Plugins/UnhandledExceptionPolicy.cs
  src/Plugins/ApplicationLogs/ApplicationLogs.json
  src/Plugins/ApplicationLogs/LogReader.cs
  src/Plugins/ApplicationLogs/Settings.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.json
  src/Plugins/DBFTPlugin/Settings.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/OracleService/OracleService.json
  src/Plugins/OracleService/Settings.cs
  src/Plugins/RpcServer/RpcServer.json
  src/Plugins/RpcServer/RpcServerPlugin.cs
  src/Plugins/RpcServer/Settings.cs
  src/Plugins/StateService/Settings.cs
  src/Plugins/StateService/StatePlugin.cs
  src/Plugins/StateService/StateService.json
  src/Plugins/StorageDumper/Settings.cs
  src/Plugins/StorageDumper/StorageDumper.cs
  src/Plugins/StorageDumper/StorageDumper.json
  src/Plugins/TokensTracker/TokensTracker.cs
  src/Plugins/TokensTracker/TokensTracker.json
  tests/Neo.UnitTests/Plugins/TestPlugin.cs
  tests/Neo.UnitTests/Plugins/UT_Plugin.cs
Labels: blocked, ready to merge, wait technical committee

#3338 [**Fixed**] `NuGet` Release
  .github/workflows/main.yml
  .github/workflows/nuget.yml
  benchmarks/Directory.Build.props
  benchmarks/Neo.Benchmarks/Neo.Benchmarks.csproj
  benchmarks/Neo.VM.Benchmarks/Neo.VM.Benchmarks.csproj
  src/Directory.Build.props
  src/Neo.CLI/Neo.CLI.csproj
  src/Neo.GUI/Neo.GUI.csproj
Labels: waiting for review, ready to merge

#3336 [Neo Core UT] Test memory store
  tests/Neo.UnitTests/Persistence/TestMemoryStoreProvider.cs
  tests/Neo.UnitTests/Persistence/UT_MemoryStore.cs
Labels: waiting for review, ready to merge

#3348 [**Fixed**] `ApplicationLogs` Console Printing
  src/Plugins/ApplicationLogs/LogReader.cs
Labels: ready to merge

#3349 Plugin unhandled exception
  src/Neo/Ledger/Blockchain.cs
  src/Neo/Plugins/Plugin.cs
  src/Neo/Plugins/PluginSettings.cs
  src/Neo/Plugins/UnhandledExceptionPolicy.cs
  src/Plugins/ApplicationLogs/ApplicationLogs.json
  src/Plugins/ApplicationLogs/LogReader.cs
  src/Plugins/ApplicationLogs/Settings.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.json
  src/Plugins/DBFTPlugin/Settings.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/OracleService/OracleService.json
  src/Plugins/OracleService/Settings.cs
  src/Plugins/RpcServer/RpcServer.json
  src/Plugins/RpcServer/RpcServerPlugin.cs
  src/Plugins/RpcServer/Settings.cs
  src/Plugins/StateService/Settings.cs
  src/Plugins/StateService/StatePlugin.cs
  src/Plugins/StateService/StateService.json
  src/Plugins/StorageDumper/Settings.cs
  src/Plugins/StorageDumper/StorageDumper.cs
  src/Plugins/StorageDumper/StorageDumper.json
  src/Plugins/TokensTracker/TokensTracker.cs
  src/Plugins/TokensTracker/TokensTracker.json
  tests/Neo.UnitTests/Plugins/TestPlugin.cs
  tests/Neo.UnitTests/Plugins/UT_Plugin.cs
Labels: waiting for review, ready to merge

#3352 Revert "Fixed Props paths for `*.csproj` builds"
  src/Directory.Build.props
  src/Plugins/Directory.Build.props
Labels: waiting for review, ready to merge

#3331 [Neo VM Style] Add comments and document to reference counter
  src/Neo.VM/ReferenceCounter.cs
  src/Neo.VM/ReferenceCounter.md
  src/Neo.VM/Types/StackItem.Vertex.cs
Labels: waiting for review, ready to merge

#3358 [Neo CLI FIX] fix https://github.com/neo-project/neo/issues/3357
  src/Directory.Build.props
Labels: ready to merge

#3339 [Neo Plugins UT] Add RpcServer Unit Tests Part Blockchain.
  src/Neo/SmartContract/Native/NeoToken.cs
  src/Plugins/RpcServer/RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/MockNeoSystem.cs
  tests/Neo.Plugins.RpcServer.Tests/Neo.Plugins.RpcServer.Tests.csproj
  tests/Neo.Plugins.RpcServer.Tests/TestMemoryStoreProvider.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.cs
  tests/Neo.UnitTests/Ledger/UT_Blockchain.cs
  tests/Neo.UnitTests/Ledger/UT_TrimmedBlock.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Header.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
  tests/Neo.UnitTests/SmartContract/UT_SmartContractHelper.cs
  tests/Neo.UnitTests/SmartContract/UT_Syscalls.cs
  tests/Neo.UnitTests/TestUtils.Block.cs
  tests/Neo.UnitTests/TestUtils.cs
Labels: waiting for review, ready to merge
