Repository neo-project/neo, pull requests merged in 2024-10, with the labels that each got.

#3494 Added `CreateStruct` & Fixed `CreateMap`
  src/Neo/VM/Helper.cs
  tests/Neo.UnitTests/VM/UT_Helper.cs
Labels: ready to merge

#3508 fix: sensitive data compare should use constant time compare to avoid timing attack
  src/Plugins/RpcServer/RpcServer.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.cs
Labels: waiting for review, ready to merge

#3516 Use `CryptographicOperations.FixedTimeEquals`
  src/Neo.Cryptography.BLS12_381/ConstantTimeUtility.cs
Labels: ready to merge

#3512 [Benchmark] this pr adds more pocs to benchmark
  benchmarks/Neo.VM.Benchmarks/Benchmarks.POC.cs
Labels: waiting for review, NGD Review

#3522 Circular reference error info in ToJson
  src/Neo/VM/Helper.cs
Labels: ready to merge

#3514 [Benchmark] Benchmark OpCode and VM
  benchmarks/Neo.VM.Benchmarks/InstructionBuilder/Helper.cs
  benchmarks/Neo.VM.Benchmarks/InstructionBuilder/Instruction.cs
  benchmarks/Neo.VM.Benchmarks/InstructionBuilder/InstructionBuilder.cs
  benchmarks/Neo.VM.Benchmarks/InstructionBuilder/JumpTarget.cs
  benchmarks/Neo.VM.Benchmarks/Neo.VM.Benchmarks.csproj
  benchmarks/Neo.VM.Benchmarks/OpCode/Arrays/OpCode.ReverseN.cs
  benchmarks/Neo.VM.Benchmarks/OpCode/Benchmark.Opcode.cs
  benchmarks/Neo.VM.Benchmarks/OpCode/BenchmarkEngine.cs
  benchmarks/Neo.VM.Benchmarks/OpCode/BenchmarkMode.cs
  benchmarks/Neo.VM.Benchmarks/OpCode/OpCodeBase.cs
  benchmarks/Neo.VM.Benchmarks/Program.cs
  benchmarks/Neo.VM.Benchmarks/VMTypes/Benchmarks_Convert.cs
  src/Neo.VM/OpCode.cs
  tests/Neo.VM.Tests/Types/TestEngine.cs
Labels: waiting for review, NGD Review

#3525 [Neo VM] optimize newstruct
  src/Neo.VM/JumpTable/JumpTable.Compound.cs
Labels: waiting for review, ready to merge

#3533 Add canonical `TryGet` style in `IReadOnlyStore`
  src/Neo/Persistence/IReadOnlyStore.cs
  src/Neo/Persistence/MemorySnapshot.cs
  src/Neo/Persistence/MemoryStore.cs
  src/Plugins/LevelDBStore/Plugins/Storage/Snapshot.cs
  src/Plugins/LevelDBStore/Plugins/Storage/Store.cs
  src/Plugins/RocksDBStore/Plugins/Storage/Snapshot.cs
  src/Plugins/RocksDBStore/Plugins/Storage/Store.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Trie.cs
  tests/Neo.Plugins.Storage.Tests/StoreTest.cs
  tests/Neo.UnitTests/Persistence/UT_MemorySnapshot.cs
  tests/Neo.UnitTests/Persistence/UT_MemoryStore.cs
Labels: ready to merge

#3529 Change references to IReferenceCounter
  benchmarks/Neo.VM.Benchmarks/TestArray.cs
  benchmarks/Neo.VM.Benchmarks/TestStruct.cs
  src/Neo.VM/ExecutionEngine.cs
  src/Neo.VM/Types/Array.cs
  src/Neo.VM/Types/Struct.cs
Labels: waiting for review

#3527 fix: concurrency conflict in NEP6Wallet.ToJson
  src/Neo/Wallets/NEP6/NEP6Wallet.cs
Labels: ready to merge

#3545 Expose `GetInteropDescriptor`
  src/Neo/SmartContract/ApplicationEngine.cs
Labels: waiting for review

#3557 OpCodes: extend MODPOW tests with negative base/exp/mod
  tests/Neo.VM.Tests/Tests/OpCodes/Arithmetic/MODPOW.json
Labels: ready to merge

#3558 Fix InvalidOperationException
  src/Neo/SmartContract/ContractParameter.cs
  src/Neo/VM/Helper.cs
  tests/Neo.UnitTests/VM/UT_Helper.cs
Labels: ready to merge
