Repository neo-project/neo, pull requests merged in 2024-11, with the labels that each got.

#3531 Fixed hashcode for StackItem [Remove Murmur32 and add XxHash3]
  src/Neo.VM/Cryptography/Murmur32.cs
  src/Neo.VM/JumpTable/JumpTable.Compound.cs
  src/Neo.VM/JumpTable/JumpTable.Splice.cs
  src/Neo.VM/Neo.VM.csproj
  src/Neo.VM/Script.cs
  src/Neo.VM/Types/Buffer.cs
  src/Neo.VM/Types/ByteString.cs
  src/Neo.VM/Types/Pointer.cs
  src/Neo.VM/Types/PrimitiveType.cs
  src/Neo.VM/Types/StackItem.Vertex.cs
  src/Neo.VM/Unsafe.cs
  tests/Neo.VM.Tests/UT_StackItem.cs
Labels: bug, ready to merge

#3385 Extend `CalculateNetworkFee` with contract verification
  src/Neo/Wallets/Helper.cs
Labels: waiting for review, ready to merge

#3487 support file path to base64 in parse
  src/Neo.CLI/CLI/MainService.Tools.cs
Labels: waiting for review

#3563 A simpler and better performance impl for `ByteArrayComparer`
  benchmarks/Neo.Extensions.Benchmarks/Benchmark.ByteArrayComparer.cs
  benchmarks/Neo.Extensions.Benchmarks/Neo.Extensions.Benchmarks.csproj
  benchmarks/Neo.Extensions.Benchmarks/OldByteArrayComparer.cs
  benchmarks/Neo.Extensions.Benchmarks/Program.cs
  neo.sln
  src/Neo.Extensions/ByteArrayComparer.cs
  src/Neo/Persistence/DataCache.cs
  src/Neo/Persistence/MemorySnapshot.cs
  src/Neo/Persistence/MemoryStore.cs
  tests/Neo.Extensions.Tests/UT_ByteArrayComparer.cs
Labels: blocker, waiting for review

#3559 use `Xxhash3` for StorageKey.GetHashCode
  .gitignore
  benchmarks/Neo.Benchmarks/Benchmarks.Hash.cs
  benchmarks/Neo.Benchmarks/Neo.Benchmarks.csproj
  benchmarks/Neo.Benchmarks/Program.cs
  src/Neo.VM/Unsafe.cs
  src/Neo/Cryptography/Helper.cs
  src/Neo/Neo.csproj
  src/Neo/SmartContract/StorageKey.cs
  tests/Neo.UnitTests/Cryptography/UT_Cryptography_Helper.cs
  tests/Neo.UnitTests/Ledger/UT_StorageKey.cs
Labels: ready to merge

#3549 [`Fix`] StackItem.GetHashCode for CompoundType
  src/Neo.VM/Types/CompoundType.cs
  tests/Neo.VM.Tests/UT_StackItem.cs
Labels: blocker, ready to merge

#3492 `[Fix]` unalignment memory load in Neo.VM Unsafe.NotZero(ReadOnlySpan<byte>) and remove the use of `unsafe`
  .gitignore
  src/Neo.VM/Types/ByteString.cs
  src/Neo.VM/Unsafe.cs
  tests/Neo.VM.Tests/UT_Unsafe.cs
Labels: ready to merge

#3568 [Fix] Enable Storage tests for (MacOS)
  .github/workflows/main.yml
Labels: waiting for review, ready to merge, Tested, GitHub Workflow

#3566 Optimize the ` ToHexString`
  src/Neo.Cryptography.BLS12_381/Neo.Cryptography.BLS12_381.csproj
  src/Neo.Cryptography.BLS12_381/Scalar.cs
  src/Neo.Extensions/ByteExtensions.cs
Labels: ready to merge

#3562 A simpler impl for `ByteArrayEqualityComparer` and remove redundant impl
  src/Neo.Extensions/ByteArrayEqualityComparer.cs
  src/Neo.Extensions/ByteExtensions.cs
  src/Neo.Extensions/Neo.Extensions.csproj
  src/Neo.IO/ByteArrayEqualityComparer.cs
  src/Neo/Cryptography/Helper.cs
  src/Neo/IO/Caching/ECPointCache.cs
  src/Neo/Neo.csproj
  src/Neo/SmartContract/StorageKey.cs
  src/Plugins/MPTTrie/Cryptography/MPTTrie/Trie.Proof.cs
  src/Plugins/MPTTrie/IO/ByteArrayEqualityComparer.cs
  tests/Neo.Extensions.Tests/UT_ByteArrayEqualityComparer.cs
  tests/Neo.Extensions.Tests/UT_ByteExtensions.cs
  tests/Neo.UnitTests/Cryptography/UT_Cryptography_Helper.cs
  tests/Neo.UnitTests/Ledger/UT_StorageKey.cs
Labels: Ready to Merge

#3573 [Add] `IEquatable` to WitnessRule
  src/Neo/Network/P2P/Payloads/WitnessRule.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_WitnessRule.cs
Labels: Blocker, Waiting for Review

#3579 Make exception message more clear in `Neo.Json`
  src/Neo.Json/JNumber.cs
  src/Neo.Json/JPathToken.cs
  src/Neo.Json/JToken.cs
Labels: Waiting for Review

#3578 use `MemoryExtenions.SequenceEqual` for better performance
  src/Neo.Cryptography.BLS12_381/Fp.cs
  src/Neo.Extensions/ByteArrayEqualityComparer.cs
Labels: Ready to Merge

#3575 [Plugin LevelDB] First step of 3414 - Comments and style
  src/Plugins/LevelDBStore/IO/Data/LevelDB/DB.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Iterator.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Options.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/ReadOptions.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Snapshot.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/WriteBatch.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/WriteOptions.cs
  src/Plugins/LevelDBStore/Plugins/Storage/Snapshot.cs
  src/Plugins/LevelDBStore/Plugins/Storage/Store.cs
Labels: Ready to Merge

#3577 [Core VM] update exception message in the vm to make it more clear.
  src/Neo.VM/EvaluationStack.cs
  src/Neo.VM/ExecutionEngine.cs
  src/Neo.VM/ExecutionEngineLimits.cs
  src/Neo.VM/JumpTable/JumpTable.Compound.cs
  src/Neo.VM/JumpTable/JumpTable.Slot.cs
  src/Neo.VM/JumpTable/JumpTable.Splice.cs
  src/Neo.VM/Types/Array.cs
  src/Neo.VM/Types/ByteString.cs
  src/Neo.VM/Types/Integer.cs
  src/Neo.VM/Types/InteropInterface.cs
  src/Neo.VM/Types/Map.cs
  src/Neo.VM/Types/Null.cs
  src/Neo.VM/Types/Struct.cs
  src/Neo.VM/Utility.cs
Labels: Ready to Merge

#3585 Add more info to deserialization exceptions
  src/Neo/Network/P2P/Message.cs
  src/Neo/Network/P2P/Payloads/ExtensiblePayload.cs
  src/Neo/Network/P2P/Payloads/GetBlockByIndexPayload.cs
  src/Neo/Network/P2P/Payloads/GetBlocksPayload.cs
  src/Neo/Network/P2P/Payloads/OracleResponse.cs
  src/Neo/Network/P2P/Payloads/Transaction.cs
  src/Neo/Network/P2P/Payloads/TransactionAttribute.cs
  src/Neo/Network/P2P/Payloads/WitnessRule.cs
Labels: Ready to Merge

#3584 Remove some ToArrays to reduce memory allocations
  src/Neo.Extensions/Collections/CollectionExtensions.cs
  src/Neo/Network/P2P/Payloads/InvPayload.cs
  src/Neo/Network/P2P/RemoteNode.ProtocolHandler.cs
  src/Neo/Network/P2P/TaskManager.cs
  tests/Neo.Extensions.Tests/Collections/UT_CollectionExtensions.cs
Labels: Ready to Merge

#3571 [Add] `IEquatable` to Signer
  src/Neo/Network/P2P/Payloads/Signer.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Signers.cs
Labels: Waiting for Review, Ready to Merge

#3588 Optimize Signer equals
  src/Neo/Network/P2P/Payloads/Signer.cs
Labels: Ready to Merge

#3587 Lower Timeout for the Akka System
  src/Neo/NeoSystem.cs
Labels: Waiting for Review, Ready to Merge

#3590 [Core VM] optmize the vm
  src/Neo.VM/Script.cs
Labels: Waiting for Review

#3592 vm: Add some `AggressiveInlining`
  src/Neo.VM/Types/Array.cs
  src/Neo.VM/Types/Boolean.cs
  src/Neo.VM/Types/ByteString.cs
  src/Neo.VM/Types/Integer.cs
  src/Neo.VM/Types/Map.cs
  src/Neo.VM/Types/Null.cs
Labels: Waiting for Review

#3598 Optimizations for `KeyBuilder`
  benchmarks/Neo.Benchmarks/Program.cs
  benchmarks/Neo.Benchmarks/SmartContract/Benchmarks.StorageKey.cs
  src/Neo/SmartContract/KeyBuilder.cs
  src/Neo/UInt160.cs
  src/Neo/UInt256.cs
  tests/Neo.UnitTests/SmartContract/UT_KeyBuilder.cs
  tests/Neo.UnitTests/UT_UInt160.cs
  tests/Neo.UnitTests/UT_UInt256.cs
Labels: Ready to Merge

#3601 Update README.md
  README.md
Labels: Ready to Merge

#3576 .NET 9
  .devcontainer/devcontainer.dockerfile
  .github/workflows/docker.yml
  .github/workflows/main.yml
  .github/workflows/nuget.yml
  .github/workflows/release.yml
  benchmarks/Neo.Benchmarks/Neo.Benchmarks.csproj
  benchmarks/Neo.Extensions.Benchmarks/Neo.Extensions.Benchmarks.csproj
  benchmarks/Neo.VM.Benchmarks/Neo.VM.Benchmarks.csproj
  global.json
  scripts/Neo.CLI/test-neo-cli.exp
  src/Neo.CLI/CLI/MainService.cs
  src/Neo.CLI/Dockerfile
  src/Neo.CLI/Neo.CLI.csproj
  src/Neo.ConsoleService/Neo.ConsoleService.csproj
  src/Neo.Cryptography.BLS12_381/Neo.Cryptography.BLS12_381.csproj
  src/Neo.Extensions/Neo.Extensions.csproj
  src/Neo.GUI/GUI/ChangePasswordDialog.cs
  src/Neo.GUI/GUI/CreateWalletDialog.cs
  src/Neo.GUI/GUI/ImportPrivateKeyDialog.cs
  src/Neo.GUI/GUI/OpenWalletDialog.cs
  src/Neo.GUI/GUI/TxOutListBox.cs
  src/Neo.GUI/Neo.GUI.csproj
  src/Neo.IO/Neo.IO.csproj
  src/Neo.Json/Neo.Json.csproj
  src/Neo.VM/Neo.VM.csproj
  src/Neo.VM/ScriptBuilder.cs
  src/Neo.VM/Types/Map.cs
  src/Neo/Neo.csproj
  src/Plugins/ApplicationLogs/ApplicationLogs.csproj
  src/Plugins/DBFTPlugin/DBFTPlugin.csproj
  src/Plugins/LevelDBStore/LevelDBStore.csproj
  src/Plugins/MPTTrie/MPTTrie.csproj
  src/Plugins/OracleService/OracleService.csproj
  src/Plugins/RocksDBStore/RocksDBStore.csproj
  src/Plugins/RpcClient/RpcClient.csproj
  src/Plugins/RpcServer/RpcServer.csproj
  src/Plugins/SQLiteWallet/SQLiteWallet.csproj
  src/Plugins/StateService/StateService.csproj
  src/Plugins/StorageDumper/StorageDumper.csproj
  src/Plugins/TokensTracker/Extensions.cs
  src/Plugins/TokensTracker/TokensTracker.csproj
  tests/Directory.Build.props
  tests/Neo.ConsoleService.Tests/Neo.ConsoleService.Tests.csproj
  tests/Neo.Cryptography.BLS12_381.Tests/Neo.Cryptography.BLS12_381.Tests.csproj
  tests/Neo.Cryptography.MPTTrie.Tests/Neo.Cryptography.MPTTrie.Tests.csproj
  tests/Neo.Extensions.Tests/Neo.Extensions.Tests.csproj
  tests/Neo.Extensions.Tests/UT_ByteExtensions.cs
  tests/Neo.Json.UnitTests/Neo.Json.UnitTests.csproj
  tests/Neo.Network.RPC.Tests/Neo.Network.RPC.Tests.csproj
  tests/Neo.Plugins.ApplicationLogs.Tests/Neo.Plugins.ApplicationLogs.Tests.csproj
  tests/Neo.Plugins.OracleService.Tests/Neo.Plugins.OracleService.Tests.csproj
  tests/Neo.Plugins.RpcServer.Tests/Neo.Plugins.RpcServer.Tests.csproj
  tests/Neo.Plugins.Storage.Tests/Neo.Plugins.Storage.Tests.csproj
  tests/Neo.UnitTests/Neo.UnitTests.csproj
  tests/Neo.UnitTests/UT_Helper.cs
  tests/Neo.VM.Tests/Neo.VM.Tests.csproj
  tests/Neo.VM.Tests/UT_ScriptBuilder.cs
  tests/Neo.VM.Tests/UT_Utility.cs
Labels: Ready to Merge

#3593 Added better error handling to `Native.Ledger`
  src/Neo/SmartContract/Native/LedgerContract.cs
Labels: Need Update, Ready to Merge

#3446 `[Move]` Part-7 Classes into Different Library - `Neo.Extensions`
  src/Neo.GUI/GUI/ElectionDialog.cs
  src/Neo.GUI/GUI/VotingDialog.cs
  src/Neo/Extensions/Collections/ICollectionExtensions.cs
  src/Neo/Extensions/VM/ScriptBuilderExtensions.cs
  src/Neo/SmartContract/ContractParametersContext.cs
  src/Neo/SmartContract/Helper.cs
  src/Neo/VM/Helper.cs
  src/Neo/Wallets/AssetDescriptor.cs
  src/Plugins/RpcClient/ContractClient.cs
  tests/Neo.Plugins.OracleService.Tests/E2E_Https.cs
  tests/Neo.Plugins.OracleService.Tests/TestBlockchain.cs
  tests/Neo.UnitTests/Extensions/Nep17NativeContractExtensions.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngine.Contract.cs
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngine.cs
  tests/Neo.UnitTests/SmartContract/UT_Contract.cs
  tests/Neo.UnitTests/VM/UT_Helper.cs
Labels: Ready to Merge

#3591 [Core Plugin] adopt more change from pr 3414
  src/Plugins/LevelDBStore/IO/Data/LevelDB/DB.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Helper.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Iterator.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/LevelDBException.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/LevelDBHandle.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Native.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Options.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/ReadOptions.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Snapshot.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/WriteBatch.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/WriteOptions.cs
  src/Plugins/LevelDBStore/Plugins/Storage/LevelDBStore.cs
  src/Plugins/LevelDBStore/Plugins/Storage/Snapshot.cs
  src/Plugins/LevelDBStore/Plugins/Storage/Store.cs
Labels: Waiting for Review, Ready to Merge

#3603 Revert "[Remove] obsolete `WsServer`"
  src/Neo/Network/P2P/Capabilities/NodeCapability.cs
  src/Neo/Network/P2P/Capabilities/NodeCapabilityType.cs
  src/Neo/Network/P2P/Capabilities/ServerCapability.cs
  tests/Neo.UnitTests/Network/P2P/Capabilities/UT_ServerCapability.cs
Labels: Critical, Waiting for Review

#3605 Add argument null check for `ToHexString` to keep same behavior between different .net versions
  src/Neo.Extensions/ByteExtensions.cs
  tests/Neo.Extensions.Tests/UT_ByteExtensions.cs
Labels: Waiting for Review
