Repository neo-project/neo, pull requests merged in 2024-02, with the labels that each got.

#3113 Fix ut
  benchmarks/Neo.Benchmarks/Benchmarks.cs
  src/Neo.CLI/CLI/MainService.cs
  src/Neo/NeoSystem.cs
  src/Neo/Persistence/MemoryStore.cs
  src/Neo/Persistence/StoreFactory.cs
  tests/Neo.UnitTests/Ledger/UT_Blockchain.cs
  tests/Neo.UnitTests/Ledger/UT_MemoryPool.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Transaction.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_RoleManagement.cs
  tests/Neo.UnitTests/TestBlockchain.cs
  tests/Neo.UnitTests/Wallets/UT_Wallet.cs
Labels: waiting for review

#3082 Neo as dotnet standard
  src/Neo.VM/Utility.cs
  src/Neo/BigDecimal.cs
  src/Neo/Cryptography/ECC/ECCurve.cs
  src/Neo/Cryptography/ECC/ECFieldElement.cs
  src/Neo/Cryptography/ECC/ECPoint.cs
  src/Neo/Cryptography/Helper.cs
  src/Neo/Cryptography/Murmur128.cs
  src/Neo/Cryptography/Murmur32.cs
  src/Neo/IO/Helper.cs
  src/Neo/Neo.csproj
  src/Neo/Network/UPnP.cs
  src/Neo/SmartContract/ContractTask.cs
  src/Neo/SmartContract/ContractTaskMethodBuilder.cs
  src/Neo/SmartContract/Manifest/ContractMethodDescriptor.cs
  src/Neo/SmartContract/Manifest/ContractParameterDefinition.cs
  src/Neo/SmartContract/StorageKey.cs
  tests/Neo.VM.Tests/UtUtility.cs
Labels: waiting for review

#3115 [VM UT] update UT name
  tests/Neo.VM.Tests/UT_Debugger.cs
  tests/Neo.VM.Tests/UT_EvaluationStack.cs
  tests/Neo.VM.Tests/UT_ExecutionContext.cs
  tests/Neo.VM.Tests/UT_ReferenceCounter.cs
  tests/Neo.VM.Tests/UT_Script.cs
  tests/Neo.VM.Tests/UT_ScriptBuilder.cs
  tests/Neo.VM.Tests/UT_Slot.cs
  tests/Neo.VM.Tests/UT_StackItem.cs
  tests/Neo.VM.Tests/UT_Struct.cs
  tests/Neo.VM.Tests/UT_Unsafe.cs
  tests/Neo.VM.Tests/UT_Utility.cs
  tests/Neo.VM.Tests/UT_VMJson.cs
Labels: ready to merge

#3107 VM: avoid checking reference when the stack is not full.
  src/Neo.VM/ExecutionEngine.cs
  tests/Neo.VM.Tests/UT_ReferenceCounter.cs
Labels: waiting for review

#3124 [Neo Fix] fix the store crash issue
  src/Neo.CLI/CLI/MainService.cs
  src/Neo/NeoSystem.cs
  src/Neo/Persistence/StoreFactory.cs
Labels: ready to merge

#3130 Fix storage encoding
  src/Neo/SmartContract/KeyBuilder.cs
  tests/Neo.UnitTests/SmartContract/UT_KeyBuilder.cs
Labels: bug, critical, waiting for review

#3134 Allow access TestingEngine to internal
  src/Neo/Neo.csproj
Labels: blocker

#3072 Added `publish` to `github packages`
  .github/workflows/main.yml
  .github/workflows/pkgs-delete.yml
  NuGet.Config
Labels: critical, waiting for review

#3131 Optimize opcode price charging
  src/Neo/SmartContract/ApplicationEngine.OpCodePrices.cs
  src/Neo/SmartContract/ApplicationEngine.cs
  src/Neo/SmartContract/Helper.cs
  tests/Neo.UnitTests/SmartContract/UT_Contract.cs
  tests/Neo.UnitTests/SmartContract/UT_OpCodePrices.cs
Labels: waiting for review

#3141 [Core Fix] add loadstore back
  src/Neo/NeoSystem.cs
Labels: blocker, waiting for review

#3143 Update InteropInterface
  src/Neo.VM/Neo.VM.csproj
  src/Neo.VM/Types/InteropInterface.cs
Labels: blocker

#3148 Fix: Screen Rendering on Invalid Arguments
  src/Neo.CLI/CLI/MainService.cs
  src/Neo.ConsoleService/ConsoleServiceBase.cs
Labels: waiting for review

#3147 Decouple calculate fee from Wallet
  src/Neo/Wallets/Helper.cs
  src/Neo/Wallets/Wallet.cs
Labels: waiting for review

#2942 Allow Native Contracts to be updated
  src/Neo/Hardfork.cs
  src/Neo/NeoSystem.cs
  src/Neo/Persistence/DataCache.cs
  src/Neo/ProtocolSettings.cs
  src/Neo/SmartContract/ApplicationEngine.cs
  src/Neo/SmartContract/Native/ContractEventAttribute.cs
  src/Neo/SmartContract/Native/ContractManagement.cs
  src/Neo/SmartContract/Native/ContractMethodAttribute.cs
  src/Neo/SmartContract/Native/ContractMethodMetadata.cs
  src/Neo/SmartContract/Native/CryptoLib.cs
  src/Neo/SmartContract/Native/FungibleToken.cs
  src/Neo/SmartContract/Native/GasToken.cs
  src/Neo/SmartContract/Native/LedgerContract.cs
  src/Neo/SmartContract/Native/NativeContract.cs
  src/Neo/SmartContract/Native/NeoToken.cs
  src/Neo/SmartContract/Native/OracleContract.cs
  src/Neo/SmartContract/Native/PolicyContract.cs
  src/Neo/SmartContract/Native/RoleManagement.cs
  src/Neo/SmartContract/Native/StdLib.cs
  src/Neo/SmartContract/StorageItem.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_ContractEventAttribute.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_ContractMethodAttribute.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_CryptoLib.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
  tests/Neo.UnitTests/SmartContract/UT_JsonSerializer.cs
  tests/Neo.UnitTests/UT_ProtocolSettings.cs
Labels: critical, blocker, waiting for review

#3161 Expose GetContractState
  src/Neo/Neo.csproj
  src/Neo/Persistence/MemoryStoreProvider.cs
  src/Neo/SmartContract/Native/NativeContract.cs
Labels: blocker, waiting for review
