Repository neo-project/neo, pull requests merged in 2024-07, with the labels that each got.

#3359 Remove comments in `nuget.yml`
  .github/workflows/nuget.yml
Labels: waiting for review, ready to merge, GitHub Workflow

#3367 Fix: `MemPool` null checks
  src/Neo/Ledger/MemoryPool.cs
Labels: ready to merge

#3393 plugins: remove expressions that are always true
  src/Plugins/ApplicationLogs/LogReader.cs
  src/Plugins/OracleService/OracleService.cs
Labels: ready to merge

#3308 [**Part-1] Add `github` Release Workflow
  .github/workflows/release.yml
Labels: ready to merge, Tested, GitHub Workflow

#3384 `[Tests]` Add blame logging - `main.yml`
  .github/workflows/main.yml
Labels: ready to merge, GitHub Workflow

#3395 Fix download tips
  src/Neo.CLI/CLI/MainService.Plugins.cs
Labels: ready to merge

#3362 `DeprecatedIn` for events
  src/Neo/SmartContract/Native/ContractEventAttribute.cs
  src/Neo/SmartContract/Native/ContractMethodAttribute.cs
  src/Neo/SmartContract/Native/ContractMethodMetadata.cs
  src/Neo/SmartContract/Native/IHardforkActivable.cs
  src/Neo/SmartContract/Native/NativeContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
Labels: blocker, ready to merge

#3396 Fix crash when comparing ContractPermissionDescriptor
  src/Neo/SmartContract/Manifest/ContractPermissionDescriptor.cs
  tests/Neo.UnitTests/SmartContract/Manifest/UT_ContractPermissionDescriptor.cs
Labels: ready to merge

#3380 `[neo-cli]` Error Message and Warning - LevelDb
  src/Neo.CLI/CLI/MainService.cs
Labels: bug, ready to merge

#3379 `[Fixes]` Props Duplicate - Path Packing
  src/Plugins/Directory.Build.props
Labels: ready to merge

#3387 `[Move]` Part-1 Classes into Different Library - `Neo.IO`
  src/Neo.IO/Caching/Cache.cs
  src/Neo.IO/Caching/FIFOCache.cs
  src/Neo.IO/Caching/HashSetCache.cs
  src/Neo.IO/Caching/IndexedQueue.cs
  src/Neo.IO/Caching/KeyedCollectionSlim.cs
  src/Neo/Cryptography/Crypto.cs
  src/Neo/IO/Caching/ECDsaCache.cs
  src/Neo/Network/P2P/RemoteNode.ProtocolHandler.cs
Labels: ready to merge

#3398 `[Fix]` Test Problems
  .github/workflows/main.yml
Labels: ready to merge, GitHub Workflow

#3383 `[Typo]` Unit Tests - UT_ProtocolSettings.CreateHKSettings
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/UT_ProtocolSettings.cs
Labels: ready to merge

#3399 [Neo Plugin Store] Unit test
  tests/Neo.Plugins.Storage.Tests/StoreTest.cs
Labels: ready to merge

#3407 `[Add]` Debug Output to `Expect`
  .github/workflows/main.yml
  scripts/Neo.CLI/test-neo-cli.exp
Labels: ready to merge, GitHub Workflow, Minor Change

#3354 Improve code coverage
  src/Neo/SmartContract/Manifest/ContractAbi.cs
  src/Neo/SmartContract/Manifest/ContractManifest.cs
  tests/Neo.Json.UnitTests/UT_JArray.cs
  tests/Neo.Json.UnitTests/UT_JBoolean.cs
  tests/Neo.Json.UnitTests/UT_JNumber.cs
  tests/Neo.Json.UnitTests/UT_JString.cs
  tests/Neo.UnitTests/Cryptography/UT_BloomFilter.cs
  tests/Neo.UnitTests/Cryptography/UT_Cryptography_Helper.cs
  tests/Neo.UnitTests/Neo.UnitTests.csproj
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Block.cs
  tests/Neo.UnitTests/SmartContract/Manifest/TestFile/SampleContractCall.manifest.json
  tests/Neo.UnitTests/SmartContract/Manifest/TestFile/SampleEvent.manifest.json
  tests/Neo.UnitTests/SmartContract/Manifest/TestFile/SampleException.manifest.json
  tests/Neo.UnitTests/SmartContract/Manifest/TestFile/SampleHelloWorld.manifest.json
  tests/Neo.UnitTests/SmartContract/Manifest/TestFile/SampleNep17Token.manifest.json
  tests/Neo.UnitTests/SmartContract/Manifest/TestFile/SampleOracle.manifest.json
  tests/Neo.UnitTests/SmartContract/Manifest/UT_ContractPermissionDescriptor.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_StdLib.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
Labels: ready to merge

#3353 [Neo Plugin UT] Rpcserver unit test on node
  src/Neo/Ledger/MemoryPool.cs
  src/Plugins/RpcServer/RpcServer.Node.cs
  tests/Neo.Plugins.RpcServer.Tests/TestBlockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/TestProtocolSettings.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Node.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Block.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Header.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_HeadersPayload.cs
  tests/Neo.UnitTests/SmartContract/UT_Syscalls.cs
  tests/Neo.UnitTests/TestProtocolSettings.cs
  tests/Neo.UnitTests/TestUtils.Block.cs
  tests/Neo.UnitTests/TestUtils.Transaction.cs
  tests/Neo.UnitTests/TestUtils.cs
Labels: ready to merge

#3417 Fix release compilation
  src/Neo/Ledger/MemoryPool.cs
Labels: ready to merge

#3411 `[Fix]` Publish Step
  .github/workflows/main.yml
Labels: ready to merge, GitHub Workflow, Minor Change

#3404 [Neo Core MemoryStore] MemoryStore Unit Tests.
  tests/Neo.UnitTests/Persistence/UT_MemoryClonedCache.cs
  tests/Neo.UnitTests/Persistence/UT_MemorySnapshot.cs
  tests/Neo.UnitTests/Persistence/UT_MemorySnapshotCache.cs
Labels: ready to merge

#3403 [Neo Core Storage] Implicit methods and tests
  src/Neo/SmartContract/StorageItem.cs
  src/Neo/SmartContract/StorageKey.cs
  tests/Neo.UnitTests/SmartContract/UT_Storage.cs
Labels: ready to merge

#3388 `[Move]` Part-2 Classes into Different Library - `Neo.IO`
  .github/workflows/main.yml
  neo.sln
  src/Neo.Extensions/BigIntegerExtensions.cs
  src/Neo.Extensions/Neo.Extensions.csproj
  src/Neo.GUI/GUI/MainForm.cs
  src/Neo.IO/Actors/Idle.cs
  src/Neo.IO/Caching/ReflectionCacheAttribute.cs
  src/Neo/Cryptography/ECC/ECFieldElement.cs
  src/Neo/Cryptography/ECC/ECPoint.cs
  src/Neo/Helper.cs
  src/Neo/IO/Actors/PriorityMailbox.cs
  src/Neo/IO/Actors/PriorityMessageQueue.cs
  src/Neo/IO/Caching/ReflectionCache.cs
  src/Neo/IO/Caching/RelayCache.cs
  src/Neo/SmartContract/StorageItem.cs
  src/Neo/Wallets/Wallet.cs
  tests/Neo.Extensions.Tests/Neo.Extensions.Tests.csproj
  tests/Neo.Extensions.Tests/UT_BigIntegerExtensions.cs
  tests/Neo.UnitTests/Neo.UnitTests.csproj
  tests/Neo.UnitTests/UT_Helper.cs
Labels: ready to merge

#3366 Revert "Plugin unhandled exception (#3349)"
  src/Neo/Ledger/Blockchain.cs
  src/Neo/Plugins/Plugin.cs
  src/Neo/Plugins/PluginSettings.cs
  src/Neo/Plugins/UnhandledExceptionPolicy.cs
  src/Plugins/ApplicationLogs/ApplicationLogs.json
  src/Plugins/ApplicationLogs/LogReader.cs
  src/Plugins/ApplicationLogs/Settings.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.json
  src/Plugins/DBFTPlugin/Settings.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/OracleService/OracleService.json
  src/Plugins/OracleService/Settings.cs
  src/Plugins/RpcServer/RpcServer.json
  src/Plugins/RpcServer/RpcServerPlugin.cs
  src/Plugins/RpcServer/Settings.cs
  src/Plugins/StateService/Settings.cs
  src/Plugins/StateService/StatePlugin.cs
  src/Plugins/StateService/StateService.json
  src/Plugins/StorageDumper/Settings.cs
  src/Plugins/StorageDumper/StorageDumper.cs
  src/Plugins/StorageDumper/StorageDumper.json
  src/Plugins/TokensTracker/TokensTracker.cs
  src/Plugins/TokensTracker/TokensTracker.json
  tests/Neo.UnitTests/Plugins/TestPlugin.cs
  tests/Neo.UnitTests/Plugins/UT_Plugin.cs
Labels: bug, critical, discussion, ready to merge

#3428 [Neo Core] fix obsolete warning
  src/Neo.CLI/CLI/MainService.Blockchain.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
  src/Plugins/TokensTracker/Trackers/NEP-11/Nep11Tracker.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Node.cs
Labels: ready to merge

#3421 [`Upgrade`] Nuget packages
  src/Neo.Extensions/Neo.Extensions.csproj
  src/Neo/Neo.csproj
  src/Plugins/RocksDBStore/RocksDBStore.csproj
  src/Plugins/SQLiteWallet/SQLiteWallet.csproj
  tests/Neo.ConsoleService.Tests/Neo.ConsoleService.Tests.csproj
  tests/Neo.Cryptography.BLS12_381.Tests/Neo.Cryptography.BLS12_381.Tests.csproj
  tests/Neo.Cryptography.MPTTrie.Tests/Neo.Cryptography.MPTTrie.Tests.csproj
  tests/Neo.Extensions.Tests/Neo.Extensions.Tests.csproj
  tests/Neo.Json.UnitTests/Neo.Json.UnitTests.csproj
  tests/Neo.Network.RPC.Tests/Neo.Network.RPC.Tests.csproj
  tests/Neo.Plugins.OracleService.Tests/Neo.Plugins.OracleService.Tests.csproj
  tests/Neo.Plugins.RpcServer.Tests/Neo.Plugins.RpcServer.Tests.csproj
  tests/Neo.Plugins.Storage.Tests/Neo.Plugins.Storage.Tests.csproj
  tests/Neo.UnitTests/Neo.UnitTests.csproj
  tests/Neo.VM.Tests/Neo.VM.Tests.csproj
Labels: ready to merge

#3432 [Neo Core Fix]use strong randomness
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.MakePayload.cs
Labels: ready to merge

#3430 [`Fixed`] Warning with MemoryPool
  src/Neo.CLI/CLI/MainService.Network.cs
  src/Neo.CLI/CLI/MainService.Wallet.cs
  src/Neo/Ledger/MemoryPool.cs
Labels: waiting for review, ready to merge

#3413 [Neo Core UT] Fix ut and style
  src/Neo/Neo.csproj
  tests/Neo.Plugins.OracleService.Tests/TestBlockchain.cs
  tests/Neo.Plugins.OracleService.Tests/UT_OracleService.cs
  tests/Neo.UnitTests/IO/Caching/UT_CloneCache.cs
  tests/Neo.UnitTests/IO/Caching/UT_DataCache.cs
  tests/Neo.UnitTests/Ledger/UT_Blockchain.cs
  tests/Neo.UnitTests/Ledger/UT_TransactionVerificationContext.cs
  tests/Neo.UnitTests/Ledger/UT_TrimmedBlock.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Block.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Conflicts.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Header.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_HighPriorityAttribute.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_NotValidBefore.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Transaction.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Witness.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_CryptoLib.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_FungibleToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_GasToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NeoToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_PolicyContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_RoleManagement.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_StdLib.cs
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngine.cs
  tests/Neo.UnitTests/SmartContract/UT_ContractParameterContext.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropPrices.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.NEO.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
  tests/Neo.UnitTests/SmartContract/UT_SmartContractHelper.cs
  tests/Neo.UnitTests/SmartContract/UT_Syscalls.cs
  tests/Neo.UnitTests/TestBlockchain.cs
  tests/Neo.UnitTests/UT_DataCache.cs
  tests/Neo.UnitTests/Wallets/NEP6/UT_NEP6Wallet.cs
  tests/Neo.UnitTests/Wallets/UT_AssetDescriptor.cs
  tests/Neo.UnitTests/Wallets/UT_Wallet.cs
Labels: ready to merge

#3355 [**Added**] Build `neo-cli` Docker Image
  .github/workflows/docker.yml
  .github/workflows/pkgs-delete.yml
  .neo/docker/neo-cli/Dockerfile
Labels: ready to merge, Tested, GitHub Workflow

#3435 [Neo Core Doc]create a docs folder and move existing doc to it.
  docs/ReferenceCounter.md
  docs/config.json.md
  docs/handlers.md
Labels: ready to merge

#3346 [**Part-1**] Added `ApplicationLogs` Unit Tests
  .github/workflows/main.yml
  neo.sln
  src/Plugins/ApplicationLogs/ApplicationLogs.csproj
  tests/Neo.Plugins.ApplicationLogs.Tests/Neo.Plugins.ApplicationLogs.Tests.csproj
  tests/Neo.Plugins.ApplicationLogs.Tests/Setup/TestStorage.cs
  tests/Neo.Plugins.ApplicationLogs.Tests/UT_LogStorageStore.cs
Labels: ready to merge, NGD Review

#2993 add unit tests for json
  tests/Neo.Json.UnitTests/UT_JArray.cs
  tests/Neo.Json.UnitTests/UT_JBoolean.cs
  tests/Neo.Json.UnitTests/UT_JPath.cs
  tests/Neo.Json.UnitTests/UT_JString.cs
Labels: waiting for review, NGD Review

#3437 [Neo Core VM] complete opcode comments
  src/Neo.VM/JumpTable/JumpTable.Compound.cs
  src/Neo.VM/JumpTable/JumpTable.Numeric.cs
  src/Neo.VM/JumpTable/JumpTable.Splice.cs
  src/Neo.VM/JumpTable/JumpTable.Stack.cs
  src/Neo.VM/OpCode.cs
Labels: ready to merge

#3436 [Neo Core] Obsolete applicationengine snapshot
  src/Neo/Network/P2P/Payloads/Conditions/CalledByGroupCondition.cs
  src/Neo/Network/P2P/Payloads/Conditions/GroupCondition.cs
  src/Neo/SmartContract/ApplicationEngine.Contract.cs
  src/Neo/SmartContract/ApplicationEngine.Runtime.cs
  src/Neo/SmartContract/ApplicationEngine.Storage.cs
  src/Neo/SmartContract/ApplicationEngine.cs
  src/Neo/SmartContract/ContractParametersContext.cs
  src/Neo/SmartContract/ExecutionContextState.cs
  src/Neo/SmartContract/Native/ContractManagement.cs
  src/Neo/SmartContract/Native/FungibleToken.cs
  src/Neo/SmartContract/Native/GasToken.cs
  src/Neo/SmartContract/Native/LedgerContract.cs
  src/Neo/SmartContract/Native/NativeContract.cs
  src/Neo/SmartContract/Native/NeoToken.cs
  src/Neo/SmartContract/Native/OracleContract.cs
  src/Neo/SmartContract/Native/PolicyContract.cs
  src/Neo/SmartContract/Native/RoleManagement.cs
  src/Neo/Wallets/Wallet.cs
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
  tests/Neo.Plugins.OracleService.Tests/UT_OracleService.cs
  tests/Neo.UnitTests/IO/Caching/UT_CloneCache.cs
  tests/Neo.UnitTests/Ledger/UT_Blockchain.cs
  tests/Neo.UnitTests/Ledger/UT_MemoryPool.cs
  tests/Neo.UnitTests/Ledger/UT_TransactionVerificationContext.cs
  tests/Neo.UnitTests/Ledger/UT_TrimmedBlock.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Block.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Conflicts.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Header.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_HighPriorityAttribute.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_NotValidBefore.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Transaction.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Witness.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_CryptoLib.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_FungibleToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_GasToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NeoToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_PolicyContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_RoleManagement.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_StdLib.cs
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngine.cs
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngineProvider.cs
  tests/Neo.UnitTests/SmartContract/UT_ContractParameterContext.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropPrices.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.NEO.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
  tests/Neo.UnitTests/SmartContract/UT_SmartContractHelper.cs
  tests/Neo.UnitTests/SmartContract/UT_Syscalls.cs
  tests/Neo.UnitTests/UT_DataCache.cs
  tests/Neo.UnitTests/Wallets/UT_AssetDescriptor.cs
  tests/Neo.UnitTests/Wallets/UT_Wallet.cs
Labels: ready to merge

#3433 [Neo Plugin RpcServer UT]Plugin rpcserver wallet UTs
  src/Plugins/RpcServer/Result.cs
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Wallet.cs
  tests/Neo.UnitTests/TestUtils.Contract.cs
  tests/Neo.UnitTests/TestUtils.Transaction.cs
  tests/Neo.UnitTests/TestUtils.cs
Labels: ready to merge

#3400 `[Move]` Part-3 Classes into Different Library - `Neo.Extensions`
  src/Neo.CLI/AssemblyExtensions.cs
  src/Neo.CLI/CLI/MainService.Tools.cs
  src/Neo.CLI/CLI/MainService.Vote.cs
  src/Neo.CLI/CLI/MainService.Wallet.cs
  src/Neo.CLI/CLI/MainService.cs
  src/Neo.CLI/Neo.CLI.csproj
  src/Neo.Extensions/ByteExtensions.cs
  src/Neo.GUI/GUI/DeployContractDialog.cs
  src/Neo.GUI/GUI/InvokeContractDialog.cs
  src/Neo.GUI/GUI/SigningDialog.cs
  src/Neo.GUI/GUI/ViewContractDialog.cs
  src/Neo.GUI/GUI/ViewPrivateKeyDialog.cs
  src/Neo.GUI/GUI/Wrappers/HexConverter.cs
  src/Neo/Cryptography/Base58.cs
  src/Neo/Cryptography/ECC/ECPoint.cs
  src/Neo/Cryptography/Helper.cs
  src/Neo/Helper.cs
  src/Neo/SmartContract/ContractParameter.cs
  src/Neo/UInt160.cs
  src/Neo/UInt256.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
  src/Plugins/MPTTrie/Cryptography/MPTTrie/Trie.Delete.cs
  src/Plugins/MPTTrie/Cryptography/MPTTrie/Trie.Find.cs
  src/Plugins/MPTTrie/Cryptography/MPTTrie/Trie.Proof.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/RpcClient/Nep17API.cs
  src/Plugins/RpcServer/RpcServer.Blockchain.cs
  src/Plugins/TokensTracker/Trackers/NEP-11/Nep11Tracker.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Cache.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Node.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Trie.cs
  tests/Neo.Extensions.Tests/UT_ByteExtensions.cs
  tests/Neo.Network.RPC.Tests/UT_Nep17API.cs
  tests/Neo.Network.RPC.Tests/UT_Utility.cs
  tests/Neo.Network.RPC.Tests/UT_WalletAPI.cs
  tests/Neo.UnitTests/Cryptography/UT_Cryptography_Helper.cs
  tests/Neo.UnitTests/Cryptography/UT_Murmur128.cs
  tests/Neo.UnitTests/Cryptography/UT_SCrypt.cs
  tests/Neo.UnitTests/IO/Caching/UT_CloneCache.cs
  tests/Neo.UnitTests/IO/UT_IOHelper.cs
  tests/Neo.UnitTests/Ledger/UT_TrimmedBlock.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Block.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Header.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Signers.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Transaction.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Witness.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_CryptoLib.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NeoToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_RoleManagement.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_StdLib.cs
  tests/Neo.UnitTests/SmartContract/UT_ContractParameter.cs
  tests/Neo.UnitTests/SmartContract/UT_ContractParameterContext.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.NEO.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
  tests/Neo.UnitTests/SmartContract/UT_KeyBuilder.cs
  tests/Neo.UnitTests/UT_Helper.cs
  tests/Neo.UnitTests/VM/UT_Helper.cs
Labels: ready to merge

#3420 [`Optimization`] Parsing Smart Contract Script Analysis
  src/Neo.CLI/CLI/MainService.Tools.cs
  src/Neo.CLI/Tools/VMInstruction.cs
Labels: optimization, waiting for review, ready to merge

#3442 [Neo Core Benchmark]update benchmark system
  benchmarks/Neo.Benchmarks/Benchmarks.POC.cs
  benchmarks/Neo.Benchmarks/Neo.Benchmarks.csproj
  benchmarks/Neo.Benchmarks/Program.cs
  benchmarks/Neo.VM.Benchmarks/Benchmarks.POC.cs
  benchmarks/Neo.VM.Benchmarks/Neo.VM.Benchmarks.csproj
  benchmarks/Neo.VM.Benchmarks/Program.cs
Labels: ready to merge

#3443 [rpc] Extend `getversion` RPC response with additional protocol settings
  src/Plugins/RpcClient/Models/RpcVersion.cs
  src/Plugins/RpcServer/RpcServer.Node.cs
  tests/Neo.Network.RPC.Tests/RpcTestCases.json
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Node.cs
Labels: waiting for review, ready to merge
