Repository neo-project/neo, pull requests merged in 2025-04, with the labels that each got.

#3858 config: upgrade NeoFS chains protocol configuration
  src/Neo.CLI/CLI/MainService.CommandLine.cs
  src/Neo.CLI/config.fs.mainnet.json
  src/Neo.CLI/config.fs.testnet.json
  src/Neo/ProtocolSettings.cs
  tests/Neo.UnitTests/UT_ProtocolSettings.cs
Labels: Ready to Merge, Easy-to-Review

#3864 [Plugin UT] add more rpcserver UTs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Node.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Utilities.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Wallet.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.cs
Labels: Waiting for Review, Ready to Merge, Unit Tests

#3865 [`Fix`]: add default value for `key` parameter in help command
  src/Neo.ConsoleService/ConsoleServiceBase.cs
Labels: Ready to Merge

#3860 [`Fix`]: concurrent conflict in `Cache.CopyTo`
  src/Neo.IO/Caching/Cache.cs
Labels: Ready to Merge, Easy-to-Review

#3859 Native: swap Policy's `[get/set]AttributeFee` implementations
  src/Neo/Network/P2P/Payloads/TransactionAttribute.cs
  src/Neo/SmartContract/Native/GasToken.cs
  src/Neo/SmartContract/Native/PolicyContract.cs
Labels: Bug, Waiting for Review, Ready to Merge

#3866 [`Add`]: set name when create wallet
  src/Neo.CLI/CLI/MainService.Wallet.cs
  src/Neo.CLI/CLI/MainService.cs
  src/Neo.ConsoleService/ConsoleServiceBase.cs
  src/Neo/Wallets/IWalletFactory.cs
Labels: Ready to Merge

#3863 move non-plugins out of plugins
  neo.sln
  src/Neo.CLI/Neo.CLI.csproj
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Cache.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Helper.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Node.Branch.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Node.Extension.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Node.Hash.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Node.Leaf.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Node.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/NodeType.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.Delete.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.Find.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.Get.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.Proof.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.Put.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.cs
  src/Neo.Cryptography.MPTTrie/Neo.Cryptography.MPTTrie.csproj
  src/Neo.Network.RpcClient/API_REFERENCE.md
  src/Neo.Network.RpcClient/ContractClient.cs
  src/Neo.Network.RpcClient/Models/RpcAccount.cs
  src/Neo.Network.RpcClient/Models/RpcApplicationLog.cs
  src/Neo.Network.RpcClient/Models/RpcBlock.cs
  src/Neo.Network.RpcClient/Models/RpcBlockHeader.cs
  src/Neo.Network.RpcClient/Models/RpcContractState.cs
  src/Neo.Network.RpcClient/Models/RpcFoundStates.cs
  src/Neo.Network.RpcClient/Models/RpcInvokeResult.cs
  src/Neo.Network.RpcClient/Models/RpcMethodToken.cs
  src/Neo.Network.RpcClient/Models/RpcNefFile.cs
  src/Neo.Network.RpcClient/Models/RpcNep17Balances.cs
  src/Neo.Network.RpcClient/Models/RpcNep17TokenInfo.cs
  src/Neo.Network.RpcClient/Models/RpcNep17Transfers.cs
  src/Neo.Network.RpcClient/Models/RpcPeers.cs
  src/Neo.Network.RpcClient/Models/RpcPlugin.cs
  src/Neo.Network.RpcClient/Models/RpcRawMemPool.cs
  src/Neo.Network.RpcClient/Models/RpcRequest.cs
  src/Neo.Network.RpcClient/Models/RpcResponse.cs
  src/Neo.Network.RpcClient/Models/RpcStateRoot.cs
  src/Neo.Network.RpcClient/Models/RpcTransaction.cs
  src/Neo.Network.RpcClient/Models/RpcTransferOut.cs
  src/Neo.Network.RpcClient/Models/RpcUnclaimedGas.cs
  src/Neo.Network.RpcClient/Models/RpcValidateAddressResult.cs
  src/Neo.Network.RpcClient/Models/RpcValidator.cs
  src/Neo.Network.RpcClient/Models/RpcVersion.cs
  src/Neo.Network.RpcClient/Neo.Network.RpcClient.csproj
  src/Neo.Network.RpcClient/Nep17API.cs
  src/Neo.Network.RpcClient/PolicyAPI.cs
  src/Neo.Network.RpcClient/Properties/AssemblyInfo.cs
  src/Neo.Network.RpcClient/README.md
  src/Neo.Network.RpcClient/RpcClient.cs
  src/Neo.Network.RpcClient/RpcException.cs
  src/Neo.Network.RpcClient/StateAPI.cs
  src/Neo.Network.RpcClient/TransactionManager.cs
  src/Neo.Network.RpcClient/TransactionManagerFactory.cs
  src/Neo.Network.RpcClient/Utility.cs
  src/Neo.Network.RpcClient/WalletAPI.cs
  src/Plugins/StateService/StateService.csproj
  tests/Neo.Cryptography.MPTTrie.Tests/Neo.Cryptography.MPTTrie.Tests.csproj
  tests/Neo.Network.RPC.Tests/Neo.Network.RPC.Tests.csproj
Labels: Ready to Merge

#3868 Release the resources
  src/Neo/Ledger/Blockchain.cs
  src/Neo/Ledger/HeaderCache.cs
  src/Plugins/ApplicationLogs/Store/NeoStore.cs
  src/Plugins/StateService/Storage/StateStore.cs
  src/Plugins/TokensTracker/Trackers/TrackerBase.cs
  tests/Neo.UnitTests/Ledger/UT_HeaderCache.cs
Labels: Ready to Merge

#3872 Optimize Uint160 and Uint256 constructor
  src/Neo/UInt160.cs
  src/Neo/UInt256.cs
Labels: Waiting for Review, Easy-to-Review

#3873 Optimize ram usage
  src/Neo/Ledger/Blockchain.cs
Labels: Optimization, Ready to Merge

#3883 [`Optimize`]: return `GetFileNameWithoutExtension(Path)` if name is not set
  src/Neo/Wallets/NEP6/NEP6Wallet.cs
  tests/Neo.UnitTests/Wallets/NEP6/UT_NEP6Wallet.cs
Labels: Ready to Merge

#3884 [`Style`]: format long lines
  src/Neo/NeoSystem.cs
  src/Neo/Persistence/StoreFactory.cs
  src/Neo/Plugins/Plugin.cs
  tests/Neo.UnitTests/Cryptography/ECC/UT_ECPoint.cs
  tests/Neo.UnitTests/Cryptography/UT_Base58.cs
  tests/Neo.UnitTests/SmartContract/UT_ContractParameterContext.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.NEO.cs
Labels: Waiting for Review, Ready to Merge

#3879 Optimize block deserialization
  src/Neo/Network/P2P/Payloads/Block.cs
Labels: Ready to Merge

#3888 [`fix`] stop syncing on block 1465790
  src/Neo/SmartContract/ContractTaskAwaiter.cs
  src/Neo/SmartContract/Native/OracleContract.cs
Labels: Critical, Ready to Merge

#3867 [style] Added some var styles
  src/Neo/Cryptography/Helper.cs
  src/Neo/Cryptography/MerkleTree.cs
  src/Neo/Cryptography/MerkleTreeNode.cs
  src/Neo/Ledger/Blockchain.ApplicationExecuted.cs
  src/Neo/Ledger/PoolItem.cs
  src/Neo/Ledger/TransactionRouter.cs
  src/Neo/Ledger/TransactionVerificationContext.cs
  src/Neo/Network/UPnP.cs
  src/Neo/Persistence/ClonedCache.cs
Labels: Ready to Merge

#3891 Move Import/Export operations to a seperate file.
  src/Neo.CLI/CLI/MainService.Block.cs
  src/Neo.CLI/CLI/MainService.Blockchain.cs
  src/Neo.CLI/CLI/MainService.cs
Labels: Ready to Merge

#3889 [NEO CLI]replace old show state
  src/Neo.CLI/CLI/MainService.Node.cs
Labels: Waiting for Review

#3885 [`Optimize`]: Cache implemetation
  benchmarks/Neo.Benchmarks/IO/Benchmarks.Cache.cs
  src/Neo.IO/Caching/Cache.cs
  src/Neo.IO/Caching/LRUCache.cs
  tests/Neo.UnitTests/IO/Caching/UT_Cache.cs
  tests/Neo.UnitTests/IO/Caching/UT_LRUCache.cs
Labels: Optimization, Ready to Merge

#3893 fix a few warnings.
  src/Neo/Persistence/DataCache.cs
  tests/Neo.Cryptography.BLS12_381.Tests/UT_G1.cs
  tests/Neo.Cryptography.BLS12_381.Tests/UT_G2.cs
Labels: Ready to Merge, Easy-to-Review

#3871 Ensure Notary attribute
  src/Neo/Network/P2P/Payloads/NotaryAssisted.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_NotaryAssisted.cs
Labels: Blocker, Ready to Merge

#3882 [`Add`]: start with `Signer` support
  src/Neo.CLI/CLI/MainService.Wallet.cs
  src/Neo.CLI/CLI/MainService.cs
  src/Neo/Sign/ISigner.cs
  src/Neo/Sign/SignerFactory.cs
  src/Neo/SmartContract/ContractParametersContext.cs
  src/Neo/Wallets/Wallet.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.cs
  tests/Neo.UnitTests/SmartContract/UT_ContractParameterContext.cs
  tests/Neo.UnitTests/Wallets/UT_Wallet.cs
Labels: Waiting for Review, Ready to Merge

#3890 [add] Optimize check if an address is a contract
  src/Neo.CLI/CLI/MainService.Wallet.cs
  src/Neo/SmartContract/Native/ContractManagement.cs
  src/Neo/SmartContract/Native/FungibleToken.cs
  src/Neo/SmartContract/Native/OracleContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
Labels: Optimization, Waiting for Review, Ready to Merge, Hardfork

#3812 Ensure that view interops can't be changed outside
  src/Neo.VM/Debugger.cs
  src/Neo/SmartContract/BinarySerializer.cs
  src/Neo/SmartContract/Native/ContractManagement.cs
  src/Neo/SmartContract/Native/NeoToken.cs
  src/Neo/SmartContract/Native/OracleContract.cs
  src/Neo/SmartContract/StorageItem.cs
  tests/Neo.UnitTests/Extensions/UT_ContractStateExtensions.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Conflicts.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropPrices.cs
  tests/Neo.UnitTests/SmartContract/UT_SmartContractHelper.cs
Labels: Waiting for Review, Ready to Merge

#3895 Native: move MillisecondsPerBlock setting to native Policy
  docs/config.json.md
  src/Neo.CLI/CLI/MainService.Node.cs
  src/Neo.GUI/GUI/MainForm.cs
  src/Neo/Extensions/NeoSystemExtensions.cs
  src/Neo/Ledger/Blockchain.cs
  src/Neo/Ledger/MemoryPool.cs
  src/Neo/ProtocolSettings.cs
  src/Neo/SmartContract/ApplicationEngine.cs
  src/Neo/SmartContract/Native/PolicyContract.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusService.Check.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
  src/Plugins/RpcServer/RpcServer.Node.cs
  src/Plugins/StateService/Verification/VerificationService.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_PolicyContract.cs
Labels: Critical, Ready to Merge, Hardfork, Core

#3877 Clean `KeyedCollectionSlim.RemoveFirst` method
  src/Neo.IO/Caching/KeyedCollectionSlim.cs
  src/Neo/Network/P2P/RemoteNode.ProtocolHandler.cs
  tests/Neo.UnitTests/IO/Caching/UT_KeyedCollectionSlim.cs
Labels: Waiting for Review, Ready to Merge

#3901 Update workflow
  .github/workflows/main.yml
Labels: Ready to Merge, NGD Review, Easy-to-Review

#3902 Use `DateTime.UtcNow` for time differences
  src/Neo.CLI/CLI/MainService.Logger.cs
  src/Neo.CLI/CLI/MainService.Node.cs
  src/Neo/Network/P2P/Payloads/VersionPayload.cs
  src/Neo/Network/UPnP.cs
  tests/Neo.Extensions.Tests/UT_DateTimeExtensions.cs
Labels: Waiting for Review, Ready to Merge

#3898 Native: move MaxTraceableBlocks setting to native Policy
  docs/config.json.md
  src/Neo/Extensions/NeoSystemExtensions.cs
  src/Neo/Ledger/Blockchain.cs
  src/Neo/NeoSystem.cs
  src/Neo/ProtocolSettings.cs
  src/Neo/SmartContract/Native/LedgerContract.cs
  src/Neo/SmartContract/Native/PolicyContract.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs
  src/Plugins/RpcServer/RpcServer.Node.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_PolicyContract.cs
Labels: Critical, Waiting for Review, Ready to Merge, Hardfork, Core

#3906 [`Style`]: move bytes extensions from `Unsafe` to `ByteExtensions`
  src/Neo.Extensions/ByteExtensions.cs
  src/Neo.VM/Script.cs
  src/Neo.VM/Types/StackItem.Vertex.cs
  src/Neo.VM/Unsafe.cs
  tests/Neo.Extensions.Tests/UT_ByteExtensions.cs
  tests/Neo.VM.Tests/UT_Unsafe.cs
Labels: Ready to Merge

#3874 Optimize memory usage
  src/Neo.CLI/CLI/MainService.cs
  src/Neo.CLI/Settings.cs
  src/Neo.CLI/config.fs.mainnet.json
  src/Neo.CLI/config.fs.testnet.json
  src/Neo.CLI/config.json
  src/Neo.CLI/config.mainnet.json
  src/Neo.CLI/config.testnet.json
  src/Neo.IO/Caching/HashSetCache.cs
  src/Neo/Network/P2P/ChannelsConfig.cs
  src/Neo/Network/P2P/LocalNode.cs
  src/Neo/Network/P2P/Peer.cs
  src/Neo/Network/P2P/RemoteNode.ProtocolHandler.cs
  src/Neo/Network/P2P/RemoteNode.cs
  src/Neo/Network/P2P/TaskManager.cs
  tests/Neo.UnitTests/IO/Caching/UT_HashSetCache.cs
  tests/Neo.UnitTests/Network/P2P/UT_LocalNode.cs
  tests/Neo.UnitTests/Network/P2P/UT_RemoteNode.cs
Labels: Bug, Critical, Blocked, Optimization, Ready to Merge

#3907 Neo.CLI: fix NeoFS testnet configuration
  src/Neo.CLI/config.fs.testnet.json
Labels: Bug, Waiting for Review, Ready to Merge

#3909 Native: revert Update/Deploy callflag change for pre-Aspidochelone
  src/Neo/SmartContract/Native/ContractManagement.cs
Labels: Bug, Ready to Merge

#3913 [`Optimize`]: some optimizations for `KeyedCollectionSlim`
  benchmarks/Neo.Benchmarks/IO/Benchmarks.Cache.cs
  src/Neo.IO/Caching/KeyedCollectionSlim.cs
  src/Neo.IO/Neo.IO.csproj
  src/Neo/Network/P2P/RemoteNode.ProtocolHandler.cs
  tests/Neo.UnitTests/IO/Caching/UT_KeyedCollectionSlim.cs
Labels: Ready to Merge

#3910 Native: adjust hardfork activation definition
  src/Neo/SmartContract/Native/NativeContract.cs
Labels: Bug, Ready to Merge, Core

#3914 [`Optimize`]: HashSetCache Implementation
  benchmarks/Neo.Benchmarks/IO/Benchmarks.Cache.cs
  src/Neo.IO/Caching/HashSetCache.cs
  src/Neo/Network/P2P/RemoteNode.ProtocolHandler.cs
  src/Neo/Network/P2P/RemoteNode.cs
  src/Neo/Network/P2P/TaskManager.cs
  tests/Neo.UnitTests/IO/Caching/UT_HashSetCache.cs
  tests/Neo.UnitTests/UT_Helper.cs
Labels: Ready to Merge

#3912 Fix RPC error codes not being correctly returned in responses
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
  src/Plugins/RpcServer/RpcServer.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcErrorHandling.cs
Labels: Waiting for Review

#3178 Implement native Notary contract
  src/Neo/SmartContract/Native/NativeContract.cs
  src/Neo/SmartContract/Native/Notary.cs
  tests/Neo.UnitTests/Extensions/NativeContractExtensions.cs
  tests/Neo.UnitTests/Extensions/Nep17NativeContractExtensions.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_GasToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_Notary.cs
  tests/Neo.UnitTests/TestUtils.Transaction.cs
Labels: Feature, Ready to Merge, Hardfork
