Repository neo-project/neo, pull requests merged in 2025-02, with the labels that each got.

#3710 [`Fix`] ByteArrayComparer
  src/Neo.Extensions/ByteArrayComparer.cs
Labels: Waiting for Review

#3711 ['Bug'] MemoryStore and MemorySnapshot
  src/Neo/Persistence/MemorySnapshot.cs
  src/Neo/Persistence/MemoryStore.cs
  tests/Neo.Plugins.Storage.Tests/StoreTest.cs
  tests/Neo.UnitTests/Persistence/UT_MemoryStore.cs
Labels: Waiting for Review

#3683 [`Improve`]: use `IReadOnlyStoreView` instead.
  src/Neo/SmartContract/ApplicationEngine.cs
  src/Neo/SmartContract/Native/ContractManagement.cs
  src/Neo/SmartContract/Native/ContractMethodMetadata.cs
  src/Neo/SmartContract/Native/FungibleToken.cs
  src/Neo/SmartContract/Native/LedgerContract.cs
  src/Neo/SmartContract/Native/NeoToken.cs
  src/Neo/SmartContract/Native/OracleContract.cs
  src/Neo/SmartContract/Native/PolicyContract.cs
  src/Plugins/StorageDumper/StorageDumper.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_ContractMethodAttribute.cs
Labels: Ready to Merge

#3717 [`Optimization`]: check null when set `IVerifiable.Witnesses`
  src/Neo/Network/P2P/Payloads/Block.cs
  src/Neo/Network/P2P/Payloads/ExtensiblePayload.cs
  src/Neo/Network/P2P/Payloads/Header.cs
  src/Plugins/StateService/Network/StateRoot.cs
  src/Plugins/StateService/StatePlugin.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Block.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_ExtensiblePayload.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Header.cs
  tests/Neo.UnitTests/TestUtils.Block.cs
  tests/Neo.UnitTests/TestUtils.Contract.cs
  tests/Neo.UnitTests/TestUtils.Transaction.cs
  tests/Neo.UnitTests/TestUtils.cs
Labels: Waiting for Review

#3716 [`Optimization`]: make some unit tests more readable
  src/Neo/Network/P2P/Payloads/ExtensiblePayload.cs
  src/Neo/Network/P2P/Payloads/Header.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Block.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Header.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_HeadersPayload.cs
  tests/Neo.UnitTests/TestUtils.Block.cs
Labels: Ready to Merge

#3718 Nullable storage classes
  src/Neo/Persistence/IReadOnlyStoreView.cs
  src/Neo/Persistence/ISnapshot.cs
  src/Neo/Persistence/IStore.cs
  src/Neo/Persistence/IStoreProvider.cs
  src/Neo/Persistence/MemoryStoreProvider.cs
  src/Neo/Persistence/ReadOnlyStoreView.cs
  src/Neo/Persistence/StoreFactory.cs
  src/Neo/SmartContract/KeyBuilder.cs
  src/Neo/SmartContract/StorageItem.cs
  src/Neo/SmartContract/StorageKey.cs
  tests/Neo.Plugins.ApplicationLogs.Tests/UT_LogStorageStore.cs
  tests/Neo.UnitTests/SmartContract/UT_Storage.cs
Labels: Waiting for Review

#3725 [`fix`] Docker Image
  .github/workflows/docker.yml
  .neo/docker/neo-cli/Dockerfile
Labels: Ready to Merge

#3722 [`Add`] Read Me for Neo Build Engine (`NEBuild`, `neo-build`)
  docs/neo-build/README.md
Labels: Ready to Merge

#3706 [Core MD] Clarify repo scope: C# implementation ≠ Neo Core protocol
  README.md
Labels: Waiting for Review, Ready to Merge

#3727 [`Add`] Neo Build Project Files
  neo.sln
  src/Shared/Directory.Build.props
  src/Shared/Neo.Build.Core/Neo.Build.Core.csproj
  tests/Neo.Build.Core.Tests/MSTestSettings.cs
  tests/Neo.Build.Core.Tests/Neo.Build.Core.Tests.csproj
Labels: Blocker, Waiting for Review, Neo Build

#3719 Nullable IO and plugins folders
  src/Neo/IO/Actors/PriorityMailbox.cs
  src/Neo/IO/Actors/PriorityMessageQueue.cs
  src/Neo/IO/Caching/ECDsaCache.cs
  src/Neo/IO/Caching/ECPointCache.cs
  src/Neo/IO/Caching/ReflectionCache.cs
  src/Neo/IO/Caching/RelayCache.cs
  src/Neo/Plugins/Plugin.cs
  src/Neo/Plugins/PluginSettings.cs
Labels: Ready to Merge

#3728 [`Add`] Neo Build Error Definition - Part 1
  docs/neo-build/error-codes.md
  src/Shared/Neo.Build.Core/NeoBuildErrorCodes.General.cs
  src/Shared/Neo.Build.Core/NeoBuildErrorCodes.Wallet.cs
  src/Shared/Neo.Build.Core/NeoBuildErrorCodes.cs
Labels: Blocker, Waiting for Review, Neo Build

#3740 Avoid duplicate conditions
  src/Neo/SmartContract/ApplicationEngine.cs
Labels: Waiting for Review, Easy-to-Review

#3742 fix stuff
  benchmarks/Neo.Benchmarks/Persistence/Bechmarks_LevelDB.cs
  benchmarks/Neo.Json.Benchmarks/Benchmark_JsonDeserialize.cs
  src/Neo.CLI/CLI/MainService.Wallet.cs
  src/Neo/BigDecimal.cs
  src/Neo/IO/Actors/PriorityMailbox.cs
  src/Neo/IO/Actors/PriorityMessageQueue.cs
  src/Neo/IO/Caching/ECDsaCache.cs
  src/Neo/IO/Caching/ECPointCache.cs
  src/Neo/IO/Caching/ReflectionCache.cs
  src/Neo/IO/Caching/RelayCache.cs
  src/Neo/Ledger/MemoryPool.cs
  src/Neo/Persistence/ClonedCache.cs
  src/Neo/Persistence/DataCache.cs
  src/Neo/Persistence/IRawReadOnlyStore.cs
  src/Neo/Persistence/IReadOnlyStore.cs
  src/Neo/Persistence/IStore.cs
  src/Neo/Persistence/IStoreProvider.cs
  src/Neo/Persistence/IStoreSnapshot.cs
  src/Neo/Persistence/IWriteStore.cs
  src/Neo/Persistence/MemorySnapshot.cs
  src/Neo/Persistence/MemoryStore.cs
  src/Neo/Persistence/MemoryStoreProvider.cs
  src/Neo/Persistence/StoreCache.cs
  src/Neo/Persistence/StoreFactory.cs
  src/Neo/Plugins/Plugin.cs
  src/Neo/Plugins/PluginSettings.cs
  src/Neo/SmartContract/KeyBuilder.cs
  src/Neo/SmartContract/StorageItem.cs
  src/Neo/SmartContract/StorageKey.cs
  src/Neo/Wallets/Helper.cs
  src/Plugins/MPTTrie/Cryptography/MPTTrie/Node.cs
  src/Plugins/RpcClient/TransactionManager.cs
  src/Plugins/RpcServer/Result.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
  src/Plugins/StateService/StatePlugin.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_Result.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Wallet.cs
  tests/Neo.UnitTests/Extensions/NativeContractExtensions.cs
  tests/Neo.UnitTests/SmartContract/UT_Helper.cs
  tests/Neo.UnitTests/SmartContract/UT_NotifyEventArgs.cs
Labels: Ready to Merge

#3745 removed unused files
  src/Plugins/StatelessBlock/StatelessBlock.cs
  src/Plugins/StatelessBlock/StatelessBlock.csproj
Labels: Ready to Merge

#3736 Move `MemoryStore` to a different folder
  src/Neo.CLI/Settings.cs
  src/Neo/NeoSystem.cs
  src/Neo/Persistence/Providers/MemorySnapshot.cs
  src/Neo/Persistence/Providers/MemoryStore.cs
  src/Neo/Persistence/Providers/MemoryStoreProvider.cs
  src/Neo/Persistence/StoreFactory.cs
  src/Plugins/MPTTrie/Cryptography/MPTTrie/Trie.Proof.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Cache.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Trie.cs
  tests/Neo.Plugins.ApplicationLogs.Tests/UT_LogReader.cs
  tests/Neo.Plugins.ApplicationLogs.Tests/UT_LogStorageStore.cs
  tests/Neo.Plugins.OracleService.Tests/TestBlockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/TestBlockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/TestMemoryStoreProvider.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.cs
  tests/Neo.Plugins.Storage.Tests/StoreTest.cs
  tests/Neo.UnitTests/Persistence/TestMemoryStoreProvider.cs
  tests/Neo.UnitTests/Persistence/UT_CloneCache.cs
  tests/Neo.UnitTests/Persistence/UT_DataCache.cs
  tests/Neo.UnitTests/Persistence/UT_MemoryClonedCache.cs
  tests/Neo.UnitTests/Persistence/UT_MemorySnapshot.cs
  tests/Neo.UnitTests/Persistence/UT_MemorySnapshotCache.cs
  tests/Neo.UnitTests/Persistence/UT_MemoryStore.cs
  tests/Neo.UnitTests/Persistence/UT_ReadOnlyStoreView.cs
  tests/Neo.UnitTests/TestBlockchain.cs
Labels: Ready to Merge

#3737 Remove `Trackable.Key` from `DataCache.Trackable`
  src/Neo/Ledger/Blockchain.cs
  src/Neo/Network/P2P/RemoteNode.ProtocolHandler.cs
  src/Neo/Network/P2P/TaskManager.cs
  src/Neo/Persistence/DataCache.cs
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
  src/Plugins/StateService/StatePlugin.cs
  src/Plugins/StateService/Storage/StateStore.cs
  src/Plugins/StorageDumper/StorageDumper.cs
  tests/Neo.UnitTests/Persistence/UT_DataCache.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NeoToken.cs
Labels: Waiting for Review

#3748 updated dockerfile for action workflow
  .neo/docker/neo-cli/Dockerfile
Labels: Ready to Merge

#3665 [Fix] Leveldb RocksDb Runtime Binaries
  .github/workflows/docker.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  benchmarks/Neo.Extensions.Benchmarks/Neo.Extensions.Benchmarks.csproj
  src/Neo.CLI/Neo.CLI.csproj
  src/Plugins/LevelDBStore/LevelDBStore.csproj
Labels: Ready to Merge

#3730 [`Add`] Neo Build Error Base - Part 2
  src/Shared/Neo.Build.Core/Exceptions/INeoBuildException.cs
  src/Shared/Neo.Build.Core/Exceptions/NeoBuildException.cs
  tests/Neo.Build.Core.Tests/Exceptions/UT_NeoBuildException.cs
Labels: Blocker, Waiting for Review, Neo Build

#3754 Optimize Release
  .github/workflows/docker.yml
  .github/workflows/nuget.yml
  .github/workflows/release.yml
Labels: Ready to Merge, GitHub Workflow

#3753 [`fix`] Unit tests
  tests/Directory.Build.props
  tests/Neo.ConsoleService.Tests/Neo.ConsoleService.Tests.csproj
  tests/Neo.Cryptography.BLS12_381.Tests/Neo.Cryptography.BLS12_381.Tests.csproj
  tests/Neo.Cryptography.MPTTrie.Tests/Neo.Cryptography.MPTTrie.Tests.csproj
  tests/Neo.Extensions.Tests/Neo.Extensions.Tests.csproj
  tests/Neo.Extensions.Tests/UT_AssemblyExtensions.cs
  tests/Neo.Json.UnitTests/Neo.Json.UnitTests.csproj
  tests/Neo.Network.RPC.Tests/Neo.Network.RPC.Tests.csproj
  tests/Neo.Plugins.OracleService.Tests/E2E_Https.cs
  tests/Neo.Plugins.OracleService.Tests/Neo.Plugins.OracleService.Tests.csproj
  tests/Neo.Plugins.OracleService.Tests/UT_OracleService.cs
  tests/Neo.Plugins.RpcServer.Tests/Neo.Plugins.RpcServer.Tests.csproj
  tests/Neo.Plugins.Storage.Tests/Neo.Plugins.Storage.Tests.csproj
  tests/Neo.UnitTests/Neo.UnitTests.csproj
  tests/Neo.VM.Tests/Neo.VM.Tests.csproj
Labels: Critical, Ready to Merge, Needs Reapproved

#3751 [`Optimziation`]: support running specified benchmarks
  benchmarks/Neo.Benchmarks/Program.cs
  benchmarks/Neo.Extensions.Benchmarks/Program.cs
  benchmarks/Neo.Json.Benchmarks/Program.cs
Labels: Waiting for Review

#3752 [`Add`] Enable Continuous Integration Build
  .github/workflows/docker.yml
  .github/workflows/main.yml
  .github/workflows/nuget.yml
  .github/workflows/release.yml
  src/Directory.Build.props
  tests/Directory.Build.props
Labels: Ready to Merge, GitHub Workflow, Needs Reapproved

#3763 Rename to `nuget.config` -- case sensitive
  nuget.config
Labels: Waiting for Review, Easy-to-Review

#3757 Optimize `ECPoint` serialization
  src/Neo.IO/ISerializableSpan.cs
  src/Neo/Cryptography/ECC/ECPoint.cs
  src/Neo/SmartContract/KeyBuilder.cs
  src/Neo/UInt160.cs
  src/Neo/UInt256.cs
  tests/Neo.Plugins.OracleService.Tests/TestUtils.cs
  tests/Neo.UnitTests/Cryptography/ECC/UT_ECPoint.cs
  tests/Neo.UnitTests/SmartContract/UT_KeyBuilder.cs
  tests/Neo.UnitTests/TestUtils.cs
Labels: Waiting for Review

#3764 Nullable BloomFilter and MerkleTree
  src/Neo/Cryptography/BloomFilter.cs
  src/Neo/Cryptography/MerkleTree.cs
Labels: Ready to Merge

#3759 [`Fix`] Github Action Issues
  .github/workflows/main.yml
  src/Directory.Build.props
  src/Plugins/Directory.Build.props
  src/Plugins/LevelDBStore/LevelDBStore.csproj
  tests/Directory.Build.props
  tests/Neo.ConsoleService.Tests/Neo.ConsoleService.Tests.csproj
  tests/Neo.Cryptography.MPTTrie.Tests/Neo.Cryptography.MPTTrie.Tests.csproj
  tests/Neo.Network.RPC.Tests/Neo.Network.RPC.Tests.csproj
  tests/Neo.Plugins.ApplicationLogs.Tests/Neo.Plugins.ApplicationLogs.Tests.csproj
  tests/Neo.Plugins.OracleService.Tests/Neo.Plugins.OracleService.Tests.csproj
  tests/Neo.Plugins.RpcServer.Tests/Neo.Plugins.RpcServer.Tests.csproj
  tests/Neo.Plugins.Storage.Tests/Neo.Plugins.Storage.Tests.csproj
  tests/Neo.VM.Tests/Neo.VM.Tests.csproj
Labels: Ready to Merge

#3696 EC Recover
  src/Neo/Cryptography/Crypto.cs
  src/Neo/Cryptography/ECC/ECCurve.cs
  src/Neo/Cryptography/HashAlgorithm.cs
  src/Neo/SmartContract/Native/CryptoLib.cs
  tests/Neo.UnitTests/Cryptography/ECC/UT_ECFieldElement.cs
  tests/Neo.UnitTests/Cryptography/UT_Crypto.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
Labels: Ready to Merge, Hardfork

#3761 Improve MaxNestingDepth of WitnessCondition
  src/Neo/Network/P2P/Payloads/Conditions/AndCondition.cs
  src/Neo/Network/P2P/Payloads/Conditions/NotCondition.cs
  src/Neo/Network/P2P/Payloads/Conditions/OrCondition.cs
  src/Neo/Network/P2P/Payloads/Conditions/WitnessCondition.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_WitnessCondition.cs
Labels: Ready to Merge

#3755 Add Support for Plugin Loading by Assembly
  src/Plugins/Directory.Build.props
Labels: Ready to Merge, Plugins

#3756 Optimize `StorageKey` creation
  src/Neo/SmartContract/Native/ContractManagement.cs
  src/Neo/SmartContract/Native/FungibleToken.cs
  src/Neo/SmartContract/Native/LedgerContract.cs
  src/Neo/SmartContract/Native/NativeContract.cs
  src/Neo/SmartContract/Native/NeoToken.cs
  src/Neo/SmartContract/Native/OracleContract.cs
  src/Neo/SmartContract/Native/PolicyContract.cs
  src/Neo/SmartContract/Native/RoleManagement.cs
  src/Neo/SmartContract/StorageKey.cs
  tests/Neo.UnitTests/Ledger/UT_StorageKey.cs
Labels: Ready to Merge

#3769 [`Fix`] Linux File Access
  src/Plugins/LevelDBStore/LevelDBStore.csproj
Labels: Waiting for Review, GitHub Workflow

#3760 [`Optimization`]: Make murmur32 appendable and faster.
  src/Neo/Cryptography/Murmur32.cs
  tests/Neo.UnitTests/Cryptography/UT_Murmur32.cs
Labels: Ready to Merge

#3767 [`Optimization`]: remove some `unsafe` usages
  src/Neo/BigDecimal.cs
  src/Neo/SmartContract/ApplicationEngine.cs
  src/Neo/UInt160.cs
  src/Neo/UInt256.cs
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngineProvider.cs
Labels: Waiting for Review, Ready to Merge

#3768 Updated `KeyBuilder` Fast Access
  benchmarks/Neo.Benchmarks/SmartContract/Benchmarks.StorageKey.cs
  src/Neo/SmartContract/KeyBuilder.cs
Labels: Ready to Merge

#3775 [`Optimization`]: some memory optimizations
  src/Neo.IO/Caching/IndexedQueue.cs
  src/Neo.VM/ScriptBuilder.cs
  src/Neo/SmartContract/Contract.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.cs
  tests/Neo.UnitTests/IO/Caching/UT_IndexedQueue.cs
Labels: Ready to Merge

#3780 [`Add`] Neo Toolset Application
  .neo/icons/neo-build.ico
  neo.sln
  src/Shared/Neo.Build.Core/Neo.Build.Core.csproj
  src/Shared/Neo.Build.ToolSet/Commands/ProgramRootCommand.cs
  src/Shared/Neo.Build.ToolSet/Neo.Build.ToolSet.csproj
  src/Shared/Neo.Build.ToolSet/Program.cs
Labels: Waiting for Review, Neo Build

#3786 [`Style`]: Rename `UnsafeData` to `IntegerExtensions`
  src/Neo.Extensions/IntegerExtensions.cs
  src/Neo.Extensions/StringExtensions.cs
  src/Neo.Extensions/UnsafeData.cs
  src/Neo/Extensions/Collections/ICollectionExtensions.cs
  src/Neo/Extensions/MemoryExtensions.cs
  src/Neo/Wallets/Helper.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.Get.cs
  src/Plugins/MPTTrie/Cryptography/MPTTrie/Node.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/TokensTracker/Extensions.cs
  tests/Neo.Extensions.Tests/UT_IntegerExtensions.cs
  tests/Neo.Extensions.Tests/UT_StringExtensions.cs
Labels: Ready to Merge

#3788 [`Fix`] Avoid null in `GetMultiSignatures`
  src/Neo/Network/P2P/Payloads/Transaction.cs
Labels: Waiting for Review, Core

#3773 [`Optimization`]: move private key usages from the `DBFTPlugin` to `Wallet`
  neo.sln
  src/Neo/Wallets/SignException.cs
  src/Neo/Wallets/Wallet.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.MakePayload.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/Neo.Plugins.DBFTPlugin.Tests.csproj
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_ConsensusContext.cs
  tests/Neo.UnitTests/TestProtocolSettings.cs
  tests/Neo.UnitTests/Wallets/UT_Wallet.cs
Labels: Waiting for Review, Ready to Merge, Core

#3784 [`Fix`] RpcStack in RpcClient
  src/Plugins/RpcClient/Models/RpcInvokeResult.cs
  tests/Neo.Network.RPC.Tests/UT_RpcModels.cs
Labels: Ready to Merge

#3781 [`Add`] Protocol Settings as Extras in Wallet
  src/Shared/Neo.Build.Core/Factories/FunctionFactory.cs
  src/Shared/Neo.Build.Core/Factories/RandomFactory.cs
  src/Shared/Neo.Build.Core/Json/Converters/JsonStringAddressConverter.cs
  src/Shared/Neo.Build.Core/Json/Converters/JsonStringECPointConverter.cs
  src/Shared/Neo.Build.Core/Json/Converters/JsonStringHexFormatConverter.cs
  src/Shared/Neo.Build.Core/Json/Converters/JsonStringKeyPairHexFormatConverter.cs
  src/Shared/Neo.Build.Core/Json/Converters/JsonStringUInt160Converter.cs
  src/Shared/Neo.Build.Core/Json/JsonPropertyNames.cs
  src/Shared/Neo.Build.Core/Models/ProtocolSettingsModel.cs
  src/Shared/Neo.Build.Core/Models/Wallets/TestWalletAccountModel.cs
  src/Shared/Neo.Build.Core/Models/Wallets/TestWalletModel.cs
  src/Shared/Neo.Build.Core/NeoBuildDefaults.cs
  src/Shared/Neo.Build.Core/NeoBuildSettings.cs
  tests/Neo.Build.Core.Tests/Factories/UT_FunctionFactory.cs
  tests/Neo.Build.Core.Tests/Factories/UT_RandomFactory.cs
  tests/Neo.Build.Core.Tests/Helpers/TestObjectHelper.cs
  tests/Neo.Build.Core.Tests/Models/Wallets/UT_TestWalletModel.cs
  tests/Neo.Build.Core.Tests/Wallets/UT_DevWallet.cs
Labels: Blocker, Waiting for Review, Neo Build
