Repository neo-project/neo, pull requests merged in 2025-08, with the labels that each got.

#4074 Optimize: merge `RpcMethod` and `RpcMethodWithParams`
  src/Plugins/RpcServer/RpcMethodWithParamsAttribute.cs
  src/Plugins/RpcServer/RpcServer.Blockchain.cs
  src/Plugins/RpcServer/RpcServer.Node.cs
  src/Plugins/RpcServer/RpcServer.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.cs
Labels: Ready to Merge

#4033 Add invokeabi command for simplified contract invocation
  src/Neo.CLI/CLI/MainService.Contracts.cs
  tests/Neo.CLI.Tests/Neo.CLI.Tests.csproj
  tests/Neo.CLI.Tests/UT_MainService_Contracts.cs
Labels: Ready to Merge

#4079 Implemented JsonRPC in WebSocketService - PART 4
  src/neo-build/Neo.Build.ToolSet/Net/RpcDispatcher.cs
  src/neo-build/Neo.Build.ToolSet/Services/WebSocketService.cs
Labels: Ready to Merge, Neo Build

#4104 Doc: Add doc for plugin RpcServer, Part-2
  docs/plugin-rpc-server.md
Labels: Waiting for Review

#4108 update packages
  benchmarks/Neo.Benchmarks/Neo.Benchmarks.csproj
  src/Neo.ConsoleService/Neo.ConsoleService.csproj
  src/Neo.Extensions/Neo.Extensions.csproj
  src/Neo.Json/Neo.Json.csproj
  src/Neo.VM/Neo.VM.csproj
  src/Neo/Neo.csproj
  src/Plugins/SQLiteWallet/SQLiteWallet.csproj
  tests/Directory.Build.props
  tests/Neo.Plugins.ApplicationLogs.Tests/UT_LogReader.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_ConsensusService.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Core.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Failures.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Integration.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_NormalFlow.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Performance.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Recovery.cs
  tests/Neo.Plugins.OracleService.Tests/E2E_Https.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Node.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Wallet.cs
  tests/Neo.UnitTests/Ledger/UT_Blockchain.cs
  tests/Neo.UnitTests/Network/P2P/UT_LocalNode.cs
  tests/Neo.UnitTests/Network/P2P/UT_RemoteNode.cs
  tests/Neo.UnitTests/UT_ProtocolSettings.cs
Labels: Ready to Merge

#4109 Fixed docker.yml
  .github/workflows/docker.yml
Labels: Waiting for Review, GitHub Workflow, Easy-to-Review

#4087 Added NEBuild Utilities Project - PART 5
  .gitignore
  neo.sln
  src/neo-build/Directory.Build.props
  src/neo-build/Neo.Build.Utilities.Core/BuildTasks/Neo.Build.Utilities.Core.props
  src/neo-build/Neo.Build.Utilities.Core/BuildTasks/Neo.Build.Utilities.Core.targets
  src/neo-build/Neo.Build.Utilities.Core/Neo.Build.Utilities.Core.csproj
  src/neo-build/Neo.Build.Utilities.Core/NeoBuildToolRunner.cs
  src/neo-build/Neo.Build.Utilities.Core/NeoWallet.cs
Labels: Waiting for Review, Neo Build

#4103 Optimize RPCClient code
  src/RpcClient/RpcClient.cs
Labels: Ready to Merge

#4112 UnitTests: use proper `Assert` methods
  tests/Neo.UnitTests/Builders/UT_SignerBuilder.cs
  tests/Neo.UnitTests/Builders/UT_TransactionAttributesBuilder.cs
  tests/Neo.UnitTests/Builders/UT_TransactionBuilder.cs
  tests/Neo.UnitTests/Builders/UT_WitnessConditionBuilder.cs
  tests/Neo.UnitTests/Cryptography/UT_Ed25519.cs
  tests/Neo.UnitTests/Cryptography/UT_MerkleTree.cs
  tests/Neo.UnitTests/IO/Caching/UT_Cache.cs
  tests/Neo.UnitTests/IO/Caching/UT_ECPointCache.cs
  tests/Neo.UnitTests/IO/Caching/UT_HashSetCache.cs
  tests/Neo.UnitTests/IO/Caching/UT_IndexedQueue.cs
  tests/Neo.UnitTests/IO/Caching/UT_KeyedCollectionSlim.cs
  tests/Neo.UnitTests/IO/Caching/UT_LRUCache.cs
  tests/Neo.UnitTests/IO/Caching/UT_RelayCache.cs
  tests/Neo.UnitTests/IO/UT_IOHelper.cs
  tests/Neo.UnitTests/IO/UT_MemoryReader.cs
  tests/Neo.UnitTests/Ledger/UT_MemoryPool.cs
  tests/Neo.UnitTests/Ledger/UT_PoolItem.cs
  tests/Neo.UnitTests/Ledger/UT_TrimmedBlock.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Block.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_ExtensiblePayload.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Header.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_InvPayload.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Signers.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Transaction.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_VersionPayload.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_WitnessCondition.cs
  tests/Neo.UnitTests/Network/P2P/UT_Message.cs
  tests/Neo.UnitTests/Network/P2P/UT_RemoteNode.cs
  tests/Neo.UnitTests/Network/P2P/UT_TaskSession.cs
  tests/Neo.UnitTests/Persistence/UT_DataCache.cs
  tests/Neo.UnitTests/Persistence/UT_MemorySnapshot.cs
  tests/Neo.UnitTests/Persistence/UT_MemoryStore.cs
  tests/Neo.UnitTests/Plugins/UT_Plugin.cs
  tests/Neo.UnitTests/SmartContract/Manifest/UT_ContractEventDescriptor.cs
  tests/Neo.UnitTests/SmartContract/Manifest/UT_ContractManifest.cs
  tests/Neo.UnitTests/SmartContract/Manifest/UT_WildCardContainer.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_ContractEventAttribute.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_CryptoLib.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NeoToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_Notary.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_RoleManagement.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_StdLib.cs
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngine.cs
  tests/Neo.UnitTests/SmartContract/UT_Contract.cs
  tests/Neo.UnitTests/SmartContract/UT_ContractParameter.cs
  tests/Neo.UnitTests/SmartContract/UT_ContractParameterContext.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
  tests/Neo.UnitTests/SmartContract/UT_JsonSerializer.cs
  tests/Neo.UnitTests/SmartContract/UT_Syscalls.cs
  tests/Neo.UnitTests/TestUtils.Transaction.cs
  tests/Neo.UnitTests/UT_Helper.cs
  tests/Neo.UnitTests/UT_ProtocolSettings.cs
  tests/Neo.UnitTests/UT_UInt256.cs
  tests/Neo.UnitTests/VM/UT_Helper.cs
  tests/Neo.UnitTests/Wallets/NEP6/UT_NEP6Contract.cs
Labels: Ready to Merge

#4107 Optimize: use explicitly typed parameters instead of JArray in `RpcMethod`
  src/Plugins/RpcServer/ParameterConverter.cs
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
  src/Plugins/RpcServer/RpcServer.Utilities.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Utilities.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Wallet.cs
Labels: Waiting for Review

#4105 Fix: unicode escape for cli input
  src/Neo.ConsoleService/CommandTokenizer.cs
  src/Neo.ConsoleService/ConsoleServiceBase.cs
  tests/Neo.ConsoleService.Tests/UT_CommandTokenizer.cs
Labels: Waiting for Review, Ready to Merge

#4114 Add some checks
  src/Neo/Extensions/IO/BinaryWriterExtensions.cs
  src/Neo/SmartContract/ApplicationEngine.Storage.cs
  src/Neo/SmartContract/ApplicationEngine.cs
Labels: Ready to Merge

#4113 Clean JsonSerializer
  src/Neo/SmartContract/JsonSerializer.cs
  tests/Neo.UnitTests/SmartContract/UT_JsonSerializer.cs
Labels: Ready to Merge

#4056 [`Add`] DebugApplicationEngine
  src/neo-build/Directory.Build.props
  src/neo-build/Neo.Build.Core/Attributes/ContractScriptHashAttribute.cs
  src/neo-build/Neo.Build.Core/Builders/BlockBuilder.cs
  src/neo-build/Neo.Build.Core/Extensions/ScriptBuilderExtensions.cs
  src/neo-build/Neo.Build.Core/Extensions/SmartContract/ApplicationEngineExtensions.cs
  src/neo-build/Neo.Build.Core/Factories/RandomNumberFactory.cs
  src/neo-build/Neo.Build.Core/Helpers/NeoBuildAttributeHelper.cs
  src/neo-build/Neo.Build.Core/Logging/DebugEventLog.cs
  src/neo-build/Neo.Build.Core/NeoBuildErrorCodes.Contracts.cs
  src/neo-build/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemContract.cs
  src/neo-build/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemCrypto.cs
  src/neo-build/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemIterator.cs
  src/neo-build/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemRuntime.cs
  src/neo-build/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemStorage.cs
  src/neo-build/Neo.Build.Core/SmartContract/ApplicationEngineBase.cs
  src/neo-build/Neo.Build.Core/SmartContract/DebugApplicationEngine.Common.cs
  src/neo-build/Neo.Build.Core/SmartContract/DebugApplicationEngine.cs
  src/neo-build/Neo.Build.Core/SmartContract/Debugger/Breakpoint.cs
  src/neo-build/Neo.Build.Core/SmartContract/Debugger/DebugCallSink.cs
  src/neo-build/Neo.Build.Core/SmartContract/Debugger/DebugStorage.cs
  src/neo-build/Neo.Build.Core/Wallets/DevWallet.cs
  src/neo-build/Neo.Build.ToolSet/Providers/NeoBuildConfigurationProvider.cs
  tests/Neo.Build.Core.Tests/Extensions/UT_ApplicationEngineExtensions.cs
  tests/Neo.Build.Core.Tests/Extensions/UT_ScriptBuilderExtensions.cs
  tests/Neo.Build.Core.Tests/Factories/UT_RandomFactory.cs
  tests/Neo.Build.Core.Tests/Helpers/SmartContract/UnitTestApplicationEngine.cs
  tests/Neo.Build.Core.Tests/Helpers/SmartContract/UnitTestApplicationEngineProvider.cs
  tests/Neo.Build.Core.Tests/Neo.Build.Core.Tests.csproj
  tests/Neo.Build.Core.Tests/SmartContract/UT_ApplicationEngineBase.cs
  tests/Neo.Build.Core.Tests/SmartContract/UT_DebugApplicationEngine.cs
  tests/Neo.Build.Core.Tests/Storage/UT_FasterDbSnapshot.cs
  tests/Neo.Build.Core.Tests/Storage/UT_FasterDbStore.cs
Labels: Waiting for Review, Neo Build

#4117 [`Add`] IComparable, Casting to UInt160 & UInt256
  src/Neo/UInt160.cs
  src/Neo/UInt256.cs
  tests/Neo.UnitTests/UT_UInt160.cs
  tests/Neo.UnitTests/UT_UInt256.cs
Labels: Ready to Merge, Core

#4119 Allow HF in syscalls
  src/Neo/SmartContract/ApplicationEngine.cs
  src/Neo/SmartContract/InteropDescriptor.cs
Labels: Blocker, Ready to Merge

#4122 UnitTests: Use proper 'Assert' methods after adding lots of new code.
  tests/Neo.ConsoleService.Tests/UT_CommandServiceBase.cs
  tests/Neo.ConsoleService.Tests/UT_CommandTokenizer.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Node.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Trie.cs
  tests/Neo.Extensions.Tests/Collections/UT_CollectionExtensions.cs
  tests/Neo.Extensions.Tests/Factories/UT_RandomNumberFactory.cs
  tests/Neo.Extensions.Tests/UT_ByteArrayComparer.cs
  tests/Neo.Json.UnitTests/UT_JArray.cs
  tests/Neo.Json.UnitTests/UT_OrderedDictionary.cs
  tests/Neo.Plugins.ApplicationLogs.Tests/UT_LogReader.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Core.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_MessageFlow.cs
  tests/Neo.Plugins.RestServer.Tests/RateLimitingIntegrationTests.cs
  tests/Neo.Plugins.RestServer.Tests/RestServerRateLimitingTests.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_Parameters.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcErrorHandling.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Node.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Utilities.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Wallet.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.cs
  tests/Neo.Plugins.Storage.Tests/StoreTest.cs
  tests/Neo.RpcClient.Tests/UT_TransactionManager.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Signers.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_WitnessCondition.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_WitnessRule.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_StdLib.cs
  tests/Neo.UnitTests/SmartContract/UT_JsonSerializer.cs
  tests/Neo.VM.Tests/Converters/ScriptConverter.cs
  tests/Neo.VM.Tests/UT_EvaluationStack.cs
  tests/Neo.VM.Tests/UT_ExecutionContext.cs
  tests/Neo.VM.Tests/UT_Slot.cs
Labels: Ready to Merge

#4121 [`Fixed`] Console Formatting & Wallet Extra
  src/neo-build/Neo.Build.Core/Models/Wallets/WalletModel.cs
  src/neo-build/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemContract.cs
  src/neo-build/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemCrypto.cs
  src/neo-build/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemIterator.cs
  src/neo-build/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemRuntime.cs
  src/neo-build/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemStorage.cs
  src/neo-build/Neo.Build.Core/SmartContract/ApplicationEngineBase.cs
  src/neo-build/Neo.Build.Core/SmartContract/Debugger/DebugCallSink.cs
  src/neo-build/Neo.Build.Core/SmartContract/TraceApplicationEngine.cs
  src/neo-build/Neo.Build.Core/Wallets/DevWallet.cs
  src/neo-build/Neo.Build.ToolSet/Commands/RunNodeCommand.cs
  src/neo-build/Neo.Build.ToolSet/Extensions/ConsoleExtensions.cs
  src/neo-build/Neo.Build.ToolSet/Extensions/HostBuilderExtensions.cs
  src/neo-build/Neo.Build.ToolSet/Extensions/LoggingExtensions.cs
  src/neo-build/Neo.Build.ToolSet/Logging/NeoBuildConsoleLogger.cs
  src/neo-build/Neo.Build.ToolSet/Plugins/LoggerPlugin.cs
  src/neo-build/Neo.Build.ToolSet/Providers/NeoBuildConsoleLoggerProvider.cs
  src/neo-build/Neo.Build.ToolSet/Providers/TraceApplicationEngineProvider.cs
  src/neo-build/Neo.Build.ToolSet/config.json
  tests/Neo.Build.Core.Tests/Helpers/TestNode.cs
  tests/Neo.Build.Core.Tests/Helpers/TestObjectHelper.cs
  tests/Neo.Build.Core.Tests/Wallets/UT_DevWallet.cs
Labels: Waiting for Review, Neo Build

#4120 Fix: avoid NullReferenceException when account not found
  src/Plugins/RpcServer/RpcError.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Wallet.cs
Labels: Ready to Merge

#4123 [`Add`] Protected for ApplicationEngine properties
  src/Neo/SmartContract/ApplicationEngine.cs
Labels: Waiting for Review, Easy-to-Review

#4128 Hardfork: add Gorgon hardfork
  src/Neo/Hardfork.cs
  tests/Neo.UnitTests/UT_ProtocolSettings.cs
Labels: Hardfork, Easy-to-Review

#4149 Fix: out of bound exception in TestAppend unit tests
  tests/Neo.UnitTests/Cryptography/UT_Murmur128.cs
  tests/Neo.UnitTests/Cryptography/UT_Murmur32.cs
Labels: Ready to Merge

#4131 Unify `HashSetExtensions`
  src/Neo.Extensions/Collections/HashSetExtensions.cs
  src/Neo.IO/Caching/HashSetCache.cs
  src/Neo/Extensions/HashSetExtensions.cs
  src/Neo/Network/P2P/TaskManager.cs
  tests/Neo.UnitTests/IO/Caching/UT_HashSetCache.cs
Labels: Ready to Merge

#4148 Remove: unnecessary json rewrite for Block and Tx in RpcMethod.
  src/Plugins/RpcServer/RpcServer.Blockchain.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
  src/Plugins/RpcServer/Utility.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
Labels: Ready to Merge, Easy-to-Review

#4151 Improve StringExtensions exception messages
  src/Neo.Extensions/StringExtensions.cs
  tests/Neo.Extensions.Tests/UT_StringExtensions.cs
Labels: Ready to Merge

#4154 Update coverallsapp Version
  .github/workflows/main.yml
Labels: Waiting for Review
