Repository neo-project/neo, pull requests merged in 2025-10, with the labels that each got.

#4184 Replaced `Random` with `RandomNumberFactory`
  src/Neo.Extensions/Factories/RandomNumberFactory.cs
  src/Neo/Network/P2P/LocalNode.cs
  src/Neo/Network/P2P/Payloads/PingPayload.cs
  src/Neo/Network/P2P/Peer.cs
  src/Neo/Network/P2P/RemoteNode.ProtocolHandler.cs
  src/Neo/Wallets/Wallet.cs
  src/RpcClient/TransactionManagerFactory.cs
  tests/Neo.Extensions.Tests/Factories/UT_RandomNumberFactory.cs
  tests/Neo.Extensions.Tests/UT_BigIntegerExtensions.cs
  tests/Neo.Plugins.ApplicationLogs.Tests/UT_LogStorageStore.cs
  tests/Neo.UnitTests/Builders/UT_TransactionBuilder.cs
  tests/Neo.UnitTests/Cryptography/UT_Murmur128.cs
  tests/Neo.UnitTests/Cryptography/UT_Murmur32.cs
  tests/Neo.UnitTests/Ledger/UT_MemoryPool.cs
  tests/Neo.UnitTests/Ledger/UT_TransactionState.cs
  tests/Neo.UnitTests/Ledger/UT_TransactionVerificationContext.cs
  tests/Neo.UnitTests/SmartContract/Manifest/UT_ContractGroup.cs
  tests/Neo.UnitTests/SmartContract/Manifest/UT_ContractPermission.cs
  tests/Neo.UnitTests/SmartContract/UT_ContractParameter.cs
  tests/Neo.UnitTests/SmartContract/UT_Helper.cs
  tests/Neo.UnitTests/TestUtils.Transaction.cs
  tests/Neo.UnitTests/TestWalletAccount.cs
  tests/Neo.UnitTests/UT_UInt160.cs
  tests/Neo.UnitTests/UT_UInt256.cs
  tests/Neo.UnitTests/Wallets/NEP6/UT_NEP6Wallet.cs
  tests/Neo.UnitTests/Wallets/UT_KeyPair.cs
  tests/Neo.VM.Tests/Helpers/RandomHelper.cs
  tests/Neo.VM.Tests/UT_ScriptBuilder.cs
Labels: Waiting for Review

#4210 Fix ut CheckNextBytes
  tests/Neo.Extensions.Tests/Factories/UT_RandomNumberFactory.cs
Labels: Ready to Merge

#4207 Map constructor
  src/Neo.VM/Types/Map.cs
  tests/Neo.VM.Tests/UT_StackItem.cs
Labels: Blocker, Ready to Merge, Easy-to-Review, Core

#4206 Create constructor for JObject
  src/Neo.Json/JObject.cs
  tests/Neo.Json.UnitTests/UT_JObject.cs
Labels: Blocker, Waiting for Review
