Repository neo-project/neo, pull requests merged in 2025-09, with the labels that each got.

#4147 [`Add`] GetBlockedAccounts to Policy Contract
  src/Neo/SmartContract/Native/PolicyContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_PolicyContract.cs
Labels: Ready to Merge, Hardfork, Core

#4158 Remove: benchmarks in unit test
  tests/Neo.UnitTests/UT_UIntBenchmarks.cs
Labels: Ready to Merge, Easy-to-Review

#4159 Remove: `AllowUnsafeBlocks` if no unsafe blocks
  benchmarks/Neo.Benchmarks/Neo.Benchmarks.csproj
  src/Neo.Cryptography.MPTTrie/Neo.Cryptography.MPTTrie.csproj
  src/Neo.IO/Neo.IO.csproj
  src/Neo.VM/Neo.VM.csproj
  src/Plugins/LevelDBStore/LevelDBStore.csproj
  src/Plugins/StateService/StateService.csproj
  tests/Neo.CLI.Tests/Neo.CLI.Tests.csproj
  tests/Neo.Plugins.RpcServer.Tests/Neo.Plugins.RpcServer.Tests.csproj
  tests/Neo.UnitTests/Neo.UnitTests.csproj
  tests/Neo.VM.Tests/Neo.VM.Tests.csproj
Labels: Ready to Merge, Easy-to-Review

#4157 Add: parameter nullable checking for `RpcMethod`
  src/Plugins/RpcServer/RpcServer.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.cs
Labels: Ready to Merge

#4160 Add: unit tests for SQLiteWallet
  neo.sln
  src/Plugins/SQLiteWallet/Account.cs
  src/Plugins/SQLiteWallet/Address.cs
  src/Plugins/SQLiteWallet/Contract.cs
  src/Plugins/SQLiteWallet/Key.cs
  src/Plugins/SQLiteWallet/SQLiteWallet.cs
  src/Plugins/SQLiteWallet/SQLiteWallet.csproj
  src/Plugins/SQLiteWallet/SQLiteWalletAccount.cs
  src/Plugins/SQLiteWallet/VerificationContract.cs
  src/Plugins/SQLiteWallet/WalletDataContext.cs
  tests/Neo.Plugins.SQLiteWallet.Tests/Neo.Plugins.SQLiteWallet.Tests.csproj
  tests/Neo.Plugins.SQLiteWallet.Tests/UT_SQLiteWallet.cs
  tests/Neo.Plugins.SQLiteWallet.Tests/UT_SQLiteWalletFactory.cs
  tests/Neo.Plugins.SQLiteWallet.Tests/UT_VerificationContract.cs
  tests/Neo.Plugins.SQLiteWallet.Tests/UT_WalletDataContext.cs
Labels: Ready to Merge

#4182 Add: run without console input support
  src/Neo.CLI/CLI/CommandLineOption.cs
  src/Neo.CLI/CLI/MainService.CommandLine.cs
  src/Neo.ConsoleService/ConsoleServiceBase.cs
Labels: Ready to Merge

#4192 Fix: `Settings` cannot load `config.json` if neo-cli doesn't exsit in current directory
  src/Neo.CLI/Settings.cs
Labels: Waiting for Review

#4197 Use Property intead of Method
  src/Neo.ConsoleService/ConsoleHelper.cs
  src/Neo/Ledger/MemoryPool.cs
  src/Plugins/OracleService/OracleSettings.cs
  src/Plugins/RestServer/RestWebServer.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
  src/Plugins/RpcServer/RpcServer.cs
  tests/Neo.Json.UnitTests/UT_JArray.cs
  tests/Neo.Plugins.ApplicationLogs.Tests/UT_LogReader.cs
  tests/Neo.Plugins.RestServer.Tests/ControllerRateLimitingTests.cs
  tests/Neo.Plugins.RestServer.Tests/RateLimitingIntegrationTests.cs
  tests/Neo.Plugins.RestServer.Tests/TestUtility.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_Notary.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.NEO.cs
Labels: Ready to Merge
