Repository neo-project/neo, pull requests merged in 2025-07, with the labels that each got.

#4040 [`style`] Style neo system
  .editorconfig
  src/Neo.Cryptography.MPTTrie/GlobalSuppressions.cs
  src/Neo/Ledger/Blockchain.cs
  src/Neo/NeoSystem.cs
Labels: Ready to Merge

#4036 Refactor MainService.Vote class
  src/Neo.CLI/CLI/MainService.Vote.cs
Labels: Waiting for Review

#4049 Doc: add document for plugin SignClient
  docs/plugin-secure-sign-guide.md
Labels: Ready to Merge, Easy-to-Review

#4046 [`Move`] RcpClient Files To Proper Directory
  docs/RpcClient/API_REFERENCE.md
  neo.sln
  src/RpcClient/ContractClient.cs
  src/RpcClient/Models/RpcAccount.cs
  src/RpcClient/Models/RpcApplicationLog.cs
  src/RpcClient/Models/RpcBlock.cs
  src/RpcClient/Models/RpcBlockHeader.cs
  src/RpcClient/Models/RpcContractState.cs
  src/RpcClient/Models/RpcFoundStates.cs
  src/RpcClient/Models/RpcInvokeResult.cs
  src/RpcClient/Models/RpcMethodToken.cs
  src/RpcClient/Models/RpcNefFile.cs
  src/RpcClient/Models/RpcNep17Balances.cs
  src/RpcClient/Models/RpcNep17TokenInfo.cs
  src/RpcClient/Models/RpcNep17Transfers.cs
  src/RpcClient/Models/RpcPeers.cs
  src/RpcClient/Models/RpcPlugin.cs
  src/RpcClient/Models/RpcRawMemPool.cs
  src/RpcClient/Models/RpcRequest.cs
  src/RpcClient/Models/RpcResponse.cs
  src/RpcClient/Models/RpcStateRoot.cs
  src/RpcClient/Models/RpcTransaction.cs
  src/RpcClient/Models/RpcTransferOut.cs
  src/RpcClient/Models/RpcUnclaimedGas.cs
  src/RpcClient/Models/RpcValidateAddressResult.cs
  src/RpcClient/Models/RpcValidator.cs
  src/RpcClient/Models/RpcVersion.cs
  src/RpcClient/Nep17API.cs
  src/RpcClient/PolicyAPI.cs
  src/RpcClient/Properties/AssemblyInfo.cs
  src/RpcClient/README.md
  src/RpcClient/RpcClient.cs
  src/RpcClient/RpcClient.csproj
  src/RpcClient/RpcException.cs
  src/RpcClient/StateAPI.cs
  src/RpcClient/TransactionManager.cs
  src/RpcClient/TransactionManagerFactory.cs
  src/RpcClient/Utility.cs
  src/RpcClient/WalletAPI.cs
  tests/Neo.Network.RPC.RpcClient.Tests/Neo.Network.RPC.Tests.csproj
  tests/Neo.Network.RPC.RpcClient.Tests/RpcTestCases.json
  tests/Neo.Network.RPC.RpcClient.Tests/TestUtils.cs
  tests/Neo.Network.RPC.RpcClient.Tests/UT_ContractClient.cs
  tests/Neo.Network.RPC.RpcClient.Tests/UT_Nep17API.cs
  tests/Neo.Network.RPC.RpcClient.Tests/UT_PolicyAPI.cs
  tests/Neo.Network.RPC.RpcClient.Tests/UT_RpcClient.cs
  tests/Neo.Network.RPC.RpcClient.Tests/UT_RpcModels.cs
  tests/Neo.Network.RPC.RpcClient.Tests/UT_TransactionManager.cs
  tests/Neo.Network.RPC.RpcClient.Tests/UT_Utility.cs
  tests/Neo.Network.RPC.RpcClient.Tests/UT_WalletAPI.cs
Labels: Ready to Merge

#4044 Optimize: no escaped string for command line input
  src/Neo.ConsoleService/CommandToken.cs
  src/Neo.ConsoleService/CommandTokenizer.cs
  tests/Neo.ConsoleService.Tests/CommandTokenizerTest.cs
Labels: Ready to Merge

#4051 Fix: tx.ToJson no 'cosigners' field
  benchmarks/Neo.Json.Benchmarks/Data/RpcTestCases.json
  src/Plugins/RpcServer/RpcServer.Wallet.cs
  tests/Neo.Network.RPC.RpcClient.Tests/RpcTestCases.json
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Transaction.cs
Labels: Ready to Merge

#4057 [`Add`] More Node Configurations
  src/neo-build/Neo.Build.Core/Factories/FunctionFactory.cs
  src/neo-build/Neo.Build.Core/Models/NodeConfigurationModel.cs
  src/neo-build/Neo.Build.Core/Models/ProtocolOptionsModel.cs
  src/neo-build/Neo.Build.Core/Models/Wallets/ContractModel.cs
  src/neo-build/Neo.Build.Core/Models/Wallets/TestWalletModel.cs
  src/neo-build/Neo.Build.ToolSet/Commands/ProgramRootCommand.cs
  tests/Neo.Build.Core.Tests/Helpers/TestNode.cs
  tests/Neo.Build.Core.Tests/Helpers/TestObjectHelper.cs
  tests/Neo.Build.Core.Tests/Models/UT_ProtocolOptionsModel.cs
  tests/Neo.Build.Core.Tests/Models/Wallets/UT_TestWalletModel.cs
Labels: Neo Build

#4059 [`Add`] DBFT Configuation Part 1
  src/neo-build/Neo.Build.ToolSet/Commands/ProgramRootCommand.cs
  src/neo-build/Neo.Build.ToolSet/Configuration/DBFTConfigurationNames.cs
  src/neo-build/Neo.Build.ToolSet/Configuration/ProtocolOptionsConfigurationNames.cs
  src/neo-build/Neo.Build.ToolSet/Extensions/HostBuilderExtensions.cs
  src/neo-build/Neo.Build.ToolSet/Options/DBFTOptions.cs
  src/neo-build/Neo.Build.ToolSet/Options/ProtocolOptions.cs
  src/neo-build/Neo.Build.ToolSet/Program.cs
  src/neo-build/Neo.Build.ToolSet/Providers/NeoBuildConfigurationProvider.cs
  tests/Neo.Build.Core.Tests/Helpers/TestObjectHelper.cs
Labels: Waiting for Review, Neo Build

#4062 Renamed and Fix Properties with plugins
  src/Neo/Plugins/IPluginSettings.cs
  src/Neo/Plugins/PluginSettings.cs
  src/Plugins/ApplicationLogs/LogReader.cs
  src/Plugins/ApplicationLogs/Settings.cs
  src/Plugins/ApplicationLogs/Store/LogStorageStore.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.cs
  src/Plugins/DBFTPlugin/DbftSettings.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/OracleService/OracleSettings.cs
  src/Plugins/OracleService/Protocols/OracleHttpsProtocol.cs
  src/Plugins/OracleService/Protocols/OracleNeoFSProtocol.cs
  src/Plugins/RpcServer/RcpServerSettings.cs
  src/Plugins/RpcServer/RpcServer.cs
  src/Plugins/RpcServer/RpcServerPlugin.cs
  src/Plugins/SignClient/SignClient.cs
  src/Plugins/SignClient/SignSettings.cs
  src/Plugins/StateService/StatePlugin.cs
  src/Plugins/StateService/StateServiceSettings.cs
  src/Plugins/StateService/Storage/StateSnapshot.cs
  src/Plugins/StorageDumper/StorageDumper.cs
  src/Plugins/StorageDumper/StorageSettings.cs
  tests/Neo.Plugins.ApplicationLogs.Tests/UT_LogReader.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/MockBlockchain.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Failures.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_MessageFlow.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_NormalFlow.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Performance.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Recovery.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcErrorHandling.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Node.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.cs
  tests/Neo.Plugins.SignClient.Tests/UT_SignClient.cs
  tests/Neo.Plugins.SignClient.Tests/UT_Vsock.cs
  tests/Neo.UnitTests/Plugins/TestPlugin.cs
Labels: Ready to Merge

#4063 [`Add`] Wallet Exceptions
  src/neo-build/Neo.Build.Core/Exceptions/Wallet/NeoBuildWalletAccountLockedException.cs
  src/neo-build/Neo.Build.Core/Exceptions/Wallet/NeoBuildWalletAccountNotFoundException.cs
  src/neo-build/Neo.Build.Core/Exceptions/Wallet/NeoBuildWalletInvalidFileFormatException.cs
  src/neo-build/Neo.Build.Core/Exceptions/Wallet/NeoBuildWalletInvalidPasswordException.cs
  src/neo-build/Neo.Build.Core/Exceptions/Wallet/NeoBuildWalletInvalidVersionException.cs
  src/neo-build/Neo.Build.Core/Exceptions/Wallet/NeoBuildWalletPrivateKeyNotFoundException.cs
  src/neo-build/Neo.Build.Core/NeoBuildErrorCodes.Wallet.cs
  tests/Neo.Build.Core.Tests/Exceptions/Wallet/UT_NeoBuildWalletAccountLockedException.cs
  tests/Neo.Build.Core.Tests/Exceptions/Wallet/UT_NeoBuildWalletAccountNotFoundException.cs
  tests/Neo.Build.Core.Tests/Exceptions/Wallet/UT_NeoBuildWalletInvalidFileFormatException.cs
  tests/Neo.Build.Core.Tests/Exceptions/Wallet/UT_NeoBuildWalletInvalidPasswordException.cs
  tests/Neo.Build.Core.Tests/Exceptions/Wallet/UT_NeoBuildWalletInvalidVersionException.cs
  tests/Neo.Build.Core.Tests/Exceptions/Wallet/UT_NeoBuildWalletPrivateKeyNotFoundException.cs
Labels: Waiting for Review, Neo Build

#4050 [`Add`] Indexer to EvaluationStack
  src/Neo.VM/EvaluationStack.cs
  tests/Neo.VM.Tests/UT_EvaluationStack.cs
Labels: Ready to Merge, Easy-to-Review

#4054 Comments: Add detailed description for rpc method in plugin `RpcServer`
  src/Plugins/RpcServer/RpcMethodAttribute.cs
  src/Plugins/RpcServer/RpcMethodWithParamsAttribute.cs
  src/Plugins/RpcServer/RpcServer.Blockchain.cs
  src/Plugins/RpcServer/RpcServer.Node.cs
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
  src/Plugins/RpcServer/RpcServer.Utilities.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
Labels: Ready to Merge, Easy-to-Review

#4038 [`Add`] `TryCatch` & `TryCatchThrow` Extensions
  src/Neo.Extensions/Exceptions/TryCatchExtensions.cs
  src/Neo/Network/P2P/Connection.cs
  src/Neo/Network/P2P/LocalNode.cs
  tests/Neo.Extensions.Tests/Exceptions/UT_TryCatchExceptions.cs
Labels: Ready to Merge

#4047 Add: input cli command line with `--argument-name argument-value`
  src/Neo.ConsoleService/CommandToken.cs
  src/Neo.ConsoleService/ConsoleServiceBase.cs
  tests/Neo.ConsoleService.Tests/UT_CommandServiceBase.cs
  tests/Neo.ConsoleService.Tests/UT_CommandTokenizer.cs
Labels: Ready to Merge

#4064 [`Add`] NeoSystem - Part 2
  docs/neo-build/config.md
  src/neo-build/Neo.Build.Core/Extensions/WalletExtensions.cs
  src/neo-build/Neo.Build.Core/Factories/FunctionFactory.cs
  src/neo-build/Neo.Build.Core/Models/Wallets/WalletAccountModel.cs
  src/neo-build/Neo.Build.Core/Models/Wallets/WalletModel.cs
  src/neo-build/Neo.Build.Core/Neo.Build.Core.csproj
  src/neo-build/Neo.Build.Core/Providers/Storage/FasterDbStoreProvider.cs
  src/neo-build/Neo.Build.Core/Storage/FasterDbStore.cs
  src/neo-build/Neo.Build.Core/Storage/LocalStorageDevice.cs
  src/neo-build/Neo.Build.Core/Wallets/DevWallet.cs
  src/neo-build/Neo.Build.Core/Wallets/DevWalletAccount.cs
  src/neo-build/Neo.Build.ToolSet/CommandLineStrings.cs
  src/neo-build/Neo.Build.ToolSet/Commands/ProgramRootCommand.cs
  src/neo-build/Neo.Build.ToolSet/Commands/RunNodeCommand.cs
  src/neo-build/Neo.Build.ToolSet/Configuration/ApplicationEngineConfigurationNames.cs
  src/neo-build/Neo.Build.ToolSet/Configuration/INeoConfigurationOptions.cs
  src/neo-build/Neo.Build.ToolSet/Configuration/NeoConfigurationOptions.cs
  src/neo-build/Neo.Build.ToolSet/Configuration/NeoSystemConfigurationNames.cs
  src/neo-build/Neo.Build.ToolSet/Extensions/HostBuilderExtensions.cs
  src/neo-build/Neo.Build.ToolSet/Extensions/HostEnvironmentExtensions.cs
  src/neo-build/Neo.Build.ToolSet/Neo.Build.ToolSet.csproj
  src/neo-build/Neo.Build.ToolSet/NeoHostingEnvironments.cs
  src/neo-build/Neo.Build.ToolSet/Options/ApplicationEngineOptions.cs
  src/neo-build/Neo.Build.ToolSet/Options/DBFTOptions.cs
  src/neo-build/Neo.Build.ToolSet/Options/NeoSystemOptions.cs
  src/neo-build/Neo.Build.ToolSet/Options/ProtocolOptions.cs
  src/neo-build/Neo.Build.ToolSet/Plugins/LoggerPlugin.cs
  src/neo-build/Neo.Build.ToolSet/Program.cs
  src/neo-build/Neo.Build.ToolSet/Providers/NeoBuildConfigurationProvider.cs
  src/neo-build/Neo.Build.ToolSet/wallet1.json
  tests/Neo.Build.Core.Tests/Factories/UT_FunctionFactory.cs
  tests/Neo.Build.Core.Tests/Helpers/TestNode.cs
  tests/Neo.Build.Core.Tests/Helpers/TestObjectHelper.cs
  tests/Neo.Build.Core.Tests/Models/Wallets/UT_WalletModel.cs
  tests/Neo.Build.Core.Tests/Storage/UT_FasterDbSnapshot.cs
  tests/Neo.Build.Core.Tests/Storage/UT_FasterDbStore.cs
Labels: Waiting for Review, Neo Build

#4067 Optimize: more detailed info for `help` command
  src/Neo.ConsoleService/ConsoleServiceBase.cs
Labels: Waiting for Review

#4069 [`Add`] DevWallet Extra Methods
  src/neo-build/Neo.Build.Core/Helpers/AccountHelper.cs
  src/neo-build/Neo.Build.Core/Models/Wallets/AccountBalanceModel.cs
  src/neo-build/Neo.Build.Core/Wallets/DevWallet.cs
  src/neo-build/Neo.Build.ToolSet/Commands/RunNodeCommand.cs
  tests/Neo.Build.Core.Tests/Helpers/UT_AccountHelper.cs
  tests/Neo.Build.Core.Tests/Wallets/UT_DevWallet.cs
Labels: Waiting for Review, Neo Build

#4071 [`Fix`] Async Ask Method
  tests/Neo.Plugins.DBFTPlugin.Tests/MockBlockchain.cs
  tests/Neo.Plugins.OracleService.Tests/E2E_Https.cs
  tests/Neo.Plugins.OracleService.Tests/TestBlockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/TestBlockchain.cs
  tests/Neo.UnitTests/TestBlockchain.cs
Labels: Ready to Merge, Easy-to-Review

#4048 Move `install sc` out of `ConsoleServiceBase.Run`
  src/Neo.CLI/CLI/MainService.Wallet.cs
  src/Neo.ConsoleService/ConsoleHelper.cs
  src/Neo.ConsoleService/ConsoleServiceBase.cs
Labels: Ready to Merge, Easy-to-Review

#3987 [`Add`] `RandomNumberFactory` Class
  src/Neo.Extensions/BigIntegerExtensions.cs
  src/Neo.Extensions/Factories/RandomNumberFactory.cs
  src/Neo.Extensions/RandomExtensions.cs
  src/Neo/Cryptography/ECC/ECFieldElement.cs
  tests/Neo.Extensions.Tests/Factories/UT_RandomNumberFactory.cs
  tests/Neo.Extensions.Tests/UT_RandomExtensions.cs
  tests/Neo.UnitTests/Ledger/UT_MemoryPool.cs
  tests/Neo.UnitTests/UT_Helper.cs
Labels: Ready to Merge

#3978 [UT] - Add unit tests in NeoSystem
  tests/Neo.UnitTests/SmartContract/Native/UT_RoleManagement.cs
  tests/Neo.UnitTests/UT_NeoSystem.cs
Labels: Ready to Merge

#4082 Add Scan for Vulnerable Dependencies
  .github/workflows/main.yml
Labels: Ready to Merge, GitHub Workflow

#4068 Doc: Add doc for plugin RpcServer
  docs/plugin-rpc-server.md
Labels: Ready to Merge

#4089 Fix: no handling if `ContractNameOrHashOrId` is a native contract name
  docs/plugin-rpc-server.md
  src/Plugins/RpcServer/Model/ContractNameOrHashOrId.cs
  src/Plugins/RpcServer/RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
Labels: Ready to Merge

#4085 Optimize: More parameter type support for `RpcMethod` with params
  src/Neo/SmartContract/ContractParameter.cs
  src/Plugins/RpcServer/Model/Address.cs
  src/Plugins/RpcServer/Model/SignersAndWitnesses.cs
  src/Plugins/RpcServer/ParameterConverter.cs
  src/Plugins/RpcServer/RpcMethodAttribute.cs
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
  src/Plugins/RpcServer/RpcServer.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_Parameters.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Wallet.cs
Labels: Ready to Merge

#4073 Add `Create Wallet` Command - PART 2
  src/neo-build/Neo.Build.Core/Tokens/Nep17Token.cs
  src/neo-build/Neo.Build.Core/Tokens/TokenBase.cs
  src/neo-build/Neo.Build.Core/Tokens/TokenMethodNames.cs
  src/neo-build/Neo.Build.Core/Wallets/DevWallet.cs
  src/neo-build/Neo.Build.ToolSet/Commands/CreateCommand.cs
  src/neo-build/Neo.Build.ToolSet/Commands/CreateWalletSubCommand.cs
  src/neo-build/Neo.Build.ToolSet/Commands/ProgramRootCommand.cs
  src/neo-build/Neo.Build.ToolSet/Commands/RunNodeCommand.cs
  src/neo-build/Neo.Build.ToolSet/FileNameDefaults.cs
  src/neo-build/Neo.Build.ToolSet/Neo.Build.ToolSet.csproj
  src/neo-build/Neo.Build.ToolSet/Program.cs
  src/neo-build/Neo.Build.ToolSet/wallet1.json
  tests/Neo.Build.Core.Tests/Tokens/UT_Nep17Token.cs
  tests/Neo.Build.Core.Tests/Wallets/UT_DevWallet.cs
Labels: Waiting for Review, Neo Build

#4095 UT - Add test cases for OnCommand
  src/Neo.ConsoleService/ConsoleServiceBase.cs
  tests/Neo.ConsoleService.Tests/UT_CommandServiceBase.cs
Labels: Ready to Merge, Easy-to-Review

#4078 Implementing WebSocket and JSONRPC - PART 3
  src/neo-build/Neo.Build.Core/Models/JsonRpcError.cs
  src/neo-build/Neo.Build.Core/Models/JsonRpcRequest.cs
  src/neo-build/Neo.Build.Core/Models/JsonRpcResponse.cs
  src/neo-build/Neo.Build.ToolSet/Commands/RunNodeCommand.cs
  src/neo-build/Neo.Build.ToolSet/Extensions/HostBuilderExtensions.cs
  src/neo-build/Neo.Build.ToolSet/Neo.Build.ToolSet.csproj
  src/neo-build/Neo.Build.ToolSet/Services/WebSocketService.cs
Labels: Waiting for Review, Neo Build

#4072 [`Add`] NEP17 Token - PART 1
  src/neo-build/Neo.Build.Core/Wallets/DevWallet.cs
Labels: Waiting for Review, Easy-to-Review, Neo Build
