Repository neo-project/neo, pull requests merged in 2025-03, with the labels that each got.

#3715 [`Maintenance`] Project File Normalization
  .github/workflows/nuget.yml
  .gitignore
  nuget.config
  pkgs/.gitkeep
  src/Directory.Build.props
  src/Plugins/ApplicationLogs/ApplicationLogs.csproj
  src/Plugins/DBFTPlugin/DBFTPlugin.csproj
  src/Plugins/Directory.Build.props
  src/Plugins/LevelDBStore/LevelDBStore.csproj
  src/Plugins/MPTTrie/MPTTrie.csproj
  src/Plugins/OracleService/OracleService.csproj
  src/Plugins/RocksDBStore/RocksDBStore.csproj
  src/Plugins/RpcClient/RpcClient.csproj
  src/Plugins/RpcServer/RpcServer.csproj
  src/Plugins/SQLiteWallet/SQLiteWallet.csproj
  src/Plugins/StateService/StateService.csproj
  src/Plugins/StorageDumper/StorageDumper.csproj
  src/Plugins/TokensTracker/TokensTracker.csproj
Labels: Ready to Merge

#3175 Implement NotaryAssisted transaction attribute
  src/Neo.CLI/CLI/MainService.Blockchain.cs
  src/Neo/Network/P2P/Payloads/NotaryAssisted.cs
  src/Neo/Network/P2P/Payloads/Transaction.cs
  src/Neo/Network/P2P/Payloads/TransactionAttributeType.cs
  src/Neo/SmartContract/Native/GasToken.cs
  src/Neo/SmartContract/Native/PolicyContract.cs
  src/Plugins/RpcClient/Utility.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_NotaryAssisted.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_GasToken.cs
Labels: Waiting for Review, Ready to Merge

#3548 SmartContract: restrict the number of allowed notifications
  src/Neo/SmartContract/ApplicationEngine.Runtime.cs
Labels: Bug, Ready to Merge, Hardfork

#3739 Remove ChangeSet from `StoreView`
  src/Neo/NeoSystem.cs
  src/Neo/Persistence/ClonedCache.cs
  src/Neo/Persistence/DataCache.cs
  src/Neo/Persistence/StoreCache.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Wallet.cs
  tests/Neo.UnitTests/Persistence/UT_CloneCache.cs
  tests/Neo.UnitTests/Persistence/UT_DataCache.cs
  tests/Neo.UnitTests/Persistence/UT_MemoryStore.cs
  tests/Neo.UnitTests/Persistence/UT_ReadOnlyStore.cs
Labels: Blocker, Waiting for Review, Ready to Merge

#3797 Avoid serialization issues
  src/Neo/Ledger/Blockchain.cs
  tests/Neo.UnitTests/Ledger/UT_Blockchain.cs
Labels: Bug, Critical, Ready to Merge

#3804 Fix rpc issue
  src/Neo/SmartContract/Helper.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Transaction.cs
Labels: Bug, Critical, Ready to Merge

#3805 Transaction: ensure standard witness scripts are properly verified
  src/Neo/Network/P2P/Payloads/Transaction.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Transaction.cs
Labels: Bug, Ready to Merge

#3787 [`Add`] Hosting Environment Toolset
  src/Shared/Neo.Build.ToolSet/CommandLineStrings.cs
  src/Shared/Neo.Build.ToolSet/Commands/ProgramRootCommand.cs
  src/Shared/Neo.Build.ToolSet/Configuration/NeoBuildConfigurationSource.cs
  src/Shared/Neo.Build.ToolSet/ConfigurationNames.cs
  src/Shared/Neo.Build.ToolSet/Extensions/ConfigurationBuilderExtensions.cs
  src/Shared/Neo.Build.ToolSet/Extensions/ConsoleExtensions.cs
  src/Shared/Neo.Build.ToolSet/Extensions/HostBuilderExtensions.cs
  src/Shared/Neo.Build.ToolSet/Extensions/HostEnvironmentExtensions.cs
  src/Shared/Neo.Build.ToolSet/HostingEnvironments.cs
  src/Shared/Neo.Build.ToolSet/Program.cs
  src/Shared/Neo.Build.ToolSet/Providers/NeoBuildConfigurationProvider.cs
Labels: Waiting for Review, Neo Build

#3809 Change <TargetFrameworks> to <TargetFramework> for Plugin projects
  src/Plugins/ApplicationLogs/ApplicationLogs.csproj
  src/Plugins/DBFTPlugin/DBFTPlugin.csproj
  src/Plugins/LevelDBStore/LevelDBStore.csproj
  src/Plugins/MPTTrie/MPTTrie.csproj
  src/Plugins/OracleService/OracleService.csproj
  src/Plugins/RocksDBStore/RocksDBStore.csproj
  src/Plugins/RpcClient/RpcClient.csproj
  src/Plugins/SQLiteWallet/SQLiteWallet.csproj
  src/Plugins/StateService/StateService.csproj
  src/Plugins/StorageDumper/StorageDumper.csproj
  src/Plugins/TokensTracker/TokensTracker.csproj
Labels: Ready to Merge

#3800 Add `Serialize(Span)` method to `ISerializableSpan`
  src/Neo.IO/ISerializableSpan.cs
  src/Neo/Cryptography/MerkleTree.cs
  src/Neo/SmartContract/StorageKey.cs
  src/Neo/UInt160.cs
  src/Neo/Wallets/Helper.cs
  tests/Neo.UnitTests/UT_UInt160.cs
  tests/Neo.UnitTests/UT_UInt256.cs
Labels: Ready to Merge

#3813 [`Fix`]: some typos
  benchmarks/Neo.Benchmarks/Program.cs
  benchmarks/Neo.Extensions.Benchmarks/Program.cs
  benchmarks/Neo.Json.Benchmarks/Program.cs
  benchmarks/Neo.VM.Benchmarks/Program.cs
  tests/Neo.Json.UnitTests/UT_JString.cs
Labels: Ready to Merge

#3796 [`Add`] Logging to ApplicationEngineBase
  src/Shared/Neo.Build.Core/Logging/VMEventLog.cs
  src/Shared/Neo.Build.Core/NeoBuildErrorCodes.General.cs
  src/Shared/Neo.Build.Core/NeoBuildErrorCodes.Wallet.cs
  src/Shared/Neo.Build.Core/NeoBuildErrorCodes.cs
  src/Shared/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemContract.cs
  src/Shared/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemCrypto.cs
  src/Shared/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemIterator.cs
  src/Shared/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemRuntime.cs
  src/Shared/Neo.Build.Core/SmartContract/ApplicationEngineBase.SystemStorage.cs
  src/Shared/Neo.Build.Core/SmartContract/ApplicationEngineBase.cs
Labels: Blocked, Waiting for Review, Neo Build

#3807 [`Add`]: `ISigner` interface
  src/Neo/Sign/ISigner.cs
  src/Neo/Sign/SignException.cs
  src/Neo/Wallets/Wallet.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.MakePayload.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.cs
  src/Plugins/OracleService/OracleService.cs
  tests/Neo.UnitTests/Wallets/UT_Wallet.cs
Labels: Ready to Merge

#3814 [`Add`] Toolset Configuration & Updated Random Factory
  src/Shared/Neo.Build.Core/Factories/RandomFactory.cs
  src/Shared/Neo.Build.ToolSet/Extensions/ConfigurationBuilderExtensions.cs
  src/Shared/Neo.Build.ToolSet/Extensions/HostBuilderExtensions.cs
  src/Shared/Neo.Build.ToolSet/Neo.Build.ToolSet.csproj
  src/Shared/Neo.Build.ToolSet/ProgramDefaults.cs
  src/Shared/Neo.Build.ToolSet/Providers/NeoBuildConfigurationProvider.cs
  src/Shared/Neo.Build.ToolSet/Services/NeoSystemDefaults.cs
  src/Shared/Neo.Build.ToolSet/config.json
  tests/Neo.Build.Core.Tests/Factories/UT_RandomFactory.cs
Labels: Blocked, Waiting for Review, Neo Build

#3808 [`Style`]: move string extension method to StringExtension.cs
  benchmarks/Neo.VM.Benchmarks/InstructionBuilder/InstructionBuilder.cs
  src/Neo.CLI/CLI/MainService.Tools.cs
  src/Neo.Extensions/StringExtensions.cs
  src/Neo.Extensions/Utility.cs
  src/Neo.IO/MemoryReader.cs
  src/Neo.VM/Neo.VM.csproj
  src/Neo.VM/ScriptBuilder.cs
  src/Neo.VM/Types/Buffer.cs
  src/Neo.VM/Types/ByteString.cs
  src/Neo.VM/Types/StackItem.cs
  src/Neo.VM/Utility.cs
  src/Neo/Extensions/IO/BinaryWriterExtensions.cs
  src/Neo/SmartContract/ApplicationEngine.Runtime.cs
  src/Neo/SmartContract/Manifest/ContractManifest.cs
  src/Neo/SmartContract/Native/OracleContract.cs
  src/Plugins/OracleService/OracleService.cs
  src/Plugins/OracleService/Protocols/OracleHttpsProtocol.cs
  src/Plugins/OracleService/Protocols/OracleNeoFSProtocol.cs
  tests/Neo.Extensions.Tests/UT_StringExtensions.cs
  tests/Neo.Plugins.OracleService.Tests/UT_OracleService.cs
  tests/Neo.VM.Tests/UT_Utility.cs
Labels: Ready to Merge

#3801 Nullable for `HashIndexState` and `TransactionState`
  src/Neo.CLI/CLI/MainService.Blockchain.cs
  src/Neo/SmartContract/Native/HashIndexState.cs
  src/Neo/SmartContract/Native/LedgerContract.cs
  src/Neo/SmartContract/Native/TransactionState.cs
Labels: Ready to Merge

#3758 Nullable `ECPoint` and `ECFieldElement`
  src/Neo.CLI/CLI/MainService.Tools.cs
  src/Neo.CLI/CLI/MainService.Vote.cs
  src/Neo/Cryptography/ECC/ECFieldElement.cs
  src/Neo/Cryptography/ECC/ECPoint.cs
  tests/Neo.UnitTests/Cryptography/ECC/UT_ECFieldElement.cs
  tests/Neo.UnitTests/Cryptography/ECC/UT_ECPoint.cs
Labels: Ready to Merge, Core

#3815 [Fix] `ECPoint.GetHashCode`
  src/Neo/Cryptography/ECC/ECCurve.cs
  src/Neo/Cryptography/ECC/ECFieldElement.cs
  src/Neo/Cryptography/ECC/ECPoint.cs
  tests/Neo.UnitTests/Cryptography/ECC/UT_ECFieldElement.cs
  tests/Neo.UnitTests/Cryptography/ECC/UT_ECPoint.cs
Labels: Ready to Merge, Easy-to-Review

#3821 [`Add`]: `TryGetHash` for `IVerifiable`
  src/Neo/Ledger/Blockchain.cs
  src/Neo/Network/P2P/Helper.cs
  src/Neo/Network/P2P/Payloads/Block.cs
  src/Neo/Network/P2P/Payloads/ExtensiblePayload.cs
  src/Neo/Network/P2P/Payloads/Header.cs
  src/Neo/Network/P2P/Payloads/IVerifiable.cs
  src/Neo/Network/P2P/Payloads/Transaction.cs
  tests/Neo.UnitTests/UT_Helper.cs
Labels: Ready to Merge

#3818 Style `SQLiteWallet`
  src/Plugins/SQLiteWallet/SQLiteWallet.cs
  src/Plugins/SQLiteWallet/VerificationContract.cs
  src/Plugins/SQLiteWallet/WalletDataContext.cs
Labels: Waiting for Review, Easy-to-Review

#3816 Nullable and fix `lock` in `SQLiteWallet`
  src/Plugins/SQLiteWallet/SQLiteWallet.cs
Labels: Waiting for Review

#3823 Avoid returning the entire mempool when only `maxTransactionsPerBlock` is required
  src/Neo/Ledger/MemoryPool.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.MakePayload.cs
  tests/Neo.UnitTests/Ledger/UT_MemoryPool.cs
Labels: Ready to Merge

#3838 [MemPool] Remove constant arguments
  src/Neo/Ledger/MemoryPool.cs
Labels: Waiting for Review

#3840 [`Fix`]: `BigIntegerExtension.ModInverse` returns a wrong result if value < 0
  src/Neo.Extensions/BigIntegerExtensions.cs
  src/Neo.VM/JumpTable/JumpTable.Numeric.cs
  src/Neo.VM/Utility.cs
  tests/Neo.Extensions.Tests/UT_BigIntegerExtensions.cs
  tests/Neo.VM.Tests/UT_Utility.cs
Labels: Ready to Merge

#3802 Ensure the interop types are serializable before commit
  src/Neo/SmartContract/Native/ContractManagement.cs
  src/Neo/SmartContract/Native/LedgerContract.cs
  src/Neo/SmartContract/Native/OracleContract.cs
  src/Neo/SmartContract/Native/TrimmedBlock.cs
  src/Neo/SmartContract/StorageItem.cs
Labels: Bug, Critical, Ready to Merge

#3829 Ensure `IInteroperable.Clone`
  src/Neo/Network/P2P/Payloads/Header.cs
  src/Neo/Network/P2P/Payloads/Witness.cs
  src/Neo/SmartContract/ContractState.cs
  src/Neo/SmartContract/Native/TransactionState.cs
  src/Neo/SmartContract/Native/TrimmedBlock.cs
  tests/Neo.UnitTests/Ledger/UT_TransactionState.cs
  tests/Neo.UnitTests/Ledger/UT_TrimmedBlock.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Header.cs
  tests/Neo.UnitTests/SmartContract/UT_ContractState.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
Labels: Bug, Blocker, Ready to Merge

#3843 Review of #3782
  src/Neo/SmartContract/StorageKey.cs
Labels: Ready to Merge

#3844 [style] Clean crypto
  src/Neo/Cryptography/Crypto.cs
Labels: Ready to Merge, Easy-to-Review

#3845 [crypto] Add SHA512
  src/Neo/Cryptography/Crypto.cs
  src/Neo/Cryptography/HashAlgorithm.cs
  src/Neo/Cryptography/Helper.cs
  tests/Neo.UnitTests/Cryptography/UT_Cryptography_Helper.cs
Labels: Ready to Merge

#3846 [`Optimzie`]: remove `AsParallel` in `Cache`
  benchmarks/Neo.Benchmarks/IO/Benchmarks.Cache.cs
  src/Neo.IO/Caching/Cache.cs
Labels: Ready to Merge

#3848 add more unit tests to enforce the correctness
  tests/Neo.UnitTests/Ledger/UT_MemoryPool.cs
Labels: Ready to Merge, Unit Tests

#3849 Add build script
  scripts/build-with-plugins.bat
  scripts/build-with-plugins.md
  scripts/build-with-plugins.sh
Labels: Waiting for Review, Easy-to-Review

#3847 [`Style`]: clearer style for `Cache`
  src/Neo.IO/Caching/Cache.cs
  src/Neo.IO/Caching/FIFOCache.cs
  src/Neo/IO/Caching/ECDsaCache.cs
  src/Neo/IO/Caching/ECPointCache.cs
  src/Neo/IO/Caching/RelayCache.cs
  tests/Neo.UnitTests/IO/Caching/UT_Cache.cs
Labels: Minor Change, Easy-to-Review

#3854 format script
  scripts/run-dotnet-format.ps1
  scripts/run-dotnet-format.sh
Labels: Ready to Merge

#3853 add readme file to rpcclient
  src/Plugins/RpcClient/API_REFERENCE.md
  src/Plugins/RpcClient/README.md
Labels: Ready to Merge

#3855 Native: unify arguments naming of CryptoLib's `verifyWith*` methods
  src/Neo/SmartContract/Native/CryptoLib.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
Labels: Discussion, Ready to Merge, Easy-to-Review
