Repository neo-project/neo, pull requests merged in 2025-05, with the labels that each got.

#3919 [`Optimize`]: `Murmur128` is a noncryptographic hash aglorithm
  benchmarks/Neo.Benchmarks/Benchmarks.Hash.cs
  src/Neo/Cryptography/Helper.cs
  src/Neo/Cryptography/Murmur128.cs
  tests/Neo.UnitTests/Cryptography/UT_Murmur128.cs
Labels: Ready to Merge

#3920 [`Fix`]: getnativecontract throws null reference exception if contract not active
  src/Plugins/RpcServer/RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
Labels: Ready to Merge

#3916 [`Style`]: Move BigInteger extensions from Utility to BigIntegerExtensions
  src/Neo.Extensions/BigIntegerExtensions.cs
  src/Neo.Extensions/Neo.Extensions.csproj
  src/Neo.VM/Utility.cs
  src/Neo/Cryptography/ECC/ECCurve.cs
  src/Neo/Cryptography/ECC/ECFieldElement.cs
  src/Neo/Cryptography/ECC/ECPoint.cs
  tests/Neo.Extensions.Tests/UT_BigIntegerExtensions.cs
  tests/Neo.VM.Tests/UT_Utility.cs
Labels: Ready to Merge

#3925 [`Fix`] Avoid empty snupkg in release
  .github/workflows/nuget.yml
Labels: Ready to Merge

#3926 [`Fix`] Fix quotes in script
  scripts/run-dotnet-format.sh
Labels: Ready to Merge, Easy-to-Review

#3930 v3.8.1
  .github/workflows/main.yml
  src/Directory.Build.props
Labels: Ready to Merge

#3938 [`Fix`] Release Packages Workflow (Docker, Binaries)
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: Critical, GitHub Workflow, Easy-to-Review

#3941 V3.8.1 to master
  .github/workflows/nuget.yml
  src/Directory.Build.props
  src/Neo.CLI/CLI/MainService.Blockchain.cs
  src/Neo.CLI/CLI/MainService.Native.cs
  src/Neo/SmartContract/Native/NativeContract.cs
Labels: Ready to Merge

#3940 Add more comments for `ContractParametersContext`
  src/Neo/SmartContract/ContractParametersContext.cs
Labels: Ready to Merge

#3943 Native: unify hardfork enabling checks across native contracts
  src/Neo/SmartContract/Native/NeoToken.cs
Labels: Ready to Merge, Easy-to-Review, Core

#3932 [`Optimize`]: make BitCount simpler
  src/Neo.Extensions/BigIntegerExtensions.cs
Labels: Ready to Merge

#3937 docs: the old discord link didn't work
  README.md
Labels: Ready to Merge

#3948 [`Style`]: unify json initialization for rpc client and rpc server
  src/Neo.Network.RpcClient/Models/RpcAccount.cs
  src/Neo.Network.RpcClient/Models/RpcApplicationLog.cs
  src/Neo.Network.RpcClient/Models/RpcBlock.cs
  src/Neo.Network.RpcClient/Models/RpcBlockHeader.cs
  src/Neo.Network.RpcClient/Models/RpcInvokeResult.cs
  src/Neo.Network.RpcClient/Models/RpcNep17Balances.cs
  src/Neo.Network.RpcClient/Models/RpcNep17Transfers.cs
  src/Neo.Network.RpcClient/Models/RpcPeers.cs
  src/Neo.Network.RpcClient/Models/RpcPlugin.cs
  src/Neo.Network.RpcClient/Models/RpcRawMemPool.cs
  src/Neo.Network.RpcClient/Models/RpcRequest.cs
  src/Neo.Network.RpcClient/Models/RpcResponse.cs
  src/Neo.Network.RpcClient/Models/RpcTransaction.cs
  src/Neo.Network.RpcClient/Models/RpcTransferOut.cs
  src/Neo.Network.RpcClient/Models/RpcUnclaimedGas.cs
  src/Neo.Network.RpcClient/Models/RpcValidateAddressResult.cs
  src/Neo.Network.RpcClient/Models/RpcValidator.cs
  src/Neo.Network.RpcClient/Models/RpcVersion.cs
  src/Plugins/RpcServer/RpcError.cs
  src/Plugins/RpcServer/RpcServer.Node.cs
  src/Plugins/RpcServer/RpcServer.SmartContract.cs
  src/Plugins/RpcServer/RpcServer.Utilities.cs
  tests/Neo.Network.RPC.Tests/UT_TransactionManager.cs
  tests/Neo.Network.RPC.Tests/UT_WalletAPI.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcErrorHandling.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Blockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.cs
Labels: Ready to Merge

#3939 [`Fix`]: `ISigner` Only sign consensus messages
  src/Neo.CLI/CLI/MainService.Wallet.cs
  src/Neo.CLI/CLI/MainService.cs
  src/Neo/Sign/ISigner.cs
  src/Neo/Sign/SignerManager.cs
  src/Neo/Wallets/Wallet.cs
  src/Plugins/DBFTPlugin/Consensus/ConsensusContext.MakePayload.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.cs
  tests/Neo.UnitTests/Wallets/UT_Wallet.cs
Labels: Ready to Merge

#3949 [`Optimize`]: use `SequenceCompareTo` to compare bytes in `MPTTrie`
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Helper.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.Find.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Helper.cs
Labels: Ready to Merge

#3953 [`Bug`] Fix MemorySnapshot bug
  src/Neo/Persistence/Providers/MemorySnapshot.cs
  tests/Neo.UnitTests/Persistence/UT_MemorySnapshot.cs
Labels: Bug

#3952 [`ut`] 100% Coverage Trie.Get
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.Delete.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.Find.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.Get.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.Proof.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.Put.cs
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Trie.cs
Labels: Ready to Merge

#3954 New Dockerfile, New Makefile
  README.md
  src/Neo.CLI/Dockerfile
  src/Neo.CLI/Makefile
  src/Neo.CLI/prepare-node.sh
  src/Neo.CLI/start.sh
Labels: Ready to Merge

#3918 [`Optimize`]: command tokenizer
  src/Neo.ConsoleService/CommandQuoteToken.cs
  src/Neo.ConsoleService/CommandSpaceToken.cs
  src/Neo.ConsoleService/CommandStringToken.cs
  src/Neo.ConsoleService/CommandToken.cs
  src/Neo.ConsoleService/CommandTokenType.cs
  src/Neo.ConsoleService/CommandTokenizer.cs
  src/Neo.ConsoleService/ConsoleCommandMethod.cs
  src/Neo.ConsoleService/ConsoleServiceBase.cs
  tests/Neo.ConsoleService.Tests/CommandTokenTest.cs
  tests/Neo.ConsoleService.Tests/CommandTokenizerTest.cs
Labels: Ready to Merge

#3951 [`Style`]: make the code style of `StatePlugin` more standard
  src/Plugins/StateService/Network/StateRoot.cs
  src/Plugins/StateService/StatePlugin.cs
  src/Plugins/StateService/Storage/StateSnapshot.cs
  src/Plugins/StateService/Storage/StateStore.cs
  src/Plugins/StateService/Verification/VerificationContext.cs
  src/Plugins/StateService/Verification/VerificationService.cs
Labels: Ready to Merge, NGD Review

#3958 Optimize: for prepare.sh: 1. show usage if arg not provided; 2. remove downloaded zip files after unzip
  .gitignore
  scripts/run-dotnet-format.sh
  src/Neo.CLI/prepare-node.sh
Labels: Ready to Merge

#3964 Update .NET SDK version from 9.0.203 to 9.0.300
  global.json
Labels: Ready to Merge, Easy-to-Review

#3960 docs: Add contribution guidelines and branch rules to README
  README.md
Labels: NGD Review, Easy-to-Review

#3956 [UnitTest] Increase unit test coverage for UInt160 and UInt256
  src/Neo/UInt160.cs
  src/Neo/UInt256.cs
  tests/Neo.UnitTests/UT_UInt160.cs
  tests/Neo.UnitTests/UT_UInt256.cs
Labels: Ready to Merge

#3955 Optimize: Merge duplicated code in MainService into the `LoadScript` method
  src/Neo.CLI/CLI/MainService.cs
Labels: Waiting for Review, Ready to Merge, NGD Review

#3959 docs: Add Neo persistence system architecture documentation
  docs/persistence-architecture.md
Labels: Waiting for Review

#3967 [feature] Storage events
  src/Neo/Persistence/DataCache.cs
  src/Neo/Persistence/IStore.cs
  src/Neo/Persistence/Providers/MemoryStore.cs
  src/Plugins/LevelDBStore/Plugins/Storage/Store.cs
  src/Plugins/RocksDBStore/Plugins/Storage/Store.cs
  tests/Neo.UnitTests/Persistence/UT_DataCache.cs
Labels: Ready to Merge
