Repository neo-project/neo, pull requests merged in 2025-06, with the labels that each got.

#3972 Optimize: keep more exception info in UInt160.Parse and UInt256.Parse
  src/Neo.Extensions/StringExtensions.cs
  src/Neo/UInt160.cs
  src/Neo/UInt256.cs
  tests/Neo.Extensions.Tests/UT_StringExtensions.cs
Labels: Ready to Merge

#3986 tests: extend StdLib's unit tests
  tests/Neo.UnitTests/SmartContract/Native/UT_StdLib.cs
Labels: Unit Tests, Easy-to-Review

#3990 Optimize: use CommonPrefixLength instead in Trie.Put
  src/Neo.Cryptography.MPTTrie/Cryptography/MPTTrie/Trie.Put.cs
Labels: Ready to Merge

#3985 Create monthly issue metrics
  .github/workflows/issue-metrics.yml
Labels: Ready to Merge

#4005 Fix Threading hanging with `NeoSystem`
  src/Neo/NeoSystem.cs
Labels: Ready to Merge, Easy-to-Review

#4004 Style: unify json init style
  src/Neo/Network/P2P/Payloads/Signer.cs
  src/Neo/SmartContract/ContractParametersContext.cs
  src/Neo/SmartContract/Manifest/ContractAbi.cs
  src/Neo/SmartContract/Manifest/ContractEventDescriptor.cs
  src/Neo/SmartContract/Manifest/ContractGroup.cs
  src/Neo/SmartContract/Manifest/ContractParameterDefinition.cs
  src/Neo/SmartContract/Manifest/ContractPermission.cs
  src/Plugins/ApplicationLogs/LogReader.cs
  src/Plugins/StorageDumper/StorageDumper.cs
  tests/Neo.Json.UnitTests/UT_JArray.cs
  tests/Neo.Json.UnitTests/UT_JObject.cs
  tests/Neo.Network.RPC.Tests/UT_TransactionManager.cs
  tests/Neo.Plugins.OracleService.Tests/TestUtils.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
  tests/Neo.UnitTests/SmartContract/Manifest/UT_WildCardContainer.cs
  tests/Neo.UnitTests/TestUtils.cs
  tests/Neo.UnitTests/Wallets/NEP6/UT_NEP6Wallet.cs
  tests/Neo.UnitTests/Wallets/NEP6/UT_ScryptParameters.cs
Labels: Waiting for Review, NGD Review, Easy-to-Review

#3473 Restore DBFTPlugin Unit Tests (ConsensusService and Consensus Context)
  .github/workflows/main.yml
  src/Neo/Neo.csproj
  src/Plugins/DBFTPlugin/Consensus/ConsensusService.cs
  src/Plugins/DBFTPlugin/DBFTPlugin.csproj
  tests/Neo.Plugins.DBFTPlugin.Tests/ConsensusTestUtilities.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/MockAutoPilot.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/MockBlockchain.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/MockMemoryStoreProvider.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/MockProtocolSettings.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/MockWallet.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/README.md
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_ConsensusContext.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_ConsensusService.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Core.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Failures.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Integration.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_MessageFlow.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_NormalFlow.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Performance.cs
  tests/Neo.Plugins.DBFTPlugin.Tests/UT_DBFT_Recovery.cs
Labels: Ready to Merge

#4011 Fix: move MPT Benchmark Project to benchmarks/
  benchmarks/Neo.Cryptography.MPTTrie.Benchmarks/Benchmarks.Cache.cs
  benchmarks/Neo.Cryptography.MPTTrie.Benchmarks/Neo.Cryptography.MPTTrie.Benchmarks.csproj
  benchmarks/Neo.Cryptography.MPTTrie.Benchmarks/Program.cs
  neo.sln
Labels: Waiting for Review, Easy-to-Review

#4021 Add: add exception info comments for numeric ops
  src/Neo.VM/JumpTable/JumpTable.Numeric.cs
  tests/Neo.VM.Tests/UT_StackItem.cs
Labels: Ready to Merge, Easy-to-Review

#4034 Cache nuget packages
  .github/workflows/main.yml
Labels: Ready to Merge

#4031 Add: more semantics description and better impl for 'TestBit`
  src/Neo.Extensions/BigIntegerExtensions.cs
  tests/Neo.Extensions.Tests/UT_BigIntegerExtensions.cs
Labels: Ready to Merge, Easy-to-Review

#4030 Optimize: impl `GetLowestSetBit` by `TrailingZeroCount` if available
  src/Neo.Extensions/BigIntegerExtensions.cs
  tests/Neo.Extensions.Tests/UT_BigIntegerExtensions.cs
Labels: Ready to Merge
