Repository neo-project/neo, pull requests merged in 2025-01, with the labels that each got.

#3649 [README] update readme
  README.md
Labels: Waiting for Review, Ready to Merge, Easy-to-Review

#3652 [`Fix`]: keep the first parameter name of the `Seek` method the same
  src/Neo/Persistence/IReadOnlyStore.cs
  src/Neo/Persistence/MemorySnapshot.cs
  src/Neo/Persistence/MemoryStore.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Helper.cs
  src/Plugins/LevelDBStore/Plugins/Storage/Snapshot.cs
  src/Plugins/LevelDBStore/Plugins/Storage/Store.cs
  src/Plugins/RocksDBStore/Plugins/Storage/Snapshot.cs
  src/Plugins/RocksDBStore/Plugins/Storage/Store.cs
Labels: Ready to Merge

#3664 Fix mac ut
  .github/workflows/main.yml
Labels: Blocker, Waiting for Review, Easy-to-Review

#3658 Update `m` doc
  src/Neo/SmartContract/ApplicationEngine.Contract.cs
  src/Neo/SmartContract/Contract.cs
  src/Neo/SmartContract/Helper.cs
Labels: Blocked, Ready to Merge, Easy-to-Review

#3657 Add Log level
  src/Neo.CLI/CLI/CommandLineOption.cs
  src/Neo.CLI/CLI/MainService.CommandLine.cs
  src/Neo.CLI/CLI/MainService.cs
  src/Neo.Extensions/Utility.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Node.cs
Labels: Ready to Merge

#3656 Use the right type for Opcode casting
  src/Neo.VM/Instruction.cs
Labels: Ready to Merge

#3661 [`Fix`]: `HashSizeValue` should be set in implementations of `System.Security.Cryptography.HashAlgorithm`
  src/Neo/Cryptography/Murmur128.cs
  src/Neo/Cryptography/Murmur32.cs
  src/Neo/Cryptography/RIPEMD160Managed.cs
  tests/Neo.UnitTests/Cryptography/UT_Murmur128.cs
  tests/Neo.UnitTests/Cryptography/UT_Murmur32.cs
  tests/Neo.UnitTests/Cryptography/UT_RIPEMD160Managed.cs
Labels: Ready to Merge

#3507 [Core Add] Add support to Ed25519
  src/Neo/Cryptography/Ed25519.cs
  src/Neo/SmartContract/Native/CryptoLib.cs
  tests/Neo.UnitTests/Cryptography/UT_Ed25519.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_CryptoLib.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
Labels: Waiting for Review, Ready to Merge, Waiting-Hardfork

#3662 Remove blame tests
  .github/workflows/main.yml
Labels: Waiting for Review, GitHub Workflow

#3659 Allow ReadOnlySpan in RIPEMD160
  src/Neo/Cryptography/Helper.cs
Labels: Waiting for Review

#3671 Fix and optimize `DataCache.Commit`
  src/Neo/Persistence/DataCache.cs
Labels: Bug, Waiting for Review, Ready to Merge

#3672 .Net SDK upgraded, but `LangVersion` not.
  src/Directory.Build.props
Labels: Ready to Merge

#3655 Disable compression by p2p
  src/Neo.CLI/Settings.cs
  src/Neo.CLI/config.fs.mainnet.json
  src/Neo.CLI/config.fs.testnet.json
  src/Neo.CLI/config.json
  src/Neo.CLI/config.mainnet.json
  src/Neo.CLI/config.testnet.json
  src/Neo/Network/P2P/Capabilities/DisableCompressionCapability.cs
  src/Neo/Network/P2P/Capabilities/NodeCapabilityType.cs
  src/Neo/Network/P2P/ChannelsConfig.cs
  src/Neo/Network/P2P/Message.cs
  src/Neo/Network/P2P/Payloads/VersionPayload.cs
  src/Neo/Network/P2P/Peer.cs
  src/Neo/Network/P2P/RemoteNode.cs
Labels: Ready to Merge

#3675 [Fix] Set max entries for `VerifyProof` in `statePlugin`
  src/Plugins/StateService/StatePlugin.cs
Labels: Bug, Waiting for Review, Easy-to-Review

#3670 Nullable in Storage classes
  src/Neo/Persistence/ClonedCache.cs
  src/Neo/Persistence/DataCache.cs
  src/Neo/Persistence/MemorySnapshot.cs
  src/Neo/Persistence/MemoryStore.cs
  src/Neo/Persistence/SnapshotCache.cs
Labels: Blocker, Waiting for Review

#3674 [`Improve`] CalculateNetworkFee
  src/Neo/Wallets/Helper.cs
  src/Neo/Wallets/Wallet.cs
  src/Plugins/RpcServer/RpcServer.Wallet.cs
Labels: Waiting for Review

#3679 Fix `HF_Echidna` comments
  src/Neo.CLI/config.fs.mainnet.json
  src/Neo.CLI/config.json
  src/Neo.CLI/config.mainnet.json
  src/Neo.CLI/config.testnet.json
  src/Neo/Cryptography/Ed25519.cs
  src/Neo/ProtocolSettings.cs
  src/Neo/SmartContract/Native/CryptoLib.cs
  src/Neo/SmartContract/Native/LedgerContract.cs
  src/Neo/SmartContract/Native/RoleManagement.cs
Labels: Waiting for Review

#3684 [`Update`] Dotnet & Compiler Version
  .devcontainer/devcontainer.dockerfile
  benchmarks/Directory.Build.props
  global.json
  tests/Directory.Build.props
Labels: Waiting for Review

#3687 Enforcement Compiler Warnings
  benchmarks/Directory.Build.props
  benchmarks/Neo.Json.Benchmarks/Benchmark_JsonDeserialize.cs
  benchmarks/Neo.Json.Benchmarks/Benchmark_OrderedDictionary.cs
  benchmarks/Neo.Json.Benchmarks/Neo.Json.Benchmarks.csproj
  benchmarks/Neo.Json.Benchmarks/Program.cs
  src/Directory.Build.props
  src/Neo.CLI/CLI/MainService.cs
  src/Neo.Extensions/ByteExtensions.cs
  src/Neo.Extensions/Collections/CollectionExtensions.cs
  src/Neo.Extensions/StringExtensions.cs
  src/Neo/Persistence/MemoryStore.cs
  src/Plugins/RpcServer/Result.cs
  tests/Directory.Build.props
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Node.cs
  tests/Neo.Cryptography.MPTTrie.Tests/Cryptography/MPTTrie/UT_Trie.cs
  tests/Neo.Extensions.Tests/Collections/UT_CollectionExtensions.cs
  tests/Neo.Extensions.Tests/Collections/UT_HashSetExtensions.cs
  tests/Neo.Extensions.Tests/UT_ByteArrayComparer.cs
  tests/Neo.Extensions.Tests/UT_ByteExtensions.cs
  tests/Neo.Extensions.Tests/UT_StringExtensions.cs
  tests/Neo.Extensions.Tests/UT_UnsafeData.cs
  tests/Neo.Json.UnitTests/UT_JArray.cs
  tests/Neo.Network.RPC.Tests/UT_Utility.cs
  tests/Neo.Plugins.ApplicationLogs.Tests/Setup/TestStorage.cs
  tests/Neo.Plugins.ApplicationLogs.Tests/UT_LogReader.cs
  tests/Neo.Plugins.OracleService.Tests/E2E_Https.cs
  tests/Neo.Plugins.OracleService.Tests/TestBlockchain.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_Result.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.SmartContract.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Utilities.cs
  tests/Neo.Plugins.RpcServer.Tests/UT_RpcServer.Wallet.cs
  tests/Neo.Plugins.Storage.Tests/StoreTest.cs
  tests/Neo.UnitTests/IO/Caching/UT_KeyedCollectionSlim.cs
  tests/Neo.UnitTests/Ledger/UT_HeaderCache.cs
  tests/Neo.UnitTests/Network/P2P/Capabilities/UT_ArchivalNodeCapability.cs
  tests/Neo.UnitTests/Network/P2P/Capabilities/UT_UnknownCapability.cs
  tests/Neo.UnitTests/Network/P2P/Payloads/UT_Header.cs
  tests/Neo.UnitTests/Persistence/UT_CloneCache.cs
  tests/Neo.UnitTests/Persistence/UT_MemoryClonedCache.cs
  tests/Neo.UnitTests/Persistence/UT_MemorySnapshot.cs
  tests/Neo.UnitTests/SmartContract/UT_SmartContractHelper.cs
  tests/Neo.UnitTests/TestBlockchain.cs
  tests/Neo.UnitTests/UT_DataCache.cs
  tests/Neo.UnitTests/UT_UInt160.cs
Labels: Ready to Merge

#3685 Nullable leveldb
  src/Neo/Persistence/IReadOnlyStore.cs
  src/Neo/Persistence/MemoryStore.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/DB.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Helper.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Iterator.cs
  src/Plugins/LevelDBStore/IO/Data/LevelDB/Native.cs
  src/Plugins/LevelDBStore/LevelDBStore.csproj
  src/Plugins/LevelDBStore/Plugins/Storage/Snapshot.cs
  src/Plugins/LevelDBStore/Plugins/Storage/Store.cs
Labels: Waiting for Review

#3686 Nullable rocks db
  src/Plugins/RocksDBStore/Plugins/Storage/Options.cs
  src/Plugins/RocksDBStore/Plugins/Storage/Snapshot.cs
  src/Plugins/RocksDBStore/Plugins/Storage/Store.cs
  src/Plugins/RocksDBStore/RocksDBStore.csproj
Labels: Ready to Merge

#3689 [`Fix`]: add lock for RocksDbStore.Snapshot.WriteBatch to keep same behavior
  src/Plugins/RocksDBStore/Plugins/Storage/Snapshot.cs
Labels: Ready to Merge

#3454 Add hardfork HF_Echidna
  src/Neo.VM/JumpTable/JumpTable.Splice.cs
  src/Neo/Cryptography/Ed25519.cs
  src/Neo/Hardfork.cs
  src/Neo/Neo.csproj
  src/Neo/ProtocolSettings.cs
  src/Neo/SmartContract/ApplicationEngine.cs
  src/Neo/SmartContract/Contract.cs
  src/Neo/SmartContract/Native/ContractMethodAttribute.cs
  src/Neo/SmartContract/Native/ContractMethodMetadata.cs
  src/Neo/SmartContract/Native/CryptoLib.cs
  src/Neo/SmartContract/Native/FungibleToken.cs
  src/Neo/SmartContract/Native/NativeContract.cs
  src/Neo/SmartContract/Native/NeoToken.cs
  src/Neo/SmartContract/Native/RoleManagement.cs
  src/Neo/SmartContract/Native/StdLib.cs
  src/Plugins/StatelessBlock/StatelessBlock.cs
  src/Plugins/StatelessBlock/StatelessBlock.csproj
  tests/Neo.UnitTests/Cryptography/UT_Ed25519.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_CryptoLib.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_NeoToken.cs
  tests/Neo.UnitTests/SmartContract/Native/UT_StdLib.cs
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngine.Contract.cs
  tests/Neo.UnitTests/SmartContract/UT_ApplicationEngineProvider.cs
  tests/Neo.UnitTests/SmartContract/UT_Contract.cs
  tests/Neo.UnitTests/SmartContract/UT_Helper.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropPrices.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.NEO.cs
  tests/Neo.UnitTests/SmartContract/UT_InteropService.cs
  tests/Neo.UnitTests/SmartContract/UT_JsonSerializer.cs
  tests/Neo.UnitTests/SmartContract/UT_NotifyEventArgs.cs
  tests/Neo.UnitTests/SmartContract/UT_Syscalls.cs
  tests/Neo.UnitTests/UT_ProtocolSettings.cs
  tests/Neo.UnitTests/VM/UT_Helper.cs
  tests/Neo.VM.Tests/Tests/OpCodes/Splice/SUBSTR.json
Labels: Waiting for Review, Ready to Merge

#3695 [Core P2P] fix the bug
  src/Neo/Network/P2P/RemoteNode.cs
Labels: Waiting for Review

#3692 Update nugets
  benchmarks/Neo.Benchmarks/Neo.Benchmarks.csproj
  src/Neo.ConsoleService/Neo.ConsoleService.csproj
  src/Neo.Extensions/Neo.Extensions.csproj
  src/Neo.Json/Neo.Json.csproj
  src/Neo.VM/Neo.VM.csproj
  src/Neo/Ledger/MemoryPool.cs
  src/Neo/Neo.csproj
  src/Plugins/RocksDBStore/RocksDBStore.csproj
  src/Plugins/SQLiteWallet/SQLiteWallet.csproj
  tests/Directory.Build.props
  tests/Neo.ConsoleService.Tests/Neo.ConsoleService.Tests.csproj
  tests/Neo.Cryptography.BLS12_381.Tests/Neo.Cryptography.BLS12_381.Tests.csproj
  tests/Neo.Cryptography.MPTTrie.Tests/Neo.Cryptography.MPTTrie.Tests.csproj
  tests/Neo.Extensions.Tests/Neo.Extensions.Tests.csproj
  tests/Neo.Json.UnitTests/Neo.Json.UnitTests.csproj
  tests/Neo.Network.RPC.Tests/Neo.Network.RPC.Tests.csproj
  tests/Neo.Plugins.ApplicationLogs.Tests/Neo.Plugins.ApplicationLogs.Tests.csproj
  tests/Neo.Plugins.OracleService.Tests/Neo.Plugins.OracleService.Tests.csproj
  tests/Neo.Plugins.RpcServer.Tests/Neo.Plugins.RpcServer.Tests.csproj
  tests/Neo.Plugins.Storage.Tests/Neo.Plugins.Storage.Tests.csproj
  tests/Neo.UnitTests/Cryptography/UT_Ed25519.cs
  tests/Neo.UnitTests/Neo.UnitTests.csproj
  tests/Neo.UnitTests/UT_ProtocolSettings.cs
  tests/Neo.VM.Tests/Neo.VM.Tests.csproj
Labels: Ready to Merge

#3697 [`Add`]: unit tests for special parameter position for `ContractMethod`
  tests/Neo.UnitTests/SmartContract/Native/UT_NativeContract.cs
Labels: Ready to Merge

#3668 `Murmur3` should not be cryptographic hash algorithm
  src/Neo/Cryptography/Helper.cs
  src/Neo/Cryptography/Murmur32.cs
  src/Neo/SmartContract/Native/CryptoLib.cs
  tests/Neo.UnitTests/Cryptography/UT_Murmur32.cs
Labels: Ready to Merge

#3702 Fix `GetAndChange` warnings
  src/Neo/Persistence/DataCache.cs
Labels: Ready to Merge, Easy-to-Review

#3704 Fix: return NotNullIfNotNull
  src/Neo/Persistence/DataCache.cs
Labels: Ready to Merge, Easy-to-Review
